In [1]:
setwd('/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb/')
devtools::load_all('utils/modules/R/prstools')

i Loading PRStools

Loading required package: bigsnpr

Loading required package: bigstatsr

Loading required package: data.table

Loading required package: bigassertr

! Adding files missing in collate: /gpfs3/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb/utils/modules/R/prstools/R/qc_sumstat.R

In [2]:
args <- list(
  chrom = "chr21",
  pred = "data/prs/hapmap/ukb_500k/ukb_hapmap_500k_eur_chr21.bed",
  gwas = "data/prs/sumstat/cts/by_chrom/ukb_hapmap_500k_eur_Alanine_aminotransferase_chr21.txt.gz",
  ldsc = "data/prs/ldsc/ldsc_CAD_combined.rds",
  ld_dir = "data/prs/hapmap/ld/matrix",
  ld_bed = "data/prs/hapmap/ld/unrel_eur_10k/short_merged_ukb_hapmap_rand_10k_eur.bed",
  method = "inf"
)

lapply(args, file.exists)

$chrom
[1] FALSE

$pred
[1] TRUE

$gwas
[1] TRUE

$ldsc
[1] TRUE

$ld_dir
[1] TRUE

$ld_bed
[1] TRUE

$method
[1] FALSE

In [3]:
gwas <- read_hail_sumstat(args$gwas, trait = "cts")

In [4]:
pred <- load_bigsnp_from_bed(args$ld_bed)

In [5]:
info_snp <- snp_match(gwas, pred$map, join_by_pos = TRUE, strand_flip = FALSE)

16,726 variants to be matched.

Some duplicates were removed.

16,686 variants have been matched; 0 were flipped and 0 were reversed.

In [6]:
head(gwas)

  chr   pos      rsid               a1 a0 n_eff  beta_se   p       beta
1 chr21 10510446 chr21:10510446_A_G G  A  363339 0.0023193 0.19934  0.00297660
2 chr21 13222943 chr21:13222943_T_A A  T  363339 0.0037778 0.89046  0.00052031
3 chr21 13258267 chr21:13258267_A_G G  A  363339 0.0010081 0.67615 -0.00042109
4 chr21 13268079 chr21:13268079_G_A A  G  363339 0.0010081 0.70384 -0.00038321
5 chr21 13270143 chr21:13270143_A_G G  A  363339 0.0010084 0.67495 -0.00042290
6 chr21 13277477 chr21:13277477_C_A A  C  363339 0.0010088 0.47966 -0.00071309
  INFO MAF
1 NA   0.051302
2 NA   0.018222
3 NA   0.472800
4 NA   0.472810
5 NA   0.472670
6 NA   0.477230

In [8]:
res <- qc_sumstat(pred$G, info_snp, trait = "cts")

In [9]:
sum(res$is_bad)

[1] 546

In [36]:
G <- pred$G

In [71]:
maf <- snp_MAF(G, ind.col = info_snp$`_NUM_ID_`, ncores = 1)

In [42]:
n <- unique(gwas$n)

In [57]:
min(sqrt(0.5) * info_snp$beta_se^2 * n)

[1] 0.2524176

In [64]:
sd_val <- sqrt(2 * maf * (1 - maf))
sd_y <- min(sqrt(0.5) * info_snp$beta_se^2 * n)
sd_ss <- with(info_snp, sd_y / sqrt(n_eff * beta_se^2 + beta^2))

In [70]:
min(sqrt(0.5) * info_snp$beta_se^2 * n)

[1] 0.2524176

In [65]:
is_bad_sd <-
      sd_ss < (0.5 * sd_val) | sd_ss > (sd_val + 0.1) | sd_ss < 0.1 | sd_val < 0.05

In [66]:
is_bad_maf <- is.na(maf)
is_bad <- (is_bad_sd | is_bad_maf)
sum_is_bad <- sum(is_bad, na.rm = TRUE)
sum_n <- length(is_bad)
print(paste(sum_is_bad, 'of', sum_n, 'SNPs fail QC'))

[1] "546 of 16686 SNPs fail QC"

In [49]:
qc_binary_sumstat <- function(G, info_snp, n_eff, ncores = 1){
    maf <- snp_MAF(G, ind.col = info_snp$`_NUM_ID_`, ncores = ncores)
    sd_val <- sqrt(2 * maf * (1 - maf))
    sd_ss <- with(info_snp, 2 / sqrt(n_eff * beta_se^2 + beta^2))
    is_bad_sd <-
      sd_ss < (0.5 * sd_val) | sd_ss > (sd_val + 0.1) | sd_ss < 0.1 | sd_val < 0.05
    is_bad_maf <- is.na(maf)
    is_bad <- (is_bad_sd | is_bad_maf)
    sum_is_bad <- sum(is_bad, na.rm = TRUE)
    sum_n <- length(is_bad)
    write(paste(sum_is_bad, 'of', sum_n, 'SNPs fail QC'), stderr())
    return(list(is_bad = is_bad, sd_val = sd_val, sd_ss = sd_ss))
}

In [3]:
# laod ldsc and qced GWAS
  ldsc <- readRDS(args$ldsc)
  gwas <- ldsc$gwas
  h2 <- ldsc$h2_est

  # Estimate h2 chromosome-wide
  N_total <- nrow(gwas)
  N_chr <- sum(gwas$chr == args$chr)
  h2_init <- h2 * (N_chr / N_total)

  # check estimates
  stopifnot(h2_init > 0)
  stopifnot(!is.null(gwas))

In [4]:
  # get SNP correlations and LD
  snp <- get_single_ld_matrix(gwas, chr = args$chrom, ld_dir = args$ld_dir)

  # match GWAS with snp-correlation map
  indicies <- na.omit(match(snp$map$marker, gwas$marker))
  gwas <- gwas[indicies,]

  # check that LD-matrix markers and gwas markers have overlap
  # Check that ordering of markers are actually matching
  stopifnot(all(gwas$marker %in% snp$map$marker))
  stopifnot(all(snp$map$marker %in% gwas$marker))
  stopifnot(sum(gwas$marker == snp$map$marker) / nrow(gwas) == 1)

In [5]:
   # load data to be used for prediction
  pred <- load_bigsnp_from_bed(args$pred)
  pred <- match_bigsnp_with_gwas(pred, gwas)
  genotypes <- pred$genotypes
  indicies <- pred$gwas_indciess

In [6]:
dim(snp$corr); nrow(gwas); beta_inf

[1] 16307 16307

[1] 16307

ERROR: Error in eval(expr, envir, enclos): object 'beta_inf' not found

[1] 16307

In [ ]:
beta_inf <- snp_ldpred2_inf(snp$corr, gwas, h2_init)
head(beta_inf); length(beta_inf)

In [8]:
  write("Running multi_auto", stderr())
     multi_auto <- snp_ldpred2_auto(
        corr = snp$corr,
        df_beta = gwas,
        h2_init = h2_init,
        vec_p_init = seq_log(1e-4, 0.5, 30),
        verbose = TRUE,
        ncores = 1)

1: 0.000126895 // 0.000291787
2: 0.000128249 // 0.000635245
3: 0.000260636 // 0.000441418
4: 0.000325939 // 0.00049687
5: 0.000792083 // 0.00151865
6: 0.000603019 // 0.00121833
7: 0.000564929 // 0.000882717
8: 0.00103343 // 0.000913659
9: 0.000901696 // 0.00136474
10: 0.00155807 // 0.00128785
11: 0.000984423 // 0.000844179
12: 0.00193337 // 0.00128503
13: 0.00293289 // 0.00175614
14: 0.00349212 // 0.0015123
15: 0.00442031 // 0.00141285
16: 0.00450728 // 0.00145861
17: 0.00516121 // 0.00139733
18: 0.00453361 // 0.00141943
19: 0.00438279 // 0.0014346
20: 0.00418073 // 0.0016225
21: 0.00438242 // 0.00193025
22: 0.0048254 // 0.00191395
23: 0.00500898 // 0.00211204
24: 0.00617531 // 0.00223179
25: 0.00500974 // 0.00193889
26: 0.00444356 // 0.00218321
27: 0.00475744 // 0.00225841
28: 0.00540014 // 0.00213315
29: 0.00529293 // 0.00242545
30: 0.00486154 // 0.00212868
31: 0.00588552 // 0.0017127
32: 0.00615944 // 0.00159509
33: 0.00657214 // 0.00207463
34: 0.00592249 // 0.0017774
35: 0.00713606 // 0.00176886
36: 0.00728629 // 0.00189788
37: 0.00886609 // 0.00212109
38: 0.0108106 // 0.00249532
39: 0.00976029 // 0.002165
40: 0.0106001 // 0.00248134
41: 0.010094 // 0.00226442
42: 0.0110317 // 0.00270882
43: 0.0129677 // 0.00262969
44: 0.0132903 // 0.00254338
45: 0.0131076 // 0.0025801
46: 0.0135606 // 0.00229008
47: 0.0134796 // 0.00238181
48: 0.0144444 // 0.00259717
49: 0.0143889 // 0.00263371
50: 0.0145767 // 0.00261929
51: 0.0142334 // 0.00246843
52: 0.0176895 // 0.00243329
53: 0.0185106 // 0.00233637
54: 0.0199464 // 0.00258399
55: 0.0213218 // 0.00300812
56: 0.0219649 // 0.00278642
57: 0.024191 // 0.00267528
58: 0.0253218 // 0.00269985
59: 0.0252777 // 0.00232662
60: 0.0239707 // 0.00232052
61: 0.0282556 // 0.00258625
62: 0.0254906 // 0.00238208
63: 0.026978 // 0.00258084
64: 0.0259016 // 0.00268223
65: 0.0208437 // 0.00261352
66: 0.0190108 // 0.00237996
67: 0.0202505 // 0.00235362
68: 0.0215075 // 0.00206022
69: 0.0194155 // 0.00195897
70: 0.0189276 // 0.00199391
71: 0.0195503 // 0.00235817
72: 0.0210013 // 0.00242379
73: 0.0187455 // 0.00205113
74: 0.0178081 // 0.0019968
75: 0.018508 // 0.0026537
76: 0.0189373 // 0.00235099
77: 0.016695 // 0.00185891
78: 0.0160495 // 0.00194997
79: 0.0172439 // 0.00233716
80: 0.0181046 // 0.00212887
81: 0.0186007 // 0.00223264
82: 0.0184912 // 0.00212659
83: 0.0187047 // 0.0019779
84: 0.0171306 // 0.00190501
85: 0.0187427 // 0.00206267
86: 0.0189936 // 0.00198117
87: 0.0195953 // 0.00225164
88: 0.0196609 // 0.00236888
89: 0.016932 // 0.00234649
90: 0.0161503 // 0.00241217
91: 0.0181755 // 0.00242414
92: 0.0191003 // 0.00289269
93: 0.0208756 // 0.00262386
94: 0.0184734 // 0.00228293
95: 0.0176868 // 0.00252635
96: 0.0182043 // 0.00226036
97: 0.0192666 // 0.00203033
98: 0.0185775 // 0.00178231
99: 0.0181089 // 0.00180421
100: 0.017755 // 0.0018691
101: 0.0167789 // 0.00217088
102: 0.0164734 // 0.00237891
103: 0.0146962 // 0.00229924
104: 0.0161618 // 0.0024851
105: 0.0178475 // 0.00300143
106: 0.0162751 // 0.00256127
107: 0.0163157 // 0.00246202
108: 0.0209903 // 0.00266135
109: 0.0194618 // 0.00247169
110: 0.0195601 // 0.00254037
111: 0.020521 // 0.00283214
112: 0.0190478 // 0.00307128
113: 0.0169171 // 0.00297442
114: 0.0186105 // 0.00316704
115: 0.0204716 // 0.00315355
116: 0.019072 // 0.00288205
117: 0.0182949 // 0.00269272
118: 0.017132 // 0.00270881
119: 0.0159381 // 0.00277145
120: 0.0160706 // 0.00327356
121: 0.0191799 // 0.00339146
122: 0.0188426 // 0.00323207
123: 0.0198306 // 0.00290425
124: 0.019531 // 0.00246193
125: 0.018169 // 0.00233633
126: 0.0181694 // 0.00234773
127: 0.0197719 // 0.00227736
128: 0.0189375 // 0.00203638
129: 0.0202352 // 0.00222565
130: 0.0197746 // 0.00240598
131: 0.0212257 // 0.00257107
132: 0.0222063 // 0.00236708
133: 0.0208854 // 0.00247765
134: 0.0225036 // 0.002659
135: 0.0222535 // 0.00253597
136: 0.0213021 // 0.00224112
137: 0.0185308 // 0.00219315
138: 0.0146515 // 0.00213863
139: 0.0163263 // 0.00244702
140: 0.0156193 // 0.0021625
141: 0.0172955 // 0.0022971
142: 0.0160684 // 0.00217614
143: 0.0174403 // 0.00209203
144: 0.0186342 // 0.00239366
145: 0.0172007 // 0.00248622
146: 0.0190532 // 0.0026118
147: 0.019102 // 0.00241626
148: 0.0185301 // 0.00221805
149: 0.0194108 // 0.00252218
150: 0.0200464 // 0.00251654
151: 0.0193044 // 0.0024678
152: 0.0219041 // 0.0024562
153: 0.0204869 // 0.00240548
154: 0.0224693 // 0.00257348
155: 0.020571 // 0.00260508
156: 0.0153511 // 0.00262341
157: 0.0154949 // 0.00228326
158: 0.0181089 // 0.00273857
159: 0.0190699 // 0.00304125
160: 0.0197955 // 0.00250383
161: 0.0218382 // 0.00222024
162: 0.0203645 // 0.00199701
163: 0.0182072 // 0.00205497
164: 0.0162892 // 0.00167621
165: 0.0163935 // 0.00178702
166: 0.0197933 // 0.0020093
167: 0.0212196 // 0.00243086
168: 0.0210791 // 0.00230902
169: 0.0243117 // 0.00267199
170: 0.022433 // 0.00248711
171: 0.0235722 // 0.00267352
172: 0.0229442 // 0.00284357
173: 0.0222385 // 0.00279438
174: 0.0203996 // 0.00249383
175: 0.0212274 // 0.00255017
176: 0.0213691 // 0.00260095
177: 0.0185423 // 0.00195862
178: 0.0199724 // 0.00246184
179: 0.0189192 // 0.00252982
180: 0.0189052 // 0.00264233
181: 0.0189174 // 0.00254641
182: 0.0160428 // 0.00239835
183: 0.0175774 // 0.00281712
184: 0.0177699 // 0.00323309
185: 0.0185396 // 0.00342865
186: 0.0199786 // 0.00320373
187: 0.0185007 // 0.00312309
188: 0.0157697 // 0.00327898
189: 0.0147552 // 0.00322506
190: 0.0145084 // 0.00252881
191: 0.0148196 // 0.00226413
192: 0.0151309 // 0.00250558
193: 0.0139736 // 0.00224299
194: 0.0137943 // 0.00214849
195: 0.0134421 // 0.00200936
196: 0.0146654 // 0.00199954
197: 0.0134582 // 0.00204863
198: 0.0129127 // 0.0023407
199: 0.0120202 // 0.00235001
200: 0.0120332 // 0.0020294
201: 0.0128769 // 0.00191232
202: 0.0127324 // 0.00192458
203: 0.0119708 // 0.00193961
204: 0.0123811 // 0.00216284
205: 0.012396 // 0.00189035
206: 0.0113213 // 0.00231589
207: 0.0109545 // 0.00207008
208: 0.0101254 // 0.00205187
209: 0.0112989 // 0.00218946
210: 0.0108975 // 0.00259875
211: 0.010857 // 0.00241233
212: 0.0100913 // 0.00210758
213: 0.0082463 // 0.00152362
214: 0.00925222 // 0.00167982
215: 0.00955708 // 0.00186311
216: 0.0116306 // 0.00184711
217: 0.0124365 // 0.00206543
218: 0.0128017 // 0.00227829
219: 0.0125161 // 0.00258481
220: 0.0109473 // 0.00274275
221: 0.0119937 // 0.00274718
222: 0.0125432 // 0.00252744
223: 0.0106004 // 0.00236145
224: 0.00942848 // 0.0020481
225: 0.00983721 // 0.00205529
226: 0.00858651 // 0.00215202
227: 0.0100155 // 0.0022315
228: 0.00964778 // 0.00251354
229: 0.0101362 // 0.00227821
230: 0.0106066 // 0.00266133
231: 0.0107777 // 0.00269251
232: 0.00925577 // 0.00209161
233: 0.00918611 // 0.00218707
234: 0.00969573 // 0.00297548
235: 0.00803265 // 0.00279472
236: 0.00898675 // 0.00211411
237: 0.00949285 // 0.00221845
238: 0.0090933 // 0.00202759
239: 0.00780504 // 0.00193971
240: 0.00946513 // 0.00225545
241: 0.00843576 // 0.0020512
242: 0.00959393 // 0.00236951
243: 0.0109183 // 0.00257297
244: 0.0108228 // 0.00222987
245: 0.0121992 // 0.00225294
246: 0.0116566 // 0.00206853
247: 0.0104179 // 0.00190906
248: 0.00991873 // 0.00254567
249: 0.00835336 // 0.00254337
250: 0.00776548 // 0.00228596
251: 0.00850725 // 0.00232987
252: 0.00967506 // 0.00236798
253: 0.00941864 // 0.00255262
254: 0.0107584 // 0.00242749
255: 0.0103352 // 0.00255357
256: 0.00876415 // 0.00218547
257: 0.00765403 // 0.00230225
258: 0.00749734 // 0.0019688
259: 0.00763195 // 0.00196493
260: 0.00704524 // 0.00215538
261: 0.00787851 // 0.00242751
262: 0.00735607 // 0.00258262
263: 0.00623684 // 0.00204845
264: 0.00836127 // 0.00239567
265: 0.00786336 // 0.00208677
266: 0.00830366 // 0.00204379
267: 0.0094761 // 0.00206199
268: 0.00957567 // 0.00209226
269: 0.0100138 // 0.00212203
270: 0.0101507 // 0.00240031
271: 0.0102192 // 0.00221886
272: 0.00955978 // 0.001937
273: 0.0111663 // 0.00236071
274: 0.0107218 // 0.0024254
275: 0.00932568 // 0.00226356
276: 0.00843449 // 0.00171705
277: 0.00791912 // 0.00197196
278: 0.00899412 // 0.00186751
279: 0.00840631 // 0.00198478
280: 0.00779249 // 0.00211345
281: 0.00942825 // 0.00248483
282: 0.010339 // 0.00248538
283: 0.00950261 // 0.00206287
284: 0.0090791 // 0.00240788
285: 0.00702969 // 0.00205438
286: 0.00692745 // 0.00220194
287: 0.00707972 // 0.00196621
288: 0.00714006 // 0.00205188
289: 0.0077294 // 0.00214244
290: 0.00638185 // 0.00249253
291: 0.00692047 // 0.00224493
292: 0.0068563 // 0.00196962
293: 0.00642439 // 0.00201298
294: 0.00562893 // 0.00184021
295: 0.00643161 // 0.00235029
296: 0.00675977 // 0.00213873
297: 0.00621853 // 0.00205381
298: 0.00652666 // 0.00164925
299: 0.00545024 // 0.00194012
300: 0.00555237 // 0.00159151
301: 0.00615771 // 0.00200805
302: 0.00557559 // 0.00171006
303: 0.00576934 // 0.00175468
304: 0.00600852 // 0.00218196
305: 0.00661707 // 0.00246447
306: 0.00541456 // 0.00216013
307: 0.00524562 // 0.00188778
308: 0.00533105 // 0.00207732
309: 0.00490849 // 0.00166029
310: 0.00520042 // 0.00179903
311: 0.00556096 // 0.00212822
312: 0.00590599 // 0.00261488
313: 0.00593516 // 0.00214854
314: 0.0055718 // 0.00179776
315: 0.00565028 // 0.0018924
316: 0.00788808 // 0.00238996
317: 0.00621692 // 0.00172777
318: 0.00683854 // 0.00172071
319: 0.00613031 // 0.00172659
320: 0.00655707 // 0.00200479
321: 0.00625624 // 0.00177495
322: 0.00658525 // 0.00190312
323: 0.00717469 // 0.00217082
324: 0.00682467 // 0.00254994
325: 0.00474694 // 0.00231229
326: 0.00518963 // 0.00243269
327: 0.00400466 // 0.00190799
328: 0.00460659 // 0.00175793
329: 0.00398153 // 0.00170351
330: 0.00339175 // 0.0020364
331: 0.00315545 // 0.00167756
332: 0.00288592 // 0.00160682
333: 0.00460129 // 0.00191091
334: 0.00469478 // 0.00218437
335: 0.0043711 // 0.00251783
336: 0.0043116 // 0.001962
337: 0.00359706 // 0.0014261
338: 0.00398296 // 0.00177199
339: 0.00338135 // 0.00213999
340: 0.00382747 // 0.00210737
341: 0.00300939 // 0.00200646
342: 0.0029457 // 0.00173997
343: 0.00271386 // 0.00189735
344: 0.00275641 // 0.00157331
345: 0.00296059 // 0.00163628
346: 0.00328063 // 0.00122776
347: 0.00412273 // 0.00217596
348: 0.00329195 // 0.00207285
349: 0.0035774 // 0.0015329
350: 0.00339189 // 0.00154415
351: 0.00327973 // 0.00181313
352: 0.00305737 // 0.00187275
353: 0.00272894 // 0.00231346
354: 0.00245482 // 0.00189981
355: 0.00158523 // 0.00183689
356: 0.00137295 // 0.00105318
357: 0.000942434 // 0.00122303
358: 0.00140344 // 0.00110911
359: 0.00203125 // 0.00105579
360: 0.00238013 // 0.00173933
361: 0.00326963 // 0.00200745
362: 0.00344354 // 0.00157392
363: 0.00391383 // 0.00136566
364: 0.00348276 // 0.00179496
365: 0.00336089 // 0.0019133
366: 0.00392844 // 0.00196664
367: 0.00448896 // 0.00179029
368: 0.00467544 // 0.00159305
369: 0.0067247 // 0.0019606
370: 0.00757401 // 0.00211373
371: 0.0110045 // 0.00292005
372: 0.00953313 // 0.00249927
373: 0.00872274 // 0.00259581
374: 0.00972509 // 0.00270527
375: 0.00855305 // 0.00228457
376: 0.0102983 // 0.00252727
377: 0.00870418 // 0.00191687
378: 0.00868104 // 0.0022582
379: 0.0095738 // 0.00237603
380: 0.0103304 // 0.00261791
381: 0.0120158 // 0.00237896
382: 0.0118606 // 0.00248577
383: 0.0137072 // 0.00280645
384: 0.0128359 // 0.00273287
385: 0.0123554 // 0.00272638
386: 0.0114864 // 0.00248741
387: 0.0110942 // 0.00246706
388: 0.0106549 // 0.00203874
389: 0.0112345 // 0.00219611
390: 0.0115297 // 0.00249689
391: 0.0129393 // 0.00228939
392: 0.0137782 // 0.00216372
393: 0.0152741 // 0.00257624
394: 0.0147836 // 0.00296597
395: 0.0136597 // 0.00221899
396: 0.0147952 // 0.0025093
397: 0.0144234 // 0.00223825
398: 0.0143355 // 0.00216141
399: 0.0135488 // 0.00218958
400: 0.0145618 // 0.0020011
401: 0.0144289 // 0.001869
402: 0.0152738 // 0.00230149
403: 0.0146497 // 0.00252395
404: 0.0154412 // 0.00227868
405: 0.014857 // 0.00243258
406: 0.0137186 // 0.00245906
407: 0.0127332 // 0.00250788
408: 0.0111643 // 0.00247509
409: 0.00866163 // 0.00250153
410: 0.0111181 // 0.00248719
411: 0.0107064 // 0.00283744
412: 0.0112305 // 0.00239314
413: 0.0123847 // 0.00224807
414: 0.0142324 // 0.002528
415: 0.0153066 // 0.00255809
416: 0.0150911 // 0.0027222
417: 0.0163257 // 0.00253359
418: 0.0162907 // 0.00227523
419: 0.0167537 // 0.00227954
420: 0.0164643 // 0.00228151
421: 0.0152438 // 0.00218527
422: 0.0166653 // 0.00251391
423: 0.0155781 // 0.0023535
424: 0.016003 // 0.00256516
425: 0.0165209 // 0.00283722
426: 0.0148685 // 0.00237572
427: 0.015812 // 0.00239537
428: 0.0132174 // 0.00222055
429: 0.0136404 // 0.00214174
430: 0.0133026 // 0.00213156
431: 0.0127487 // 0.00203325
432: 0.0128308 // 0.00215109
433: 0.0132453 // 0.00213639
434: 0.0119086 // 0.00220168
435: 0.0128948 // 0.0021427
436: 0.0129924 // 0.00244249
437: 0.0123588 // 0.00292624
438: 0.0136286 // 0.00249914
439: 0.0136775 // 0.00217038
440: 0.0122514 // 0.00203313
441: 0.00886872 // 0.00151652
442: 0.00906373 // 0.00190666
443: 0.00920051 // 0.0018456
444: 0.00887207 // 0.00188381
445: 0.00890022 // 0.00221974
446: 0.00936672 // 0.00207301
447: 0.00923483 // 0.00208211
448: 0.0112778 // 0.00212801
449: 0.0108554 // 0.00236293
450: 0.011768 // 0.00226939
451: 0.0128244 // 0.00233881
452: 0.0120699 // 0.00200426
453: 0.0123582 // 0.00219092
454: 0.012153 // 0.00216499
455: 0.0118914 // 0.00226931
456: 0.012528 // 0.00227899
457: 0.0139824 // 0.00231737
458: 0.0146845 // 0.0026432
459: 0.0125825 // 0.00225308
460: 0.0103175 // 0.00204056
461: 0.0115536 // 0.00205962
462: 0.0100709 // 0.00248705
463: 0.00986192 // 0.00209265
464: 0.011062 // 0.00198639
465: 0.0113517 // 0.00213538
466: 0.0116447 // 0.002228
467: 0.0153275 // 0.00261921
468: 0.0173116 // 0.00248259
469: 0.0158208 // 0.00227926
470: 0.015674 // 0.00245112
471: 0.0182506 // 0.00242668
472: 0.0180021 // 0.00264324
473: 0.0172821 // 0.00251974
474: 0.0166583 // 0.00205543
475: 0.018063 // 0.00218601
476: 0.0184884 // 0.00237898
477: 0.0165005 // 0.00250309
478: 0.0161959 // 0.00255508
479: 0.0160619 // 0.00246918
480: 0.0163607 // 0.00260776
481: 0.0159808 // 0.00262341
482: 0.0180216 // 0.00297605
483: 0.0196867 // 0.00262975
484: 0.0211116 // 0.00229539
485: 0.022601 // 0.00246568
486: 0.0237788 // 0.00264297
487: 0.0221294 // 0.0024645
488: 0.0200357 // 0.00237475
489: 0.0185582 // 0.00215831
490: 0.0186685 // 0.00227218
491: 0.0159636 // 0.0020958
492: 0.0162851 // 0.00236877
493: 0.0169004 // 0.0022849
494: 0.0157771 // 0.00224907
495: 0.0166286 // 0.00198569
496: 0.0150078 // 0.00220225
497: 0.0152202 // 0.00227262
498: 0.0151681 // 0.00239936
499: 0.0168997 // 0.00226809
500: 0.0169757 // 0.00221988
501: 0.0173465 // 0.00241562
502: 0.0178449 // 0.00278895
503: 0.0166783 // 0.00257396
504: 0.0163828 // 0.00275389
505: 0.015005 // 0.00302897
506: 0.0134129 // 0.0026616
507: 0.0148128 // 0.00261176
508: 0.0139162 // 0.00277102
509: 0.0138928 // 0.00284385
510: 0.0144106 // 0.00238178
511: 0.0133884 // 0.00258028
512: 0.0126501 // 0.00219609
513: 0.0131826 // 0.0024616
514: 0.0133535 // 0.00296629
515: 0.0119315 // 0.00284473
516: 0.0109199 // 0.00248383
517: 0.0103838 // 0.00197681
518: 0.0103645 // 0.0018189
519: 0.00919508 // 0.00238234
520: 0.00914025 // 0.00220459
521: 0.00979173 // 0.00194524
522: 0.0102754 // 0.00201851
523: 0.0097372 // 0.0018312
524: 0.0107414 // 0.0023165
525: 0.01232 // 0.00210782
526: 0.0143334 // 0.00243799
527: 0.015536 // 0.00269443
528: 0.0157011 // 0.00257493
529: 0.0145617 // 0.00278157
530: 0.0140073 // 0.00289127
531: 0.0144172 // 0.0023089
532: 0.015185 // 0.00255446
533: 0.0149802 // 0.00225829
534: 0.0144192 // 0.00219471
535: 0.0126541 // 0.00217396
536: 0.0121296 // 0.00220846
537: 0.0106681 // 0.00227651
538: 0.0103672 // 0.00262089
539: 0.0123082 // 0.00220837
540: 0.0146703 // 0.00288324
541: 0.0169976 // 0.00293123
542: 0.01567 // 0.00259962
543: 0.0155286 // 0.00275275
544: 0.0160306 // 0.00297232
545: 0.0142706 // 0.00253456
546: 0.0113049 // 0.00246175
547: 0.0101889 // 0.00270753
548: 0.00837441 // 0.00231114
549: 0.00755769 // 0.00197646
550: 0.00709571 // 0.00215083
551: 0.00849459 // 0.0019463
552: 0.00880148 // 0.00232871
553: 0.00897452 // 0.00213091
554: 0.00846125 // 0.00239197
555: 0.0110367 // 0.00280705
556: 0.0102976 // 0.00256834
557: 0.0104877 // 0.00246003
558: 0.00888796 // 0.00262642
559: 0.00825055 // 0.00253949
560: 0.00865972 // 0.00283078
561: 0.00741725 // 0.00298364
562: 0.00823984 // 0.00234695
563: 0.00891662 // 0.00317473
564: 0.00856621 // 0.00262063
565: 0.0070729 // 0.00240715
566: 0.00666843 // 0.00227093
567: 0.00511459 // 0.00175851
568: 0.00450554 // 0.00152722
569: 0.00699416 // 0.00207872
570: 0.0072572 // 0.00197582
571: 0.00604295 // 0.00181984
572: 0.0061288 // 0.00203018
573: 0.00518858 // 0.00121442
574: 0.00567757 // 0.00158243
575: 0.00523884 // 0.00126626
576: 0.0057734 // 0.00156206
577: 0.00570356 // 0.00186405
578: 0.00758813 // 0.00239521
579: 0.00766895 // 0.00253129
580: 0.00885173 // 0.00261748
581: 0.0104627 // 0.00237779
582: 0.0118359 // 0.00281038
583: 0.0117959 // 0.00270869
584: 0.0110166 // 0.00217322
585: 0.0107334 // 0.00220447
586: 0.0123811 // 0.00219563
587: 0.0133045 // 0.00256971
588: 0.0134849 // 0.00300803
589: 0.0132532 // 0.00303159
590: 0.0142559 // 0.002795
591: 0.0129288 // 0.00268718
592: 0.0134668 // 0.00223659
593: 0.0123996 // 0.00225759
594: 0.0132142 // 0.0025178
595: 0.0130581 // 0.00242239
596: 0.0147792 // 0.00195954
597: 0.0157842 // 0.00207127
598: 0.0149549 // 0.00260938
599: 0.0154935 // 0.0026496
600: 0.0154417 // 0.00294708
601: 0.0133389 // 0.00263292
602: 0.0121924 // 0.00212377
603: 0.0124851 // 0.00217639
604: 0.0132535 // 0.00235234
605: 0.0151969 // 0.00276164
606: 0.0142772 // 0.00263299
607: 0.013368 // 0.00259903
608: 0.0124523 // 0.00256231
609: 0.0130065 // 0.00269037
610: 0.0127931 // 0.00210203
611: 0.0122167 // 0.00210869
612: 0.0133185 // 0.00231083
613: 0.0124857 // 0.00202212
614: 0.0131979 // 0.00207136
615: 0.0149102 // 0.00232789
616: 0.0132218 // 0.00235695
617: 0.0132044 // 0.00219065
618: 0.0132195 // 0.00222572
619: 0.01321 // 0.00230545
620: 0.0139902 // 0.00263801
621: 0.0141169 // 0.00257473
622: 0.0137852 // 0.0024813
623: 0.0155637 // 0.00296088
624: 0.0128179 // 0.00260224
625: 0.0137456 // 0.00257143
626: 0.0109409 // 0.00225362
627: 0.00891031 // 0.00212064
628: 0.010166 // 0.0023967
629: 0.00993285 // 0.00261516
630: 0.00856946 // 0.00181419
631: 0.00895579 // 0.00173636
632: 0.0106745 // 0.00221078
633: 0.0107833 // 0.00215051
634: 0.0116655 // 0.00255826
635: 0.0100423 // 0.00243137
636: 0.00938956 // 0.00258363
637: 0.0104837 // 0.00311371
638: 0.00952417 // 0.0026761
639: 0.0100995 // 0.00277346
640: 0.0103873 // 0.00293251
641: 0.00876035 // 0.00243831
642: 0.00745232 // 0.00220949
643: 0.00500273 // 0.001923
644: 0.00558993 // 0.00204776
645: 0.00660163 // 0.00243389
646: 0.00735355 // 0.00268662
647: 0.00660851 // 0.00276268
648: 0.00807414 // 0.00285008
649: 0.00760341 // 0.00309934
650: 0.00740514 // 0.00252836
651: 0.00663465 // 0.00229572
652: 0.00603023 // 0.00209324
653: 0.00776842 // 0.00276612
654: 0.0071997 // 0.00265576
655: 0.00665656 // 0.00183584
656: 0.00787249 // 0.00195152
657: 0.00626149 // 0.00188037
658: 0.00617631 // 0.00198539
659: 0.0087461 // 0.00241279
660: 0.00855684 // 0.00256818
661: 0.00905472 // 0.00250603
662: 0.00936405 // 0.00227111
663: 0.00754802 // 0.00176432
664: 0.00935706 // 0.0024217
665: 0.0120638 // 0.00254247
666: 0.0105092 // 0.00249541
667: 0.0112086 // 0.00296651
668: 0.0119081 // 0.00253707
669: 0.0117664 // 0.00230348
670: 0.0136643 // 0.00250043
671: 0.0137674 // 0.00258117
672: 0.0136752 // 0.00259011
673: 0.0154842 // 0.00245991
674: 0.0147864 // 0.00271654
675: 0.0138888 // 0.00300228
676: 0.012461 // 0.00274416
677: 0.0131503 // 0.00256226
678: 0.011728 // 0.00238104
679: 0.0126855 // 0.00231556
680: 0.0129954 // 0.00204722
681: 0.0121 // 0.00203653
682: 0.0116395 // 0.00228033
683: 0.0109488 // 0.00239321
684: 0.00956777 // 0.00223209
685: 0.00951938 // 0.00208814
686: 0.0109499 // 0.00265879
687: 0.0130484 // 0.0021074
688: 0.0125461 // 0.00207348

In [39]:
saveRDS(multi_auto, 'test.rda', compress = 'xz')

In [12]:
str(multi_auto)

List of 30
 $ :List of 9
  ..$ beta_est   : num [1:16307] -2.38e-04 -6.17e-06 -5.82e-06 -7.43e-06 2.78e-06 ...
  ..$ postp_est  : num [1:16307] 0.01017 0.00672 0.0067 0.00675 0.00666 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.0103
  ..$ h2_est     : num 0.00228
  ..$ path_p_est : num [1:1500] 0.000127 0.000128 0.000261 0.000326 0.000792 ...
  ..$ path_h2_est: num [1:1500] 0.000292 0.000635 0.000441 0.000497 0.001519 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 1e-04
 $ :List of 9
  ..$ beta_est   : num [1:16307] -1.84e-04 -4.94e-06 -4.71e-06 -5.74e-06 1.56e-06 ...
  ..$ postp_est  : num [1:16307] 0.00705 0.00441 0.00441 0.00443 0.00436 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.00744
  ..$ h2_est     : num 0.00215
  ..$ path_p_est : num [1:1500] 9.42e-05 2.21e-04 4.93e-04 1.87e-03 2.97e-03 ...
  ..$ path_h2_est: num [1:1500] 0.00048 0.000555 0.000502 0.001309 0.001438 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.000134
 $ :List of 9
  ..$ beta_est   : num [1:16307] -1.91e-04 -4.78e-06 -4.60e-06 -5.83e-06 1.93e-06 ...
  ..$ postp_est  : num [1:16307] 0.00771 0.00493 0.00492 0.00494 0.00489 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.00796
  ..$ h2_est     : num 0.00208
  ..$ path_p_est : num [1:1500] 0.000281 0.00051 0.000894 0.000512 0.00058 ...
  ..$ path_h2_est: num [1:1500] 0.000284 0.000676 0.0011 0.001246 0.000891 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.00018
 $ :List of 9
  ..$ beta_est   : num [1:16307] -2.01e-04 -4.83e-06 -4.55e-06 -5.68e-06 2.37e-06 ...
  ..$ postp_est  : num [1:16307] 0.00788 0.00495 0.00495 0.00497 0.00491 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.00823
  ..$ h2_est     : num 0.00225
  ..$ path_p_est : num [1:1500] 9.38e-05 2.06e-04 2.09e-04 4.32e-04 3.58e-04 ...
  ..$ path_h2_est: num [1:1500] 0.000417 0.000427 0.000479 0.000746 0.000565 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.000241
 $ :List of 9
  ..$ beta_est   : num [1:16307] -2.83e-04 -9.78e-06 -9.96e-06 -1.14e-05 9.18e-07 ...
  ..$ postp_est  : num [1:16307] 0.01342 0.00932 0.00932 0.00936 0.0092 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.0133
  ..$ h2_est     : num 0.00237
  ..$ path_p_est : num [1:1500] 0.00046 0.000761 0.001079 0.001568 0.001927 ...
  ..$ path_h2_est: num [1:1500] 0.000717 0.001075 0.001287 0.00145 0.001399 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.000324
 $ :List of 9
  ..$ beta_est   : num [1:16307] -2.60e-04 -7.09e-06 -6.90e-06 -8.63e-06 2.85e-06 ...
  ..$ postp_est  : num [1:16307] 0.01193 0.00816 0.00816 0.00819 0.00809 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.0119
  ..$ h2_est     : num 0.00225
  ..$ path_p_est : num [1:1500] 0.00024 0.000269 0.000401 0.000756 0.000713 ...
  ..$ path_h2_est: num [1:1500] 0.000537 0.000515 0.0007 0.00147 0.000729 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.000434
 $ :List of 9
  ..$ beta_est   : num [1:16307] -2.14e-04 -5.80e-06 -5.50e-06 -6.64e-06 2.08e-06 ...
  ..$ postp_est  : num [1:16307] 0.00898 0.00588 0.00588 0.00591 0.00584 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.00921
  ..$ h2_est     : num 0.0022
  ..$ path_p_est : num [1:1500] 0.000462 0.00078 0.000792 0.001324 0.001435 ...
  ..$ path_h2_est: num [1:1500] 0.001092 0.000782 0.000966 0.000847 0.00117 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.000583
 $ :List of 9
  ..$ beta_est   : num [1:16307] -2.22e-04 -5.41e-06 -5.14e-06 -6.60e-06 2.80e-06 ...
  ..$ postp_est  : num [1:16307] 0.00947 0.00623 0.00623 0.00625 0.00616 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.00965
  ..$ h2_est     : num 0.00223
  ..$ path_p_est : num [1:1500] 0.001729 0.001268 0.000967 0.001063 0.000961 ...
  ..$ path_h2_est: num [1:1500] 0.00208 0.001793 0.001267 0.000886 0.001104 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.000781
 $ :List of 9
  ..$ beta_est   : num [1:16307] -1.97e-04 -4.25e-06 -4.64e-06 -4.85e-06 3.18e-06 ...
  ..$ postp_est  : num [1:16307] 0.00787 0.00505 0.00502 0.00505 0.00501 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.00814
  ..$ h2_est     : num 0.00214
  ..$ path_p_est : num [1:1500] 0.00143 0.00151 0.00219 0.00188 0.00306 ...
  ..$ path_h2_est: num [1:1500] 0.00232 0.00192 0.00187 0.0012 0.00175 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.00105
 $ :List of 9
  ..$ beta_est   : num [1:16307] -1.95e-04 -5.04e-06 -4.82e-06 -6.04e-06 2.06e-06 ...
  ..$ postp_est  : num [1:16307] 0.00791 0.00508 0.00507 0.0051 0.00502 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.00819
  ..$ h2_est     : num 0.00215
  ..$ path_p_est : num [1:1500] 0.000978 0.000952 0.001711 0.002058 0.002406 ...
  ..$ path_h2_est: num [1:1500] 0.00139 0.00139 0.00126 0.00159 0.00189 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.00141
 $ :List of 9
  ..$ beta_est   : num [1:16307] -1.98e-04 -5.27e-06 -4.83e-06 -6.44e-06 1.83e-06 ...
  ..$ postp_est  : num [1:16307] 0.00801 0.00515 0.00512 0.00518 0.00508 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.00831
  ..$ h2_est     : num 0.00217
  ..$ path_p_est : num [1:1500] 0.00258 0.00179 0.0019 0.0015 0.00189 ...
  ..$ path_h2_est: num [1:1500] 0.0023 0.00153 0.00154 0.00123 0.00129 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.00189
 $ :List of 9
  ..$ beta_est   : num [1:16307] -2.50e-04 -6.45e-06 -6.11e-06 -7.23e-06 2.74e-06 ...
  ..$ postp_est  : num [1:16307] 0.0114 0.00776 0.00775 0.00777 0.00767 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.0115
  ..$ h2_est     : num 0.00229
  ..$ path_p_est : num [1:1500] 0.00252 0.0034 0.0032 0.00365 0.00307 ...
  ..$ path_h2_est: num [1:1500] 0.00194 0.00199 0.00218 0.0017 0.00187 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.00253
 $ :List of 9
  ..$ beta_est   : num [1:16307] -2.31e-04 -6.38e-06 -6.08e-06 -7.30e-06 2.20e-06 ...
  ..$ postp_est  : num [1:16307] 0.00959 0.00624 0.00623 0.00625 0.00617 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.00978
  ..$ h2_est     : num 0.00226
  ..$ path_p_est : num [1:1500] 0.00342 0.00293 0.0023 0.00246 0.00321 ...
  ..$ path_h2_est: num [1:1500] 0.00194 0.0019 0.00185 0.00131 0.00174 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.00339
 $ :List of 9
  ..$ beta_est   : num [1:16307] -2.63e-04 -7.06e-06 -7.07e-06 -8.51e-06 3.08e-06 ...
  ..$ postp_est  : num [1:16307] 0.01204 0.00822 0.00817 0.00826 0.00814 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.012
  ..$ h2_est     : num 0.00228
  ..$ path_p_est : num [1:1500] 0.0061 0.00448 0.00398 0.00401 0.00273 ...
  ..$ path_h2_est: num [1:1500] 0.00247 0.00241 0.00247 0.00216 0.00166 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.00455
 $ :List of 9
  ..$ beta_est   : num [1:16307] -2.58e-04 -6.96e-06 -6.59e-06 -8.44e-06 2.72e-06 ...
  ..$ postp_est  : num [1:16307] 0.01126 0.00747 0.00746 0.00748 0.00739 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.0113
  ..$ h2_est     : num 0.00228
  ..$ path_p_est : num [1:1500] 0.00719 0.0067 0.00748 0.00748 0.00675 ...
  ..$ path_h2_est: num [1:1500] 0.00219 0.00187 0.00201 0.00178 0.00165 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.00611
 $ :List of 9
  ..$ beta_est   : num [1:16307] -2.28e-04 -5.87e-06 -5.78e-06 -6.54e-06 3.49e-06 ...
  ..$ postp_est  : num [1:16307] 0.01197 0.00864 0.00863 0.00864 0.00858 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.012
  ..$ h2_est     : num 0.00216
  ..$ path_p_est : num [1:1500] 0.00789 0.00837 0.00847 0.00891 0.01148 ...
  ..$ path_h2_est: num [1:1500] 0.00217 0.00225 0.0024 0.00208 0.00215 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.00819
 $ :List of 9
  ..$ beta_est   : num [1:16307] -2.02e-04 -5.33e-06 -4.59e-06 -5.83e-06 2.42e-06 ...
  ..$ postp_est  : num [1:16307] 0.00791 0.00501 0.00503 0.00507 0.00498 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.00821
  ..$ h2_est     : num 0.00221
  ..$ path_p_est : num [1:1500] 0.0114 0.0119 0.0115 0.0122 0.0118 ...
  ..$ path_h2_est: num [1:1500] 0.0026 0.00277 0.00261 0.00216 0.00245 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.011
 $ :List of 9
  ..$ beta_est   : num [1:16307] -1.97e-04 -4.49e-06 -4.26e-06 -5.44e-06 2.50e-06 ...
  ..$ postp_est  : num [1:16307] 0.00781 0.00493 0.00493 0.00495 0.0049 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.00811
  ..$ h2_est     : num 0.00216
  ..$ path_p_est : num [1:1500] 0.0144 0.01135 0.00995 0.00909 0.00976 ...
  ..$ path_h2_est: num [1:1500] 0.00217 0.0025 0.00224 0.00253 0.00228 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.0147
 $ :List of 9
  ..$ beta_est   : num [1:16307] -1.71e-04 -3.67e-06 -3.53e-06 -4.73e-06 2.22e-06 ...
  ..$ postp_est  : num [1:16307] 0.00652 0.00405 0.00405 0.00404 0.00402 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.00692
  ..$ h2_est     : num 0.00209
  ..$ path_p_est : num [1:1500] 0.0229 0.0235 0.022 0.0183 0.0185 ...
  ..$ path_h2_est: num [1:1500] 0.00284 0.00293 0.00245 0.00247 0.00243 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.0198
 $ :List of 9
  ..$ beta_est   : num [1:16307] -1.88e-04 -5.15e-06 -4.99e-06 -6.06e-06 1.77e-06 ...
  ..$ postp_est  : num [1:16307] 0.0078 0.00506 0.00507 0.0051 0.00503 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.00805
  ..$ h2_est     : num 0.00211
  ..$ path_p_est : num [1:1500] 0.0269 0.0298 0.0293 0.0286 0.0292 ...
  ..$ path_h2_est: num [1:1500] 0.00221 0.00259 0.00263 0.00247 0.00249 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.0265
 $ :List of 9
  ..$ beta_est   : num [1:16307] -2.51e-04 -6.68e-06 -6.37e-06 -8.01e-06 2.81e-06 ...
  ..$ postp_est  : num [1:16307] 0.0118 0.00815 0.00814 0.00817 0.00808 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.0118
  ..$ h2_est     : num 0.00228
  ..$ path_p_est : num [1:1500] 0.0355 0.0337 0.0322 0.0301 0.0281 ...
  ..$ path_h2_est: num [1:1500] 0.00224 0.0022 0.00227 0.00235 0.00257 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.0356
 $ :List of 9
  ..$ beta_est   : num [1:16307] -2.00e-04 -4.91e-06 -4.76e-06 -5.84e-06 2.24e-06 ...
  ..$ postp_est  : num [1:16307] 0.00796 0.00505 0.00505 0.00506 0.005 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.00824
  ..$ h2_est     : num 0.00218
  ..$ path_p_est : num [1:1500] 0.0509 0.0531 0.0593 0.0592 0.0636 ...
  ..$ path_h2_est: num [1:1500] 0.00229 0.00256 0.00239 0.00226 0.00229 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.0477
 $ :List of 9
  ..$ beta_est   : num [1:16307] -2.25e-04 -6.31e-06 -6.01e-06 -7.62e-06 2.04e-06 ...
  ..$ postp_est  : num [1:16307] 0.00931 0.00608 0.00607 0.00609 0.006 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.00955
  ..$ h2_est     : num 0.00226
  ..$ path_p_est : num [1:1500] 0.0604 0.0611 0.0583 0.0622 0.0643 ...
  ..$ path_h2_est: num [1:1500] 0.00196 0.00202 0.00198 0.00213 0.00225 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.064
 $ :List of 9
  ..$ beta_est   : num [1:16307] -5.04e-04 -1.71e-05 -1.68e-05 -2.03e-05 6.46e-06 ...
  ..$ postp_est  : num [1:16307] 0.0425 0.0349 0.0349 0.035 0.0347 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.0407
  ..$ h2_est     : num 0.00257
  ..$ path_p_est : num [1:1500] 0.0852 0.0881 0.0919 0.0904 0.0881 ...
  ..$ path_h2_est: num [1:1500] 0.00221 0.00233 0.00233 0.00231 0.00219 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.0858
 $ :List of 9
  ..$ beta_est   : num [1:16307] -1.83e-04 -4.31e-06 -3.96e-06 -4.49e-06 2.90e-06 ...
  ..$ postp_est  : num [1:16307] 0.00722 0.0046 0.0046 0.00465 0.00461 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.00764
  ..$ h2_est     : num 0.00214
  ..$ path_p_est : num [1:1500] 0.113 0.107 0.104 0.102 0.101 ...
  ..$ path_h2_est: num [1:1500] 0.00201 0.00213 0.00194 0.00186 0.00162 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.115
 $ :List of 9
  ..$ beta_est   : num [1:16307] -2.00e-04 -5.32e-06 -5.46e-06 -6.54e-06 1.50e-06 ...
  ..$ postp_est  : num [1:16307] 0.00806 0.00516 0.00517 0.0052 0.00511 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.0083
  ..$ h2_est     : num 0.00219
  ..$ path_p_est : num [1:1500] 0.152 0.143 0.148 0.148 0.146 ...
  ..$ path_h2_est: num [1:1500] 0.00195 0.00207 0.00209 0.00224 0.00224 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.154
 $ :List of 9
  ..$ beta_est   : num [1:16307] -2.31e-04 -6.08e-06 -5.68e-06 -6.92e-06 2.76e-06 ...
  ..$ postp_est  : num [1:16307] 0.01007 0.0067 0.00671 0.00674 0.00666 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.0101
  ..$ h2_est     : num 0.00222
  ..$ path_p_est : num [1:1500] 0.207 0.2 0.202 0.2 0.198 ...
  ..$ path_h2_est: num [1:1500] 0.00223 0.00214 0.00217 0.00247 0.00245 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.207
 $ :List of 9
  ..$ beta_est   : num [1:16307] -3.70e-04 -1.08e-05 -1.14e-05 -1.42e-05 3.86e-06 ...
  ..$ postp_est  : num [1:16307] 0.028 0.0224 0.0224 0.0226 0.0224 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.027
  ..$ h2_est     : num 0.00235
  ..$ path_p_est : num [1:1500] 0.277 0.267 0.268 0.269 0.268 ...
  ..$ path_h2_est: num [1:1500] 0.00236 0.00232 0.00246 0.0024 0.00241 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.278
 $ :List of 9
  ..$ beta_est   : num [1:16307] -6.37e-04 -2.13e-05 -2.11e-05 -2.62e-05 1.06e-05 ...
  ..$ postp_est  : num [1:16307] 0.118 0.109 0.109 0.109 0.108 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.115
  ..$ h2_est     : num 0.00255
  ..$ path_p_est : num [1:1500] 0.375 0.378 0.379 0.378 0.38 ...
  ..$ path_h2_est: num [1:1500] 0.00219 0.00239 0.00226 0.00215 0.00216 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.373
 $ :List of 9
  ..$ beta_est   : num [1:16307] -7.04e-04 -2.59e-05 -2.48e-05 -3.00e-05 1.31e-05 ...
  ..$ postp_est  : num [1:16307] 0.364 0.357 0.356 0.357 0.356 ...
  ..$ sample_beta: num[1:16307, 0 ]
  ..$ p_est      : num 0.361
  ..$ h2_est     : num 0.00258
  ..$ path_p_est : num [1:1500] 0.5 0.496 0.496 0.507 0.496 ...
  ..$ path_h2_est: num [1:1500] 0.00198 0.00215 0.0021 0.0021 0.00211 ...
  ..$ h2_init    : num 0.00196
  ..$ p_init     : num 0.5

In [14]:
  # get estimates with indicies corresponding to pred genotypes
     write("Get estimates for beta_auto..", stderr())
     beta_auto <- sapply(multi_auto, function(auto){
          auto$beta_est})

In [16]:
str(beta_auto)
head(beta_auto[[1]])
length(beta_auto)

 num [1:16307, 1:30] -2.38e-04 -6.17e-06 -5.82e-06 -7.43e-06 2.78e-06 ...

[1] -0.0002376847

[1] 489210

In [18]:
dim(pred$genotypes)

[1] 381244  16307

In [20]:
  # perform matrix multiplication
     write("Performing mat mul..", stderr())
     pred_auto <- big_prodMat(
        genotypes,
        beta_auto,
        ncores = 1)

In [41]:

     # quality controls on chains
     write("Quality control om chains..", stderr())
     sc <- apply(pred_auto, 2, sd, na.rm = TRUE)
     keep <- abs(sc - median(sc)) < 3 * mad(sc)
     final_beta_auto <- rowMeans(beta_auto[, keep], na.rm = TRUE)

In [42]:
final_beta_auto

    [1] -2.177340e-04 -5.704885e-06 -5.488641e-06 -6.720491e-06  2.374155e-06
    [6] -1.178676e-05 -7.723547e-06 -4.838455e-05 -1.463803e-06  1.054120e-05
   [11] -6.031848e-07  1.871242e-04  1.124993e-05 -2.370763e-05  2.173058e-04
   [16] -3.876444e-06  1.652801e-05  1.113446e-05  9.554647e-06 -1.792740e-05
   [21]  3.177385e-05 -4.274642e-07  9.293229e-06  2.171322e-05 -2.852639e-05
   [26] -6.629152e-05 -1.155975e-04 -1.232165e-05  7.900129e-06 -1.903423e-05
   [31] -1.616393e-05 -4.179153e-04 -1.729425e-04 -1.723422e-04 -1.347899e-04
   [36] -4.694311e-04 -3.024152e-04 -1.654447e-04  1.374985e-05  2.873700e-07
   [41] -1.625602e-04  7.846467e-06 -4.102815e-06  6.011973e-06 -4.551583e-06
   [46]  1.313914e-03  4.729610e-06 -2.334440e-05  3.132471e-05  1.447960e-05
   [51]  1.236894e-04  1.901781e-05  2.041550e-05  1.257186e-04  6.522036e-06
   [56] -1.131780e-08  1.916309e-05  2.464375e-06  1.956434e-05  3.643991e-05
   [61]  3.211215e-05  2.794592e-05  2.054104e-05  8.413646e-06 -7.358024e-05
   [66] -7.512988e-06  2.754370e-05 -2.486205e-05  2.478843e-05  2.418480e-05
   [71] -1.451457e-05 -4.426968e-05 -1.234580e-07  1.322138e-05 -1.256651e-05
   [76] -1.318049e-05 -3.965148e-06 -4.968767e-06  1.294403e-06  9.088925e-07
   [81]  3.555432e-07 -3.178638e-06  3.408002e-05  7.471977e-06 -1.424410e-05
   [86] -1.203817e-05 -4.373923e-06  2.365097e-06 -9.483985e-06 -8.909134e-06
   [91] -8.927733e-07 -1.596290e-04  7.816466e-06 -1.848507e-05 -1.994619e-06
   [96]  1.485276e-05  1.749486e-05 -8.976321e-06  4.467570e-06 -1.044276e-05
  [101]  4.366044e-06 -1.590738e-05  1.928600e-05  1.500374e-05 -2.431770e-06
  [106] -1.091586e-04  1.144611e-05  1.164911e-05  2.039023e-05 -3.994265e-06
  [111]  9.698839e-06  4.347327e-06 -1.090225e-05 -2.457288e-06  9.771057e-06
  [116]  1.149270e-05  8.177963e-06 -2.028047e-05  6.502342e-06 -1.902980e-05
  [121]  8.941444e-06  1.950608e-05 -1.347915e-04 -1.370862e-04 -6.183925e-05
  [126] -1.367967e-04 -3.027108e-04  7.679912e-06 -1.248951e-04 -1.346545e-04
  [131] -9.826914e-05 -1.347087e-04  2.081352e-05 -1.309211e-04 -1.306774e-04
  [136] -1.342735e-04 -5.909826e-04  5.430597e-05  4.723992e-05 -8.462845e-05
  [141] -8.513788e-05 -8.566416e-05 -8.405943e-05 -2.335485e-05 -2.879629e-05
  [146] -2.297816e-05 -3.979976e-05 -1.867609e-05  6.215829e-05 -3.689134e-05
  [151]  5.341776e-05  5.581421e-05  1.527740e-04  3.484293e-05  3.633147e-05
  [156] -4.636263e-05 -8.788635e-06 -5.481881e-05 -4.946786e-05 -2.664207e-05
  [161] -6.647455e-05  2.096884e-06  1.266882e-05 -1.259620e-05 -3.893723e-05
  [166]  1.420111e-05  1.645984e-05  1.350051e-05 -9.032847e-05 -3.268762e-05
  [171] -8.775141e-05  2.178173e-04 -6.365180e-05 -7.157044e-05  3.019625e-05
  [176] -3.490384e-06 -2.464888e-05 -6.809527e-07 -1.478913e-06 -1.311387e-05
  [181]  2.418171e-05 -4.112013e-05 -3.565101e-06  3.247846e-05 -4.777516e-05
  [186] -4.835307e-06 -1.107387e-05 -1.134690e-04 -2.162730e-05  4.007599e-05
  [191] -4.178280e-05 -2.232883e-05  1.002280e-04  2.538211e-05 -6.121206e-05
  [196] -5.207398e-06  2.022384e-05  3.967682e-05 -1.726501e-05  3.962995e-05
  [201] -8.017751e-06  2.078015e-05  2.017477e-05  3.653509e-05  5.985301e-05
  [206] -3.626045e-06  1.890525e-04  2.224973e-05 -2.204961e-04  3.010770e-04
  [211]  2.765388e-05  2.044891e-04  4.268432e-04  3.941604e-04  2.237509e-04
  [216]  7.608681e-05  4.108654e-05  4.956209e-05  2.238674e-04  9.687159e-05
  [221]  8.025744e-05  8.567141e-05  3.867175e-05  8.673818e-05  9.000530e-05
  [226]  3.818780e-05 -1.414702e-05  2.105465e-05  5.508601e-05  6.581290e-05
  [231]  4.254578e-05  1.888244e-05 -1.764350e-05  6.833752e-05  5.984034e-05
  [236]  7.033949e-05  1.042632e-05 -5.681362e-05  4.473245e-05  2.850871e-05
  [241]  2.623627e-05 -1.325524e-05 -4.441713e-06 -1.817841e-05  3.675257e-06
  [246] -6.204143e-09 -4.230337e-06  4.191701e-06  5.846866e-07 -3.316684e-06
  [251]  3.013563e-05 -2.336716e-04  1.665802e-05  2.019117e-06  1.344766e-05
  [256] -1.237294e-04  1.407159e-05  9.582265e-06  1.567241e-05  3.028780e-05
  [261] -7.144659e-06  1.274977e-05  2.876572e-05 -5.299988e-06  1.162016e-05
  [266]  1.327077e-05  1.514489e-05  3.348109e-05  9.604234e-06 -4.645727e-04
  [271]  3.177123e-05  3.462425e-05  2.185053e-05  3.251743e-05  9.958055e-05
  [276]  3.876482e-05 -1.560219e-04  3.633743e-05 -2.718852e-04  7.733864e-06
  [281] -6.261669e-05  7.862428e-05  5.809872e-05 -1.971426e-05  4.864779e-05
  [286] -3.905087e-05  2.906210e-05  1.016435e-04  1.165819e-04 -2.979692e-05
  [291]  2.827273e-05 -2.167186e-05  4.170124e-05  1.088929e-04  3.982320e-05
  [296]  1.031408e-04  6.911910e-05 -4.880254e-06  9.592884e-05  4.211019e-05
  [301]  1.574869e-04  3.603215e-04  5.685978e-04  2.489966e-04  3.373519e-04
  [306]  4.530377e-05  5.102694e-04  9.278413e-05  3.982456e-04  9.820164e-05
  [311]  2.134987e-04  5.914123e-05  3.631896e-05 -1.742237e-04 -7.014204e-05
  [316]  2.280264e-04  9.271416e-06 -2.491827e-05  1.054185e-03 -3.980777e-05
  [321]  6.964477e-06  1.646895e-04 -3.120514e-05 -3.513328e-05 -3.117238e-05
  [326] -2.546919e-05 -3.895306e-05 -8.029834e-05 -5.306546e-05 -2.993997e-06
  [331] -1.398199e-05 -2.379766e-05 -2.737531e-05 -2.726491e-05 -2.720276e-05
  [336] -2.949109e-05 -2.831378e-05  1.486875e-05 -3.757929e-05 -5.317590e-05
  [341] -5.319260e-05 -3.813147e-05 -2.225630e-05 -2.137787e-05 -2.112785e-05
  [346] -3.442928e-06 -1.212675e-05  5.201966e-05 -1.561129e-04  4.590276e-05
  [351] -2.967302e-05 -4.853868e-05 -4.465528e-05 -6.231621e-05  1.378775e-04
  [356]  3.201326e-04  6.619272e-05 -1.062926e-04  8.560071e-05  8.227385e-05
  [361]  1.815152e-04  2.164103e-04  3.640366e-05  1.969332e-04  1.399257e-04
  [366]  1.011409e-04  2.660656e-04  2.159523e-05  2.750831e-04  2.942168e-04
  [371]  2.183657e-04  8.590901e-04  9.727038e-05  9.512148e-05  8.285220e-04
  [376]  4.440208e-05  4.285009e-05  3.147397e-05 -1.134266e-04  2.580652e-04
  [381] -1.221988e-04  2.524387e-04  8.592923e-04  4.379763e-05  8.464492e-05
  [386]  1.061320e-05  4.401923e-05  8.394260e-04  8.261041e-04 -1.891487e-04
  [391] -6.953863e-05 -6.058642e-06 -4.995862e-06 -4.994294e-06 -5.974259e-05
  [396] -7.476612e-05 -9.801768e-05 -7.443158e-05 -2.396899e-04 -5.999363e-05
  [401] -6.854232e-06 -1.157271e-04 -2.456391e-04  3.180389e-05 -2.386151e-05
  [406]  1.163048e-05 -1.510605e-05  1.851309e-05 -2.783557e-05 -3.732324e-05
  [411] -3.330855e-05 -2.259517e-05 -3.222151e-05  6.930228e-05  3.119914e-05
  [416] -2.769800e-05  6.392569e-05  3.610017e-06 -2.557901e-05  2.294362e-05
  [421]  6.278450e-05  5.193300e-06 -1.137647e-04 -7.420047e-06  1.622489e-05
  [426]  6.306036e-06  1.069142e-04  7.921050e-06 -3.386570e-05  3.454755e-06
  [431]  1.658303e-05  1.123071e-05  1.022432e-05  1.139916e-04 -1.235344e-04
  [436]  1.069480e-05  1.177845e-05 -5.561375e-05 -6.316134e-05  3.994889e-05
  [441]  4.234260e-05  4.242089e-06 -4.492055e-05  5.429365e-05 -4.745750e-05
  [446] -3.855765e-05 -3.232075e-05  4.107513e-06  1.055425e-04  1.040844e-04
  [451] -4.852672e-05  6.291669e-05  7.519253e-05  2.168177e-04  1.060413e-05
  [456] -1.354509e-04  2.840495e-05 -5.262363e-06  1.815047e-04 -6.789342e-06
  [461]  1.550651e-04  1.789369e-04  9.141070e-07  1.733821e-04 -4.369095e-05
  [466]  1.757309e-04 -1.349870e-06  2.222564e-04  1.957850e-05  2.013408e-05
  [471]  1.945681e-05 -1.506461e-04  5.153124e-04  1.741399e-04  6.737753e-05
  [476]  6.521338e-05  6.448667e-05  4.322240e-06 -1.619588e-04  5.769376e-05
  [481]  5.602766e-05  5.787399e-05  5.787514e-05  5.737682e-05  5.797328e-05
  [486]  1.219460e-05  3.997454e-05  7.884453e-05  6.779544e-06  8.426168e-06
  [491]  4.657923e-05  2.287939e-05  2.877731e-05 -5.486847e-06  3.021658e-05
  [496] -2.235389e-04  2.589863e-06  2.458119e-06  1.610640e-05  1.861080e-05
  [501] -1.506591e-04 -1.765178e-04  4.135145e-05  1.893658e-05 -1.613886e-06
  [506] -1.490600e-04 -3.953448e-07  2.559839e-06  2.994357e-06  2.136635e-05
  [511]  3.990577e-06  5.190117e-06 -1.526480e-04  8.161391e-06  2.009717e-05
  [516] -1.074420e-05 -9.354075e-06 -2.848702e-05 -5.061824e-05 -1.441784e-04
  [521]  5.019798e-06 -2.087386e-05  5.944307e-05  2.897182e-05  3.079496e-05
  [526] -2.249967e-04 -9.358443e-06  2.152809e-04 -2.106316e-04 -8.628690e-05
  [531] -1.143594e-05  1.236088e-04 -1.006882e-04 -2.425257e-04 -6.903047e-06
  [536] -7.713737e-05 -7.873537e-05 -1.452143e-04 -1.245836e-05  9.652847e-06
  [541] -1.846217e-04 -3.050958e-05 -3.089607e-05  2.014621e-04 -4.505408e-05
  [546] -4.134515e-05 -5.972799e-06 -5.931750e-05 -4.439711e-05 -6.357689e-06
  [551]  1.596700e-05 -4.270275e-05 -7.231242e-05 -1.735860e-04 -9.354706e-05
  [556]  6.735935e-05 -1.689495e-04 -6.493282e-06  3.310606e-04 -1.273477e-04
  [561] -1.458752e-04 -2.791122e-05  9.611171e-05  3.601819e-05 -2.305737e-05
  [566] -6.227874e-06 -6.184423e-05 -5.209685e-05 -6.296992e-05 -1.857115e-05
  [571] -6.313381e-05  6.510117e-05  8.568706e-06  7.288744e-05  1.984899e-05
  [576]  1.045600e-05  1.147439e-04  1.344251e-04  1.433726e-04 -9.827200e-06
  [581]  1.475947e-04 -2.219918e-05  1.594720e-05  2.276971e-05  3.323347e-05
  [586] -5.108419e-05  5.434821e-04 -5.201886e-05  2.029911e-05 -5.369535e-05
  [591]  5.421537e-04  1.613742e-04  3.398461e-05 -1.495258e-05 -2.027972e-06
  [596]  1.571194e-04 -1.352454e-05  5.825048e-05  1.621697e-04 -1.557553e-05
  [601] -9.810851e-05 -1.011230e-04 -1.357760e-05  5.147465e-05  6.484765e-05
  [606]  4.805594e-05 -9.027836e-06 -1.567187e-05 -1.278654e-05 -4.150755e-05
  [611] -1.290116e-05  4.505288e-05 -2.935900e-05 -2.612007e-05 -3.090099e-05
  [616]  2.160917e-04  7.271252e-07 -4.041541e-06 -8.648879e-05 -7.851686e-05
  [621] -1.684915e-05 -9.227830e-05 -9.265682e-05  5.140168e-05 -1.719873e-05
  [626]  4.608910e-05  1.551092e-04  2.896561e-05  2.340001e-05  1.992311e-04
  [631] -1.466319e-05  1.486931e-05 -8.508699e-05  2.474257e-04  2.101043e-05
  [636]  7.700297e-06 -4.209426e-05  3.594384e-05  1.054511e-04 -2.983937e-05
  [641] -2.490832e-05  2.839298e-05  2.559162e-05 -1.506738e-04  1.673431e-05
  [646]  3.054910e-05  3.032902e-05  2.480238e-06  6.164240e-06 -4.440688e-06
  [651]  2.360811e-05  1.081361e-04  2.490680e-05 -7.211425e-05 -6.749426e-05
  [656] -1.325878e-04  1.805009e-05  2.175797e-05  2.168662e-05  2.083882e-05
  [661]  1.365254e-04  8.417759e-06 -5.222436e-04 -2.518940e-05 -3.807699e-05
  [666] -4.808950e-05 -4.708524e-05  2.582712e-05  2.294757e-04  2.658607e-05
  [671] -7.585128e-05 -2.285515e-05 -7.150976e-05  1.644638e-04 -1.101341e-05
  [676]  3.533117e-05  2.296854e-04  2.394155e-04  4.006219e-05 -2.160986e-06
  [681]  4.838840e-05  7.115018e-07  4.608596e-05  1.964057e-04 -6.732625e-05
  [686] -6.497267e-05  1.207413e-05  5.429243e-06 -5.871999e-05 -3.200731e-05
  [691]  1.528471e-04 -4.694302e-05  1.369341e-04 -3.633165e-05  1.386558e-04
  [696] -6.767219e-05  1.340549e-04  3.305990e-05  1.093479e-04  3.267637e-05
  [701] -5.778583e-05 -6.682426e-05  1.326662e-05  1.108561e-05  2.149723e-05
  [706]  6.371158e-06  9.478967e-06  6.801904e-06  7.310247e-06  4.598796e-06
  [711]  9.662835e-06  2.076547e-05  4.891564e-06 -7.737832e-06 -6.935315e-05
  [716] -9.486702e-04 -7.896766e-04 -3.813344e-05 -8.768279e-05 -4.074928e-05
  [721] -3.990750e-05 -5.039836e-04 -2.505550e-04 -1.164314e-04 -1.260346e-04
  [726] -4.240268e-05 -4.287790e-05 -4.450461e-05 -4.107534e-05 -1.150478e-04
  [731] -5.049702e-05 -1.367976e-04 -9.418526e-05 -2.944479e-05 -7.145530e-05
  [736]  2.141038e-05 -2.976782e-04 -4.847862e-04  1.835096e-04  1.470207e-05
  [741] -2.052672e-05 -5.459344e-05 -3.611362e-04 -1.579479e-04 -3.973939e-05
  [746] -4.350498e-03 -2.045106e-04 -4.171107e-03  6.940192e-04 -2.978668e-03
  [751]  1.461523e-04 -2.996086e-05  4.556410e-05 -1.715462e-05 -2.863034e-05
  [756] -2.568130e-05 -2.300444e-05 -7.508130e-05 -8.644700e-05 -2.631129e-04
  [761] -9.824892e-05 -4.106751e-04 -9.689031e-05 -9.705420e-05 -1.020544e-04
  [766] -1.026816e-04 -7.861277e-05 -4.642357e-05 -6.008300e-05 -5.710485e-05
  [771] -8.126549e-05 -6.422247e-05 -9.209507e-05 -8.669990e-05 -3.963981e-05
  [776]  7.714016e-05 -1.182320e-04  2.707180e-05 -4.268367e-05 -3.141009e-05
  [781]  2.915756e-05  2.539807e-05  2.466092e-05  1.524491e-05 -5.347413e-05
  [786] -3.498456e-05 -4.441540e-05  1.772804e-05 -4.126644e-05 -7.005173e-05
  [791]  1.114206e-05 -3.589073e-05 -3.642206e-05 -2.307947e-05  3.510167e-05
  [796]  3.357636e-05 -6.908260e-05 -8.463898e-05 -6.515499e-05 -6.654746e-05
  [801] -6.467960e-05 -6.708380e-05 -6.706754e-05 -5.938356e-05 -5.673619e-05
  [806] -5.660366e-05 -5.534991e-05 -5.506732e-05 -7.460862e-05 -3.865650e-05
  [811] -6.359478e-05 -5.284951e-05 -3.746575e-05 -3.830114e-05 -3.501515e-05
  [816] -3.495512e-05 -3.815123e-05 -3.490778e-05 -3.601704e-05 -1.043040e-04
  [821] -6.336613e-05 -1.009688e-04 -1.026411e-04 -1.280255e-05 -1.024064e-04
  [826] -1.191667e-05 -6.901312e-05 -4.383228e-05 -4.248549e-05  1.737004e-05
  [831] -4.240386e-05  4.517552e-05  5.464214e-05 -3.473357e-05 -2.612460e-05
  [836] -2.651564e-06 -1.199056e-05  2.907023e-05  1.811428e-05  5.795837e-06
  [841]  1.764490e-05  1.224102e-05  9.259192e-06 -4.908850e-06  1.600504e-04
  [846] -1.115156e-04  6.427678e-06 -1.602691e-05 -8.516127e-06 -8.420794e-06
  [851] -1.262210e-05 -1.411140e-05  5.466967e-05 -3.022698e-06  3.191864e-05
  [856] -1.440885e-06 -5.594838e-05 -6.019363e-05 -3.327652e-05 -3.591254e-05
  [861] -2.359581e-06 -6.278356e-05  2.201075e-06 -1.996297e-06 -9.144768e-06
  [866] -6.204973e-06 -3.696051e-06 -2.625190e-06  6.186486e-06 -5.728883e-06
  [871] -8.106784e-06 -9.585180e-06 -5.454636e-06  1.038673e-05 -5.755641e-06
  [876] -7.702701e-06 -9.967584e-06  1.198977e-05 -6.842974e-06 -9.493594e-06
  [881] -7.143261e-06 -1.251773e-05 -1.428205e-05 -2.768613e-05 -2.592838e-05
  [886] -3.287074e-05 -9.857524e-06  4.170376e-04  5.223126e-05 -1.728194e-05
  [891]  8.910088e-08  5.398643e-05  5.551366e-05  4.892081e-06  3.390920e-06
  [896]  1.571288e-05  1.476146e-05  2.326558e-07  1.650683e-05 -1.565934e-05
  [901]  1.269779e-04 -6.444703e-05 -3.974795e-05 -3.791349e-05 -3.496913e-05
  [906] -4.009140e-05 -3.850205e-05 -2.615994e-05 -2.295910e-05 -1.465783e-05
  [911] -5.722905e-05 -1.280799e-05  3.511886e-06 -9.179549e-06 -4.791710e-06
  [916]  1.980682e-05 -3.907312e-06  9.459001e-06  7.601922e-06  2.343839e-05
  [921]  6.789658e-06 -2.771225e-06  5.064153e-05  6.497617e-05  9.244956e-05
  [926]  4.457361e-05  2.918960e-05  7.017853e-05  3.450937e-05  3.673942e-05
  [931] -5.837943e-05 -6.901021e-05  3.235640e-05  4.643393e-05  6.066949e-05
  [936] -2.488864e-05  9.938720e-05  9.305184e-05 -1.663213e-05  1.009621e-04
  [941]  1.018660e-04  7.822594e-05  1.087641e-04 -4.196357e-06  1.346994e-04
  [946]  1.350503e-04  7.414429e-05  4.162300e-05  4.895931e-05  1.252918e-04
  [951]  1.220051e-04  7.380130e-05  7.347150e-04  6.443359e-05  6.469576e-05
  [956]  6.349616e-05  6.470855e-05  5.560355e-05  6.318466e-05  7.850570e-05
  [961]  5.357766e-05  2.255242e-05  9.911490e-05  1.622892e-04  6.093736e-05
  [966]  7.098858e-05  1.075788e-04  5.046800e-05  7.281365e-05  1.083631e-04
  [971]  1.055373e-04  3.611341e-05  1.708225e-04  1.689650e-04  1.694188e-04
  [976]  1.910365e-04  7.407913e-06 -3.505190e-05  1.884604e-05  5.923746e-05
  [981] -1.296162e-05 -1.420878e-05  2.116591e-05  7.049949e-05 -1.686103e-05
  [986]  6.985736e-05  5.324009e-05  7.633148e-06  8.004437e-07 -6.119627e-05
  [991] -1.976077e-05 -2.180723e-05  9.249617e-05 -6.695210e-05  3.247917e-05
  [996] -3.518383e-05  1.653807e-04  1.523679e-05  1.959175e-05  1.645311e-05
 [1001]  3.511936e-05  1.991134e-05  3.489760e-05  3.366818e-05  2.784437e-05
 [1006]  3.279625e-05  1.039897e-05  5.018541e-05 -1.425570e-05  2.385446e-05
 [1011]  2.067477e-05  1.925137e-05 -3.479222e-05  2.284594e-05  3.747840e-06
 [1016]  1.820098e-05  1.593130e-05  4.916921e-06  2.432600e-05  2.730271e-05
 [1021] -5.653624e-05  2.385380e-05 -2.502246e-05 -1.517388e-05 -3.913368e-05
 [1026] -1.695613e-04 -6.412373e-06 -6.989644e-06 -1.024270e-05 -1.628615e-04
 [1031]  3.244629e-06 -2.509749e-06 -1.648585e-06  4.708788e-06 -7.056700e-04
 [1036]  1.868368e-05 -1.272913e-05 -1.377914e-05 -5.616906e-06 -1.589630e-07
 [1041] -3.627891e-07  1.761117e-05 -9.115452e-06 -2.185477e-05  2.196070e-04
 [1046] -2.697232e-05  6.345270e-06  2.704795e-06 -1.732964e-06  2.105788e-05
 [1051] -1.107193e-05  2.014090e-05 -1.069133e-05 -7.162075e-06  6.819928e-07
 [1056] -1.170246e-03 -3.434821e-06 -2.283409e-05  2.517481e-05  2.310385e-05
 [1061]  2.130876e-05  2.050207e-05 -8.837017e-06  1.483108e-05 -1.260130e-05
 [1066] -6.576691e-06 -2.740645e-05 -1.713130e-05 -4.244875e-05 -3.612579e-05
 [1071]  3.642566e-05 -3.723143e-05  5.748732e-05 -4.358711e-05 -5.476025e-05
 [1076] -6.182115e-05  1.441597e-05 -4.338255e-06 -6.559304e-05  7.047686e-05
 [1081]  1.052981e-04 -2.447380e-04 -5.673161e-06 -5.363583e-06 -7.196240e-06
 [1086] -8.482549e-06 -8.144826e-06 -5.402737e-06 -9.566365e-06 -6.691852e-06
 [1091] -6.273802e-06  9.421922e-05  1.162151e-04 -6.440272e-05  1.287348e-04
 [1096]  1.411095e-05  1.917087e-05  1.856945e-05  2.271739e-04  1.765993e-05
 [1101]  1.606509e-05 -2.701331e-04  2.553957e-05  1.320457e-04  2.308743e-04
 [1106]  4.245960e-05  1.112324e-04  3.610741e-05  4.719695e-05 -2.675268e-05
 [1111]  1.072802e-05 -6.982430e-06 -3.133675e-06 -2.811063e-06 -1.692911e-04
 [1116] -5.080341e-05 -3.527271e-04  4.234444e-06  5.840008e-05  2.175438e-05
 [1121] -1.164054e-05  2.437574e-06 -9.835348e-05  1.178135e-05 -7.520791e-07
 [1126]  1.181119e-05  1.236598e-05 -8.695452e-05  4.872501e-06 -1.054351e-04
 [1131]  3.308109e-05 -1.680406e-06 -5.126232e-05 -6.408819e-06 -4.916893e-06
 [1136] -7.729979e-06  1.212822e-07 -1.596023e-05  5.496275e-06  6.219063e-06
 [1141] -6.886781e-06 -3.202393e-06 -1.667881e-07 -1.934181e-05 -1.741407e-05
 [1146] -6.879312e-06  9.062581e-05  5.839176e-05 -5.001622e-05 -5.772605e-05
 [1151]  4.501652e-05  2.474564e-04  3.668740e-06 -4.394219e-05 -3.099895e-05
 [1156] -5.568120e-05 -5.635802e-05  2.012231e-05  1.363521e-05  1.798395e-05
 [1161]  2.468847e-05 -8.556409e-06  3.316966e-05  2.424429e-05  2.965919e-04
 [1166]  6.126173e-05 -1.974271e-05  9.818907e-06 -8.480280e-06  2.960889e-05
 [1171]  3.022312e-05  5.039635e-05 -1.462453e-05  2.976739e-05  3.482150e-05
 [1176] -1.065906e-04  5.996602e-06 -9.524024e-06  1.607660e-05 -4.405698e-05
 [1181]  1.922245e-04 -1.992593e-05 -3.447691e-05  3.223495e-05  9.230313e-06
 [1186]  3.309642e-05  4.539945e-05  2.476048e-05  6.985009e-05  2.587649e-04
 [1191]  1.642028e-03  2.739530e-04  3.060005e-04  2.245783e-04  2.973744e-04
 [1196]  3.315650e-05  2.675248e-05  3.197852e-05  3.429652e-06 -6.969014e-05
 [1201] -8.112699e-05 -4.235793e-05  8.864727e-05  6.322393e-05  1.256675e-04
 [1206]  1.255627e-04  1.223992e-04  9.830410e-05  1.347461e-04  5.388768e-05
 [1211]  4.976634e-05  6.462717e-05  6.694061e-05  7.816511e-05  8.314731e-05
 [1216]  1.625855e-06  1.313673e-04  1.241187e-04  1.145290e-04 -1.119651e-04
 [1221] -2.993057e-05 -3.680923e-04  3.062495e-05 -1.418159e-05  3.505418e-05
 [1226]  3.805728e-05 -1.428036e-04 -1.469359e-04  1.085384e-04  4.259163e-05
 [1231]  1.384807e-04  3.112148e-05 -2.517566e-05 -7.318131e-05 -1.261816e-04
 [1236]  3.813737e-04  5.148209e-05 -2.053926e-05 -4.507466e-05 -2.928678e-05
 [1241] -8.136667e-05  4.042332e-05 -1.268453e-05 -6.530376e-05 -5.204610e-05
 [1246] -5.120132e-06  4.716845e-04 -6.845159e-05 -2.531074e-06 -5.861702e-05
 [1251] -5.295725e-05 -6.600805e-05  4.770499e-04 -2.825820e-05  3.209806e-04
 [1256]  4.176591e-04 -5.602721e-06  2.163235e-05  3.300206e-04 -7.385943e-05
 [1261]  3.998985e-04 -2.784791e-06 -5.474205e-06 -6.440893e-05 -3.525727e-06
 [1266] -4.514088e-05 -2.405106e-05  7.582039e-05 -2.186907e-05  1.753062e-04
 [1271] -2.449770e-05 -1.339708e-05 -8.862559e-06  4.036891e-05 -3.959614e-05
 [1276] -7.747693e-05 -8.141758e-05 -3.168895e-05 -4.011729e-05  4.770077e-05

In [37]:
any(is.na(pred_auto))
sum(is.na(pred_auto))
NA_rows <- rowSums(is.na(pred_auto)) > 0 

sum(NA_rows)/nrow(pred_auto)

[1] TRUE

[1] 291150

[1] 0.02545614

In [43]:
   # get final predicton
     write("Getting final prediction..", stderr())
     final_pred_auto <- big_prodVec(
       genotypes,
       final_beta_auto,
       ncores = 1)

     final_pred <- final_pred_auto

In [3]:
# load data required for setting up LD-matrix
ld_data <- load_bigsnp_from_bed(args$bed)

# load summary statistics
sumstats <- read_hail_sumstat(args$gwas)

# match summary stats and LD data
info_snp <- snp_match(sumstats, ld_data$map, join_by_pos = TRUE, strand_flip = FALSE)

ERROR: Error in trait %in% c("binary", "cts"): argument "trait" is missing, with no default

In [ ]:
#QC summary statistics based on LD reference
qc <- qc_binary_sumstat(ld_data$G, info_snp, NCORES)
well_behaved_snps <- (!qc$is_bad)
df_beta <- info_snp[well_behaved_snps, ]
df_beta$marker <- get_ldpred_marker(df_beta)

In [ ]:
snp1 <- get_ld_matrix(df_beta, chrs = 1:22)

In [6]:
snp <- snp1
gwas <- df_beta #df_beta[df_beta$chr %in% paste0("chr",1:2),]
gwas <- gwas[gwas$marker %in% snp$map$marker,]

#gwas <- gwas[order(as.numeric(gsub('chr','',gwas$chr))),] # works!
indicies <- na.omit(match(snp$map$marker, gwas$marker))
gwas <- gwas[indicies,]


nrow(gwas); length(snp$map$marker); length(snp$ld)



# check that LD and GWAS data was generated simultanously
stopifnot(length(snp$ld) == nrow(gwas))
stopifnot(sum(gwas$marker == snp$map$marker) / nrow(gwas) == 1)

[1] 1121294

[1] 1121294

[1] 1121294

In [7]:
# perform LD regressio

chi2 <- (gwas$beta / gwas$beta_se)^2
ldsc <- with(gwas,
            snp_ldsc(
                snp$ld,
                length(snp$ld),
                chi2 = chi2,
                sample_size = gwas$n_eff,
                blocks = NULL)
               )

ldsc_h2_est <- ldsc[["h2"]]
ldsc_int_est <- ldsc[['int']]

In [5]:
# Load new data for prediction
pred <- load_bigsnp_from_bed(args$pred)
genotypes <- pred$G

Warning message in load_bigsnp_from_bed(args$pred):
"NAs introduced by coercion"

ERROR: Error: 'infos.chr' should have only positive values.

In [6]:
bed <- args$pred

In [22]:
if (!file.exists.ext(bed, '.bk')) snp_readBed(bed)
basename <- tools::file_path_sans_ext(bed)
rds <- paste0(basename,'.rds')

# if the bk file exists but not the rds, then re-read SNP
if (!file.exists(rds)) {
       write("rds file not available. Retrying snp_readBED", stderr())
       bk <- paste0(basename, ".bk")
       unlink(bk)
       snp_readBed(bed)
}

# attach to the file to current session
big_snp <- snp_attach(rds)

# extract the SNP information from the genotype
autosomes <- paste0('chr',1:22)
map <- big_snp$map[-3]
names(map) <- c("chr", "rsid", "pos", "a1", "a0")

odd_contig <- unique(map$chr[!map$chr %in% autosomes])
odd_contig <- paste0(odd_contig, collapse = '|')
warning(paste0("non standard chromosome contig excluded: ", odd_contig))

# remove non-autosomes (e.g. chr8_KI270821v1_alt)
map <- map[map$chr %in% autosomes,]
big_snp$map <- big_snp$map[big_snp$map$chr %in% autosomes,]

G <- big_snp$genotypes

Warning message in eval(expr, envir, enclos):
"non standard chromosome contig excluded:chr8_KI270821v1_alt"

In [12]:
unique(map$chr)

[1] "chr8"

In [13]:
# Rename the data structures
CHR <- as.numeric(gsub('chr','',map$chr))
POS <- map$pos

# get the CM information from hapmap SNPs
POS2 <- snp_as_genetic_position(CHR, POS, mapdir = "data/prs/1000-genomes-genetic-maps",genetic_map = 'hapmap')

In [ ]:
# ldpred2 inf model
#beta_inf <- snp_ldpred2_inf(snp$corr, gwas, ldsc_h2_est)

In [9]:
#final_pred_inf <- predict_prs(
#       obj = pred,
#       gwas = gwas,
#       effects = beta_inf,
#       ncores = 1,
#       ind_row = 1:100)

In [18]:
head(gwas)
head(pred$map)

  chr  pos    a0 a1 rsid.ss         n_eff  beta_se  p       beta       INFO
1 chr1 817341 A  G  chr1:817341_A_G 381192 0.011795 0.18683 -0.0155700 NA
2 chr1 818802 A  G  chr1:818802_A_G 381192 0.012571 0.22785 -0.0151590 NA
3 chr1 818954 T  C  chr1:818954_T_C 381192 0.012564 0.22805 -0.0151440 NA
4 chr1 825532 C  T  chr1:825532_C_T 381192 0.011706 0.25218 -0.0134050 NA
5 chr1 833068 G  A  chr1:833068_G_A 381192 0.013745 0.84022  0.0027711 NA
7 chr1 843942 A  G  chr1:843942_A_G 381192 0.012648 0.35109  0.0117940 NA
  MAF     _NUM_ID_.ss rsid            _NUM_ID_ marker
1 0.16040 1           chr1:817341:A:G 1        chr1:817341:A:G
2 0.13027 2           chr1:818802:A:G 2        chr1:818802:A:G
3 0.13057 3           chr1:818954:T:C 3        chr1:818954:T:C
4 0.16099 4           chr1:825532:C:T 4        chr1:825532:C:T
5 0.10605 5           chr1:833068:G:A 5        chr1:833068:G:A
7 0.12845 7           chr1:843942:A:G 7        chr1:843942:A:G

  chr   rsid               pos      a1 a0
1 chr22 chr22:15473564:G:A 15473564 A  G
2 chr22 chr22:16390411:A:G 16390411 G  A
3 chr22 chr22:16406147:G:A 16406147 A  G
4 chr22 chr22:16412132:A:G 16412132 G  A
5 chr22 rs5747620          16551808 C  T
6 chr22 chr22:16573137:G:A 16573137 A  G

In [38]:

#res <- match_map(gwas, pred$map, pred$bigsnp)

ori = pred$map
ref = gwas
bigsnp = pred$bigsnp

#match_map <- function(ori, ref, bigsnp){
    
    if (! "marker" %in% colnames(ori)) ori$marker <- get_ldpred_marker(ori)
    if (! "marker" %in% colnames(ref)) ref$marker <- get_ldpred_marker(ref)
    
    # subset ref to things contained in ori
    ref <- ref[ref$marker %in% ori$marker,]
    #ori <- ori[ori$marker %in% ref$marker,]
    
    # match gwas betas with bed map
    indicies <- na.omit(match(ref$marker, ori$marker))
    ori <- ori[indicies,]
    
    nrow(ori); nrow(ref)
    
    # check that all positions match
    stopifnot(all(ori$pos == ref$pos))
    
    
#}

[1] 16185

[1] 1121294

Warning message in ori$pos == ref$pos:
"longer object length is not a multiple of shorter object length"

ERROR: Error: all(ori$pos == ref$pos) is not TRUE

In [ ]:
#if (! "marker" %in% colnames(ori)) ori <- get_ldpred_marker(ori)
#if (! "marker" %in% colnames(ref)) ref <- get_ldpred_marker(ref)

A Sparse Filebacked Big Matrix with 1121294 rows and 1121294 columns.

In [ ]:
# ldpred2 auto model on full gwas
multi_auto <- snp_ldpred2_auto(
   snp$corr,
   gwas,
   h2_init = ldsc_h2_est,
   vec_p_init = 0.5, #seq_log(1e-4, 0.5, 30),
   ncores = 1)

In [ ]:
gwas$effects <- multi_auto
matched <- match_bigsnp_with_gwas(pred, gwas)

sid <- matched$sid
genotypes <- matched$genotype
map <- matched$map

## what is beta_auto??

In [ ]:
# run first estimates
beta_auto <- sapply(multi_auto, function(auto) auto$beta_est)
pred_auto <- big_prodMat(
    genotypes,
    beta_auto,
    ncores = 1)

In [ ]:
# quality controls on chains
sc <- apply(pred_auto, 2, sd)
keep <- abs(sc - median(sc)) < 3 * mad(sc)
final_beta_auto <- rowMeans(beta_auto[, keep])

In [ ]:
final_pred_auto <- big_prodVec(
    genotypes, final_beta_auto,
    ncores = 1)

In [ ]:
# ldpred2 auto model
  #multi_auto <- snp_ldpred2_auto(
  #   snp$corr,
  #   gwas,
  #   h2_init = ldsc_h2_est,
  #   vec_p_init = seq_log(1e-4, 0.5, 30),
  #   ncores = NCORES)

  # run first estimates
  #beta_auto <- sapply(multi_auto, function(auto) auto$beta_est)
  #pred_auto <- big_prodMat(
  #    genotypes,
  #    beta_auto,
  #    ind.col = gwas[["_NUM_ID_"]],
  #    ncores = NCORES)

  # quality controls on chains
  #sc <- apply(pred_auto, 2, sd)
  #keep <- abs(sc - median(sc)) < 3 * mad(sc)
  #final_beta_auto <- rowMeans(beta_auto[, keep])

  # run final estimates

  #final_pred_auto <- big_prodVec(
  #    genotypes, final_beta_auto,
  #    ind.col = gwas[["_NUM_ID_"]],
  #    ncores = NCORES)

  # save parameters
  model <- data.table(
     n_samples = unique(gwas$n),
     n_snps = nrow(gwas),
     ldsc_h2_est = ldsc_h2_est,
     ldsc_int_est = ldsc_int_est,
     inflation = calc_inflation(gwas$P)
     )

  # save results
  PGS <- data.table(
    sid = final_pred_inf$sid,
    prs = final_pred_inf$prs
    )

  write(paste0(args$pred, ".. done! Writing to ", args$out_prefix, ".txt.gz"), stdout())
  fwrite(PGS, file = paste0(args$out_prefix,".txt.gz"), sep = '\t')
  fwrite(model, file = paste0(args$out_prefix,".model"), sep = '\t')

In [ ]:
calc_ld_matrix2 <- function(info_snp, chrs = 1:22, sfbm_file = tempfile(), ld_dir = "data/prs/hapmap/ld/matrix"){

    chrs <- paste0("chr",chrs)
    first_chr <- chrs[1]
    for (chr in chrs) {
        
        # measure time
        start_time <- Sys.time()
        msg = paste0("Retriving LD for chrom ",chr)
        message(msg,"\r",appendLF=FALSE)
        
        # paths to ld-matrix
        path_rds <- file.path(ld_dir, paste0("ld_matrix_",chr,".rds"))
        path_map <- file.path(ld_dir, paste0("ld_matrix_",chr,".txt.gz"))
        
        # retrieve correlation matrix
        corr0 <- readRDS(path_rds)
        map <- fread(path_map)
        map$index <- 1:nrow(map)
        map$marker <- get_ldpred_marker(map)
        
        # subset ld-matrix
        i_index <- na.omit(match(info_snp$marker, map$marker)) 
        matched_map <- map[i_index,]
        j_index <- matched_map$index
        corr0 <- corr0[j_index, j_index]
    
        if (chr == first_chr) {
            ld <- Matrix::colSums(corr0^2)
            corr <- as_SFBM(corr0, sfbm_file)
            outmap <- matched_map
        } else {
            ld <- c(ld, Matrix::colSums(corr0^2))
            corr$add_columns(corr0, nrow(corr))
            outmap <- rbind(outmap, matched_map)
        }
        
        flush.console()
        end_time <- Sys.time()
        elapsed <- round(end_time - start_time,1)
        message(msg," [",elapsed,"s]","\r")
        
    }
    return(list(ld = ld, corr = corr, map = outmap))
}

In [ ]:
match_bigsnp_with_gwas <- function(obj, gwas, ind_row = NULL, ncores = 1){

    # assume that effect index correspond to gwas index
    stopifnot(length(effects) == nrow(gwas))

    # add indexes used for later subsetting
    bed_map <- obj$map
    bed_map$marker <- get_ldpred_marker(bed_map)
    bed_map$index <- 1:nrow(bed_map)
    gwas$marker <- get_ldpred_marker(gwas)
    gwas$index <- 1:nrow(gwas)

    # check that all markers are contained in one another
    stopifnot(sum(gwas$marker %in% bed_map$marker) == sum(bed_map$marker %in% gwas$marker))

    # remove any bed markers not in gwas (assuming
    # that the GWAS has already been qced before)
    bed_map <- bed_map[bed_map$marker %in% gwas$marker,]

    # match gwas betas with bed map
    indicies <- match(bed_map$marker, gwas$marker)
    gwas_matched <- gwas[indicies,]
    gwas_matched <- gwas_matched[!(rowSums(is.na(gwas_matched)) == ncol(gwas_matched)),]

    # check that all positions match
    stopifnot(all(gwas_matched$pos == bed_map$pos))

    # get subset of effects corresponding to bed_map
    matched_effects <- effects[indicies]

    # subset bigsnp to get the right genotypes
    samples <- obj$bigsnp$fam$sample.ID
    if (is.null(ind_row)) ind_row <- 1:length(samples)
    subsetted_bigsnp <- snp_subset(obj$bigsnp, ind.col = bed_map$index, ind.row = ind_row)
    subsetted_bigsnp <- snp_attach(subsetted_bigsnp)
    genotypes <- subsetted_bigsnp$genotypes
    stopifnot(dim(genotypes)[2] == nrow(gwas_matched))

    return(list(G = genotypes, map = gwas_matched, sid =  samples[ind_row]))
}