In [1]:
# extract phenotypes
library(data.table)
library(tidyverse)
library(ggrepel)
library(lubridate)
setwd('/well/lindgren/UKBIOBANK/flassen/projects/KO/wes_ko_ukbb/')

-- Attaching packages ----------------------------------------------------------------------------------------------------------------------------- tidyverse 1.3.1 --

v ggplot2 3.3.5     v purrr   0.3.4
v tibble  3.1.4     v dplyr   1.0.7
v tidyr   1.1.3     v stringr 1.4.0
v readr   1.4.0     v forcats 0.5.1

-- Conflicts -------------------------------------------------------------------------------------------------------------------------------- tidyverse_conflicts() --
x dplyr::between()   masks data.table::between()
x dplyr::filter()    masks stats::filter()
x dplyr::first()     masks data.table::first()
x dplyr::lag()       masks stats::lag()
x dplyr::last()      masks data.table::last()
x purrr::transpose() masks data.table::transpose()


Attaching package: 'lubridate'


The following objects are masked from 'package:data.table':

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year


The following objects are masked from 'package:base':

    date, intersect, setdiff, union

In [2]:
devtools::load_all('utils/modules/R/ukbtools')

i Loading ukbtools

In [3]:
# phenotype tables
imp <- list(
    phenotypes = "/well/lindgren/UKBIOBANK_DATA_LINDGREN/Phenotype_data/October2017/ukb10844.csv", # october 2018 release
    sample_genetic_eur = "/well/lindgren/UKBIOBANK/laura/k_means_clustering_pcs/ukbb_genetically_european_k4_4PCs_self_rep_Nov2020.txt",
    sample_sex = "/well/lindgren/UKBIOBANK/nbaya/resources/ukb11867_sex.tsv",
    sample_qc = "/well/lindgren/UKBIOBANK/DATA/QC/ukb_sqc_v2.txt",
    sample_fam = "/well/lindgren/UKBIOBANK/DATA/SAMPLE_FAM/ukb11867_cal_chr1_v2_s488363.fam", # family and indiviudal IDs
    sample_excl = "/well/lindgren/UKBIOBANK/ferreira/SAMPLE_QC/ukb10844_QCexclIDs_TF_21082020", #General QC - exclusion IDs (created in March 2020 by TF; see hormones project for criteria(, including individuals that withdrew consent as of Aug/2020)
    pcs = "/gpfs3/well/lindgren/UKBIOBANK/nbaya/resources/ukb_40pcs.txt.gz"
)

# 
wes <- list(
    phenotypes = "/well/lindgren/UKBIOBANK_DATA_LINDGREN/Phenotype_data/October2017/ukb10844.csv", # october 2018 release
    sample_genetic_eur = "/well/lindgren/UKBIOBANK/laura/k_means_clustering_pcs/ukbb_genetically_european_k4_4PCs_self_rep_Nov2020.txt",
    sample_sex = "/well/lindgren/UKBIOBANK/nbaya/resources/ukb11867_sex.tsv",
    sample_qc = "/well/lindgren/UKBIOBANK/DATA/QC/ukb_sqc_v2.txt",
    sample_fam = "/well/lindgren/UKBIOBANK/DATA/WES_200k/ukb23155_c1_b0_v1_s200632.fam", # family and indiviudal IDs
    sample_excl = "/well/lindgren/UKBIOBANK/ferreira/SAMPLE_QC/ukb10844_QCexclIDs_TF_21082020", #General QC - exclusion IDs (created in March 2020 by TF; see hormones project for criteria(, including individuals that withdrew consent as of Aug/2020)
    pcs = "/gpfs3/well/lindgren/UKBIOBANK/nbaya/resources/ukb_40pcs.txt.gz"
)

# conversion tables
sample_conversion <- "/well/lindgren/UKBIOBANK/DATA/WES/bridge_11867_12788.csv" # eid_11867, eid_12788
icd_conversion <- "/well/lindgren/UKBIOBANK/ferreira/convert_disease_codes/icd9_icd10_lkps.txt"

In [4]:
obj <- imp
dt <- fread(obj$phenotypes)
dt_sample_fam <- fread(obj$sample_fam)
dt_genetic_eur <- fread(obj$sample_genetic_eur)
dt_sample_qc <- fread(obj$sample_qc)

In [5]:
# append X for easier subsetting
colnames(dt) <- gsub('-','.',colnames(dt))
colnames(dt)[colnames(dt) != 'eid'] <- paste0('X', colnames(dt)[colnames(dt) != 'eid'])
dt$X34.0.0
#covars <- extract_covars(dt, dt_sample_qc)

    [1] 1946 1940 1940 1967 1943 1951 1941 1956 1941 1946 1965 1965 1951 1952
   [15] 1947 1942 1946 1961 1958 1942 1962 1958 1945 1945 1957 1966 1956 1960
   [29] 1949 1962 1950 1957 1950 1943 1946 1950 1944 1958 1942 1953 1940 1966
   [43] 1960 1957 1946 1944 1942 1947 1943 1947 1943 1945 1951 1956 1954 1949
   [57] 1958 1968 1963 1953 1958 1944 1948 1945 1955 1949 1944 1966 1942 1967
   [71] 1951 1957 1967 1942 1967 1952 1947 1948 1956 1961 1949 1943 1959 1959
   [85] 1948 1941 1960 1944 1967 1939 1942 1952 1966 1940 1942 1955 1941 1959
   [99] 1950 1963 1968 1959 1947 1958 1939 1947 1956 1945 1937 1944 1966 1955
  [113] 1956 1964 1952 1952 1942 1966 1959 1956 1966 1951 1945 1940 1962 1959
  [127] 1947 1952 1949 1955 1949 1951 1940 1962 1947 1963 1965 1942 1945 1954
  [141] 1947 1955 1946 1968 1949 1941 1955 1940 1941 1945 1956 1956 1965 1944
  [155] 1953 1952 1939 1952 1952 1953 1950 1947 1969 1941 1952 1943 1941 1940
  [169] 1958 1960 1953 1948 1966 1947 1945 1968 1961 1946 1942 1949 1958 1948
  [183] 1952 1949 1968 1940 1957 1954 1957 1950 1945 1953 1943 1959 1947 1960
  [197] 1962 1952 1941 1958 1944 1944 1948 1965 1957 1939 1942 1947 1939 1948
  [211] 1949 1939 1953 1939 1955 1956 1964 1943 1954 1963 1948 1960 1968 1967
  [225] 1958 1947 1939 1963 1963 1944 1961 1962 1952 1947 1958 1951 1963 1953
  [239] 1959 1957 1963 1964 1946 1942 1966 1948 1955 1961 1939 1940 1952 1953
  [253] 1955 1944 1953 1945 1953 1945 1963 1949 1968 1950 1954 1948 1939 1956
  [267] 1943 1949 1943 1939 1952 1963 1943 1965 1954 1966 1965 1942 1948 1951
  [281] 1938 1967 1941 1946 1940 1949 1957 1950 1970 1943 1948 1942 1945 1964
  [295] 1952 1946 1943 1944 1951 1953 1946 1964 1947 1968 1943 1964 1952 1947
  [309] 1944 1947 1942 1949 1945 1959 1944 1946 1939 1948 1952 1951 1956 1951
  [323] 1946 1941 1952 1946 1940 1941 1940 1964 1951 1950 1943 1963 1955 1955
  [337] 1958 1942 1938 1954 1949 1957 1944 1961 1940 1944 1957 1940 1949 1966
  [351] 1955 1947 1944 1943 1950 1939 1950 1949 1953 1965 1943 1941 1944 1949
  [365] 1943 1946 1950 1944 1946 1959 1948 1962 1966 1942 1941 1965 1953 1954
  [379] 1965 1966 1958 1949 1965 1959 1963 1948 1939 1947 1964 1960 1956 1942
  [393] 1961 1952 1960 1949 1952 1948 1948 1950 1956 1957 1941 1953 1966 1955
  [407] 1943 1950 1954 1951 1946 1947 1953 1941 1948 1964 1941 1966 1950 1952
  [421] 1953 1950 1957 1960 1958 1944 1954 1947 1943 1940 1957 1954 1946 1944
  [435] 1967 1964 1950 1966 1958 1951 1948 1944 1967 1959 1945 1945 1962 1963
  [449] 1938 1964 1953 1940 1966 1968 1943 1947 1958 1965 1947 1956 1947 1957
  [463] 1963 1948 1960 1942 1952 1949 1947 1944 1957 1950 1952 1938 1945 1945
  [477] 1949 1943 1953 1947 1956 1952 1956 1953 1965 1945 1957 1942 1953 1940
  [491] 1949 1956 1958 1951 1948 1953 1940 1954 1958 1963 1943 1943 1949 1951
  [505] 1947 1955 1951 1939 1955 1951 1938 1951 1948 1939 1942 1948 1966 1966
  [519] 1947 1943 1961 1956 1965 1959 1949 1944 1942 1947 1957 1964 1948 1942
  [533] 1959 1960 1942 1948 1940 1941 1966 1951 1945 1945 1943 1964 1961 1944
  [547] 1945 1963 1945 1954 1954 1951 1950 1945 1942 1948 1962 1947 1955 1966
  [561] 1954 1947 1943 1945 1939 1954 1944 1946 1946 1958 1939 1955 1944 1944
  [575] 1941 1942 1948 1949 1958 1938 1958 1961 1954 1962 1949 1945 1963 1939
  [589] 1964 1968 1958 1944 1965 1942 1951 1967 1941 1967 1945 1963 1946 1961
  [603] 1946 1965 1959 1950 1957 1959 1948 1966 1961 1950 1956 1953 1941 1956
  [617] 1948 1951 1947 1940 1950 1957 1953 1950 1948 1957 1955 1952 1952 1948
  [631] 1967 1948 1943 1945 1966 1953 1956 1946 1953 1947 1949 1966 1958 1939
  [645] 1953 1940 1961 1960 1943 1942 1957 1950 1961 1941 1950 1966 1944 1942
  [659] 1939 1949 1958 1944 1958 1940 1952 1958 1939 1944 1945 1954 1954 1943
  [673] 1949 1950 1966 1943 1948 1957 1955 1951 1943 1967 1960 1945 1966 1950
  [687] 1951 1958 1962 1961 1961 1943 1944 1954 1966 1943 1942 1957 1948 1961
  [701] 1966 1943 1957 1946 1967 1946 1944 1944 1964 1950 1952 1947 1946 1943
  [715] 1967 1944 1960 1961 1943 1956 1949 1956 1955 1945 1959 1953 1957 1941
  [729] 1961 1955 1947 1949 1941 1960 1940 1958 1948 1955 1953 1956 1945 1959
  [743] 1946 1946 1950 1950 1961 1942 1946 1946 1966 1943 1958 1954 1967 1947
  [757] 1945 1962 1950 1960 1959 1944 1952 1955 1941 1947 1962 1946 1958 1962
  [771] 1963 1949 1961 1950 1961 1946 1943 1946 1939 1946 1946 1941 1945 1944
  [785] 1947 1942 1944 1950 1948 1942 1957 1959 1951 1952 1961 1965 1965 1940
  [799] 1963 1956 1939 1940 1948 1954 1944 1945 1943 1947 1943 1960 1960 1955
  [813] 1941 1948 1952 1963 1938 1945 1946 1963 1948 1944 1950 1944 1961 1961
  [827] 1948 1959 1941 1949 1946 1951 1944 1945 1946 1942 1950 1958 1945 1951
  [841] 1940 1964 1955 1969 1951 1944 1948 1966 1942 1945 1945 1947 1967 1966
  [855] 1949 1952 1965 1942 1963 1958 1952 1947 1941 1941 1949 1963 1963 1953
  [869] 1951 1953 1946 1962 1951 1962 1945 1964 1942 1967 1947 1950 1947 1963
  [883] 1963 1958 1947 1950 1948 1958 1951 1966 1951 1965 1941 1963 1960 1941
  [897] 1959 1960 1940 1964 1953 1956 1941 1946 1954 1959 1939 1948 1951 1952
  [911] 1945 1960 1943 1960 1956 1946 1956 1948 1944 1945 1963 1950 1944 1942
  [925] 1966 1947 1953 1947 1958 1946 1939 1953 1944 1955 1941 1945 1953 1946
  [939] 1947 1940 1940 1946 1943 1961 1958 1942 1947 1946 1966 1950 1941 1952
  [953] 1946 1944 1957 1945 1941 1947 1957 1949 1954 1947 1965 1950 1961 1945
  [967] 1942 1942 1946 1961 1956 1955 1942 1951 1950 1953 1955 1951 1950 1941
  [981] 1946 1947 1951 1947 1942 1960 1940 1962 1944 1941 1951 1954 1943 1951
  [995] 1950 1962 1945 1942 1944 1945 1966 1952 1955 1943 1949 1938 1958 1943
 [1009] 1939 1957 1940 1950 1962 1956 1955 1946 1957 1943 1960 1955 1960 1948
 [1023] 1946 1949 1949 1957 1942 1963 1955 1958 1962 1962 1946 1944 1942 1952
 [1037] 1957 1949 1953 1945 1947 1964 1951 1959 1942 1957 1959 1946 1950 1961
 [1051] 1940 1960 1942 1945 1952 1963 1943 1956 1942 1947 1942 1960 1955 1943
 [1065] 1945 1951 1949 1943 1944 1958 1954 1955 1965 1944 1942 1966 1956 1948
 [1079] 1950 1947 1953 1944 1963 1965 1939 1955 1964 1947 1943 1958 1943 1951
 [1093] 1941 1944 1960 1941 1961 1966 1947 1948 1938 1957 1939 1957 1959 1939
 [1107] 1949 1964 1945 1950 1951 1945 1949 1959 1963 1966 1942 1955 1941 1943
 [1121] 1951 1961 1963 1950 1946 1956 1959 1938 1951 1956 1960 1950 1965 1952
 [1135] 1959 1942 1942 1943 1954 1948 1960 1966 1942 1947 1939 1961 1950 1945
 [1149] 1965 1944 1963 1947 1960 1961 1944 1947 1957 1947 1965 1942 1963 1939
 [1163] 1944 1943 1950 1944 1941 1944 1967 1946 1967 1946 1947 1940 1947 1946
 [1177] 1951 1955 1950 1952 1945 1947 1961 1943 1942 1955 1947 1961 1958 1946
 [1191] 1954 1947 1951 1948 1944 1955 1950 1950 1956 1945 1945 1947 1944 1950
 [1205] 1941 1948 1968 1946 1965 1950 1952 1940 1944 1944 1957 1955 1953 1941
 [1219] 1945 1957 1960 1942 1943 1959 1963 1951 1953 1961 1950 1967 1950 1950
 [1233] 1942 1948 1946 1957 1951 1951 1942 1956 1944 1963 1964 1946 1963 1942
 [1247] 1956 1939 1946 1956 1941 1953 1965 1967 1948 1955 1959 1950 1944 1956
 [1261] 1939 1942 1956 1965 1964 1946 1957 1961 1966 1968 1948 1938 1943 1940
 [1275] 1950 1944 1946 1956 1954 1953 1941 1942 1940 1946 1947 1967 1941 1959
 [1289] 1966 1945 1950 1956 1944 1957 1945 1949 1953 1942 1962 1965 1960 1950
 [1303] 1953 1948 1967 1949 1951 1941 1948 1962 1964 1944 1953 1951 1956 1963
 [1317] 1948 1952 1962 1952 1964 1958 1960 1959 1939 1943 1962 1952 1959 1944
 [1331] 1947 1966 1938 1941 1955 1959 1953 1946 1947 1965 1951 1951 1948 1956
 [1345] 1957 1956 1956 1941 1949 1942 1958 1956 1947 1959 1946 1948 1968 1966
 [1359] 1949 1948 1960 1945 1951 1944 1969 1946 1950 1959 1943 1954 1962 1957
 [1373] 1941 1955 1939 1951 1939 1964 1956 1959 1964 1966 1942 1963 1955 1949
 [1387] 1938 1950 1965 1956 1940 1951 1954 1957 1943 1962 1967 1948 1954 1944
 [1401] 1957 1941 1937 1968 1963 1949 1944 1950 1941 1942 1963 1958 1943 1967
 [1415] 1947 1950 1939 1966 1955 1944 1946 1948 1958 1958 1958 1941 1946 1944
 [1429] 1951 1948 1959 1944 1946 1945 1966 1944 1939 1952 1944 1948 1967 1959
 [1443] 1947 1939 1948 1963 1959 1942 1946 1948 1947 1943 1947 1964 1939 1962
 [1457] 1946 1948 1958 1942 1955 1941 1939 1954 1958 1944 1952 1945 1954 1959
 [1471] 1946 1952 1942 1960 1961 1947 1956 1953 1965 1942 1944 1961 1947 1968
 [1485] 1949 1951 1947 1947 1942 1949 1956 1954 1941 1956 1950 1952 1942 1947
 [1499] 1944 1964 1941 1948 1953 1951 1960 1944 1949 1962 1940 1946 1943 1944
 [1513] 1960 1946 1941 1952 1947 1966 1940 1947 1941 1954 1966 1965 1954 1944
 [1527] 1944 1948 1939 1959 1948 1969 1960 1949 1942 1955 1938 1963 1952 1956
 [1541] 1956 1942 1942 1961 1942 1942 1954 1950 1939 1964 1958 1945 1950 1962
 [1555] 1943 1957 1938 1952 1961 1961 1946 1941 1960 1949 1947 1939 1967 1965
 [1569] 1962 1959 1947 1961 1942 1954 1943 1939 1953 1969 1963 1958 1948 1969
 [1583] 1964 1942 1955 1946 1944 1943 1964 1940 1948 1964 1966 1938 1955 1956
 [1597] 1953 1957 1949 1947 1960 1944 1968 1948 1950 1952 1969 1955 1961 1962
 [1611] 1960 1956 1959 1946 1961 1950 1940 1961 1962 1948 1965 1956 1961 1954
 [1625] 1963 1958 1961 1952 1964 1946 1939 1963 1951 1955 1948 1961 1938 1952
 [1639] 1964 1939 1948 1944 1949 1954 1945 1943 1950 1944 1941 1944 1953 1946
 [1653] 1954 1962 1959 1940 1947 1943 1965 1941 1949 1950 1954 1948 1949 1946
 [1667] 1942 1948 1965 1964 1944 1942 1942 1944 1963 1956 1942 1954 1944 1964
 [1681] 1957 1947 1946 1952 1959 1942 1943 1949 1959 1955 1956 1950 1960 1952
 [1695] 1966 1957 1959 1948 1950 1945 1939 1952 1946 1944 1965 1945 1957 1949
 [1709] 1941 1944 1949 1963 1945 1951 1946 1941 1950 1941 1951 1966 1941 1959
 [1723] 1944 1960 1941 1965 1970 1945 1959 1959 1949 1951 1950 1944 1952 1945
 [1737] 1968 1957 1949 1962 1950 1953 1950 1957 1959 1948 1954 1939 1945 1951
 [1751] 1962 1948 1967 1946 1955 1955 1951 1944 1952 1959 1944 1966 1946 1939
 [1765] 1945 1939 1942 1945 1953 1956 1946 1943 1939 1947 1947 1948 1951 1961
 [1779] 1964 1943 1953 1948 1955 1965 1954 1940 1958 1965 1942 1944 1954 1958
 [1793] 1948 1953 1961 1948 1942 1951 1945 1956 1965 1939 1946 1943 1941 1951
 [1807] 1948 1952 1946 1950 1947 1961 1947 1947 1959 1960 1953 1945 1948 1942
 [1821] 1948 1946 1946 1962 1956 1952 1957 1947 1956 1946 1951 1953 1955 1950
 [1835] 1949 1946 1940 1951 1966 1955 1962 1966 1963 1954 1962 1945 1968 1962
 [1849] 1953 1954 1960 1944 1952 1958 1947 1947 1940 1939 1948 1955 1959 1964
 [1863] 1945 1967 1965 1952 1938 1962 1953 1962 1945 1949 1953 1945 1949 1954
 [1877] 1948 1959 1947 1938 1955 1955 1952 1948 1950 1948 1943 1963 1938 1942
 [1891] 1944 1950 1949 1957 1949 1949 1946 1944 1942 1944 1949 1959 1946 1947
 [1905] 1941 1940 1950 1944 1965 1943 1954 1960 1945 1960 1948 1950 1956 1957
 [1919] 1957 1965 1960 1950 1946 1962 1955 1952 1947 1946 1947 1955 1952 1947
 [1933] 1946 1945 1964 1959 1968 1959 1962 1946 1943 1948 1939 1945 1954 1950
 [1947] 1943 1950 1966 1954 1963 1960 1942 1953 1957 1946 1959 1952 1962 1946
 [1961] 1953 1943 1961 1956 1949 1949 1941 1962 1943 1949 1960 1947 1961 1956
 [1975] 1959 1945 1958 1947 1943 1953 1943 1967 1947 1951 1942 1952 1955 1943
 [1989] 1964 1942 1960 1946 1946 1952 1952 1966 1944 1963 1948 1940 1952 1955
 [2003] 1955 1958 1949 1945 1950 1944 1950 1948 1942 1947 1962 1964 1945 1961
 [2017] 1954 1962 1951 1956 1958 1959 1965 1956 1954 1953 1948 1941 1943 1943
 [2031] 1955 1940 1961 1944 1966 1943 1952 1944 1940 1941 1956 1946 1966 1957
 [2045] 1969 1940 1957 1952 1950 1949 1960 1940 1950 1965 1967 1940 1942 1965
 [2059] 1938 1954 1951 1958 1961 1957 1952 1940 1956 1942 1948 1953 1945 1966
 [2073] 1966 1943 1955 1965 1940 1966 1946 1940 1947 1944 1952 1948 1967 1953
 [2087] 1955 1946 1946 1955 1961 1939 1956 1964 1942 1943 1941 1968 1965 1960
 [2101] 1969 1938 1952 1943 1962 1941 1959 1962 1943 1942 1956 1964 1946 1945
 [2115] 1954 1964 1951 1942 1947 1946 1953 1950 1955 1950 1963 1964 1942 1940
 [2129] 1968 1958 1951 1939 1951 1943 1961 1955 1949 1945 1940 1964 1956 1948
 [2143] 1947 1950 1951 1938 1957 1943 1941 1946 1962 1961 1953 1965 1948 1950
 [2157] 1952 1945 1947 1958 1953 1955 1954 1951 1946 1942 1950 1946 1963 1964
 [2171] 1965 1963 1948 1948 1950 1946 1966 1959 1950 1966 1955 1965 1942 1941
 [2185] 1954 1945 1954 1953 1959 1949 1944 1967 1944 1964 1945 1952 1959 1953
 [2199] 1961 1944 1964 1947 1946 1958 1944 1940 1950 1947 1948 1952 1947 1951
 [2213] 1940 1952 1941 1940 1954 1946 1951 1944 1960 1947 1965 1956 1957 1953
 [2227] 1966 1958 1956 1943 1941 1947 1939 1943 1944 1950 1957 1960 1959 1939
 [2241] 1940 1952 1942 1961 1969 1943 1958 1950 1941 1959 1950 1948 1948 1964
 [2255] 1946 1939 1950 1941 1942 1949 1948 1950 1958 1947 1941 1954 1952 1959
 [2269] 1947 1941 1952 1949 1959 1950 1954 1961 1947 1943 1949 1948 1964 1946
 [2283] 1950 1957 1962 1966 1950 1963 1965 1939 1947 1942 1961 1940 1951 1941
 [2297] 1961 1960 1960 1952 1948 1966 1946 1948 1942 1965 1947 1944 1938 1946
 [2311] 1948 1954 1940 1940 1943 1960 1969 1943 1940 1953 1964 1963 1949 1943
 [2325] 1940 1958 1966 1942 1945 1949 1959 1949 1956 1960 1951 1954 1949 1953
 [2339] 1967 1951 1960 1961 1963 1951 1953 1944 1952 1938 1957 1961 1949 1951
 [2353] 1946 1955 1956 1966 1942 1951 1942 1948 1948 1959 1944 1966 1947 1968
 [2367] 1951 1949 1948 1949 1951 1965 1962 1948 1959 1963 1969 1941 1947 1962
 [2381] 1944 1956 1949 1953 1966 1960 1960 1939 1945 1949 1941 1948 1957 1959
 [2395] 1949 1960 1947 1940 1963 1942 1958 1956 1942 1945 1943 1961 1948 1946
 [2409] 1955 1965 1958 1946 1941 1946 1943 1958 1944 1943 1940 1948 1950 1947
 [2423] 1960 1962 1948 1954 1957 1967 1949 1953 1959 1957 1951 1950 1962 1966
 [2437] 1944 1957 1955 1942 1948 1958 1946 1945 1947 1955 1958 1969 1939 1960
 [2451] 1952 1942 1957 1963 1963 1940 1956 1944 1964 1953 1965 1944 1964 1959
 [2465] 1954 1947 1954 1947 1962 1950 1943 1954 1946 1944 1956 1950 1955 1960
 [2479] 1953 1955 1952 1943 1951 1947 1943 1960 1944 1964 1943 1949 1947 1962
 [2493] 1953 1955 1964 1953 1956 1952 1966 1947 1945 1964 1943 1946 1947 1938
 [2507] 1967 1947 1944 1947 1940 1960 1945 1956 1953 1962 1950 1945 1945 1958
 [2521] 1944 1940 1939 1947 1964 1943 1953 1967 1944 1949 1945 1940 1958 1945
 [2535] 1946 1940 1954 1966 1960 1948 1946 1952 1950 1943 1945 1948 1941 1949
 [2549] 1950 1950 1945 1966 1962 1942 1961 1954 1960 1938 1954 1942 1947 1946
 [2563] 1948 1966 1942 1942 1949 1957 1957 1944 1956 1940 1957 1953 1960 1946
 [2577] 1941 1966 1947 1946 1948 1962 1955 1947 1963 1948 1959 1958 1950 1949
 [2591] 1945 1953 1957 1957 1944 1955 1964 1954 1942 1949 1952 1960 1965 1954
 [2605] 1948 1953 1941 1964 1944 1951 1941 1950 1963 1950 1961 1960 1947 1940
 [2619] 1952 1953 1961 1948 1950 1945 1954 1947 1953 1969 1954 1946 1951 1964
 [2633] 1953 1952 1939 1942 1964 1942 1961 1949 1945 1959 1950 1947 1948 1962
 [2647] 1944 1940 1957 1964 1943 1954 1946 1953 1948 1945 1947 1943 1959 1948
 [2661] 1951 1964 1950 1959 1940 1942 1944 1943 1957 1955 1948 1967 1959 1946
 [2675] 1958 1952 1946 1948 1949 1957 1955 1953 1966 1961 1967 1947 1951 1944
 [2689] 1947 1945 1939 1967 1947 1947 1953 1939 1964 1947 1961 1945 1946 1951
 [2703] 1962 1945 1968 1949 1952 1943 1958 1948 1939 1953 1947 1963 1956 1947
 [2717] 1955 1960 1960 1966 1949 1953 1949 1965 1955 1949 1960 1948 1951 1957
 [2731] 1955 1954 1951 1950 1947 1967 1952 1939 1943 1960 1951 1948 1961 1950
 [2745] 1949 1950 1958 1942 1949 1961 1945 1961 1944 1945 1960 1946 1955 1945
 [2759] 1948 1948 1943 1952 1942 1952 1964 1948 1962 1952 1948 1955 1962 1959
 [2773] 1955 1960 1966 1939 1967 1962 1940 1956 1949 1946 1950 1960 1952 1949
 [2787] 1943 1939 1964 1960 1961 1964 1946 1959 1938 1943 1954 1956 1950 1953
 [2801] 1959 1946 1953 1955 1966 1944 1962 1937 1953 1957 1943 1954 1967 1945
 [2815] 1942 1965 1961 1959 1939 1957 1950 1946 1951 1943 1958 1940 1949 1956
 [2829] 1944 1952 1950 1953 1960 1939 1964 1941 1953 1948 1955 1967 1945 1952
 [2843] 1953 1953 1953 1946 1951 1951 1951 1945 1942 1955 1945 1949 1964 1941
 [2857] 1953 1958 1950 1942 1968 1955 1943 1959 1957 1947 1944 1961 1942 1940
 [2871] 1964 1969 1967 1949 1942 1947 1958 1947 1960 1942 1945 1947 1956 1950
 [2885] 1948 1967 1949 1960 1945 1947 1944 1965 1942 1944 1943 1954 1958 1944
 [2899] 1943 1948 1965 1948 1966 1940 1942 1947 1953 1951 1946 1955 1939 1943
 [2913] 1947 1945 1940 1957 1942 1947 1947 1964 1955 1950 1954 1948 1953 1949
 [2927] 1945 1942 1947 1955 1946 1961 1942 1952 1952 1949 1943 1967 1939 1965
 [2941] 1965 1947 1955 1961 1948 1953 1946 1941 1959 1961 1944 1947 1958 1963
 [2955] 1959 1967 1956 1947 1943 1948 1950 1945 1967 1958 1960 1961 1961 1957
 [2969] 1962 1959 1941 1964 1953 1942 1955 1950 1953 1956 1944 1959 1967 1940
 [2983] 1945 1944 1940 1939 1952 1962 1944 1962 1951 1948 1967 1945 1943 1957
 [2997] 1945 1961 1940 1947 1955 1953 1945 1962 1958 1963 1948 1953 1943 1939
 [3011] 1959 1947 1939 1941 1950 1957 1967 1955 1954 1941 1953 1953 1962 1954
 [3025] 1943 1944 1940 1964 1946 1964 1953 1957 1962 1947 1949 1948 1967 1947
 [3039] 1959 1956 1945 1961 1956 1953 1944 1950 1951 1938 1957 1952 1962 1965
 [3053] 1951 1966 1946 1943 1941 1943 1959 1954 1955 1953 1939 1944 1940 1953
 [3067] 1938 1949 1939 1955 1945 1953 1942 1948 1948 1956 1958 1965 1942 1951
 [3081] 1941 1951 1941 1941 1947 1945 1939 1956 1954 1950 1944 1949 1959 1954
 [3095] 1957 1968 1938 1949 1950 1944 1966 1946 1944 1951 1963 1944 1943 1949
 [3109] 1961 1960 1944 1947 1942 1946 1948 1950 1967 1962 1941 1944 1945 1957
 [3123] 1954 1952 1959 1966 1948 1950 1948 1951 1952 1961 1946 1942 1942 1947
 [3137] 1942 1958 1949 1940 1961 1948 1942 1953 1954 1951 1947 1963 1940 1948
 [3151] 1956 1961 1966 1960 1943 1960 1964 1944 1965 1948 1950 1944 1954 1963
 [3165] 1949 1946 1959 1947 1949 1960 1953 1948 1943 1942 1954 1958 1941 1957
 [3179] 1951 1944 1955 1952 1947 1949 1939 1949 1966 1953 1947 1949 1951 1964
 [3193] 1962 1966 1953 1963 1940 1955 1951 1948 1940 1948 1942 1946 1945 1957
 [3207] 1946 1963 1947 1948 1967 1945 1944 1968 1945 1945 1955 1953 1950 1943
 [3221] 1941 1965 1943 1947 1944 1939 1967 1944 1959 1954 1944 1965 1946 1958
 [3235] 1956 1943 1962 1965 1959 1948 1942 1962 1942 1956 1958 1958 1945 1945
 [3249] 1945 1958 1952 1957 1953 1964 1945 1943 1965 1944 1954 1941 1945 1941
 [3263] 1961 1962 1953 1954 1955 1951 1945 1957 1949 1947 1953 1945 1948 1961
 [3277] 1943 1957 1952 1950 1949 1953 1947 1944 1947 1955 1959 1967 1946 1948
 [3291] 1968 1942 1942 1947 1956 1951 1962 1944 1965 1962 1965 1941 1963 1941
 [3305] 1947 1943 1949 1960 1960 1966 1957 1966 1945 1958 1944 1940 1944 1947
 [3319] 1962 1965 1945 1967 1948 1944 1945 1946 1940 1961 1951 1951 1947 1945
 [3333] 1944 1955 1948 1947 1956 1942 1961 1952 1942 1954 1943 1965 1939 1944
 [3347] 1963 1967 1951 1944 1943 1955 1955 1961 1946 1965 1958 1964 1947 1959
 [3361] 1962 1967 1945 1954 1940 1955 1942 1960 1949 1958 1945 1968 1945 1938
 [3375] 1944 1942 1947 1941 1942 1943 1951 1946 1961 1946 1945 1945 1943 1967
 [3389] 1949 1940 1942 1966 1958 1943 1947 1962 1939 1958 1948 1958 1939 1948
 [3403] 1954 1951 1947 1965 1959 1961 1968 1948 1943 1954 1940 1944 1962 1940
 [3417] 1952 1961 1954 1965 1964 1954 1943 1958 1939 1946 1956 1943 1956 1946
 [3431] 1960 1946 1954 1963 1966 1958 1952 1950 1950 1947 1949 1947 1945 1968
 [3445] 1951 1939 1947 1956 1953 1948 1966 1942 1965 1939 1956 1959 1947 1967
 [3459] 1962 1957 1946 1941 1941 1958 1957 1949 1950 1946 1949 1961 1942 1968
 [3473] 1967 1943 1953 1947 1960 1950 1969 1949 1949 1942 1940 1968 1947 1940
 [3487] 1947 1941 1956 1959 1961 1961 1963 1945 1944 1965 1946 1955 1944 1956
 [3501] 1958 1952 1950 1942 1944 1960 1939 1955 1946 1941 1942 1945 1952 1952
 [3515] 1966 1944 1948 1946 1947 1945 1943 1943 1945 1968 1959 1948 1940 1942
 [3529] 1949 1942 1950 1955 1947 1963 1944 1946 1945 1946 1961 1964 1966 1960
 [3543] 1948 1954 1951 1944 1956 1962 1964 1961 1960 1962 1956 1953 1952 1949
 [3557] 1945 1948 1959 1962 1941 1946 1949 1949 1952 1959 1955 1964 1960 1938
 [3571] 1947 1959 1966 1940 1948 1948 1948 1967 1959 1950 1945 1955 1966 1956

In [6]:
"%nin%" <- function(x, y) !(x %in% y)

In [21]:
#dt = fread(wes$phenotypes, header = TRUE)

#obj <- imp

# how many individuals in the FAM file is in the Pheno file?
#dt <- fread(obj$phenotypes)
#dt_sample_fam <- fread(obj$sample_fam)
#n_found <- sum(dt_sample_fam[[1]] %in% dt$eid)
#n_not_found <- sum(dt_sample_fam[[1]] %nin% dt$eid)
#write(paste('*',n_not_found,'of',n_found,'individuals could not be mapped.'),stdout())

In [114]:
obj <- imp
dt <- fread(obj$phenotypes)
colnames(dt) <- gsub('-','.',colnames(dt))
colnames(dt)[colnames(dt) != 'eid'] <- paste0('X', colnames(dt)[colnames(dt) != 'eid'])

In [115]:
# setup core feature matrix
dt_sample_fam <- fread(obj$sample_fam)
dt_genetic_eur <- fread(obj$sample_genetic_eur)
dt_sample_qc <- fread(obj$sample_qc)

In [116]:
#extract_covars(dt, dt_sample_qc, dt_sample_fam)

In [118]:
#dt$X34.0.0
#extract_covars(dt, dt_sample_qc)
#dt_pheno <- dt
#keep <- c('eid', 'X34.0.0', 'X52.0.0', 'X53.0.0', 'X53.1.0', 'X53.2.0')
#remove <- colnames(dt_pheno)[!colnames(dt_pheno) %in% keep]
dt_sample_qc$eid <- dt_sample_fam$V1
dt_sample_qc <- dt_sample_qc[,c('eid','Submitted.Gender','Inferred.Gender','in.white.British.ancestry.subset')]
#sum(dt_pheno$eid %in% dt_sample_qc$eid)
#dt_pheno <- merge(dt_pheno, dt_sample_qc)

dim(dt_sample_qc)
fwrite(dt_sample_qc, 'data/phenotypes/ukbb_white_british_samples.txt', sep = '\t')

[1] 488377      4

In [111]:
dt_pheno$eid

integer(0)

In [40]:
## sample level QC and standard phenotypes
# read exclusion samples
# add ID to ukb_sqc_v2.txt using ukb11867_cal_chr1_v2_s488363.fam 
# use ukb_sqc_v2.txt to add submitted gender
# use ukb_sqc_v2.txt to add inferred gender
# use ukb_sqc_v2.txt to add white british ancestry
# tally up current men/women/white british

# add recruitment age
# encode genotyping array using "X22000.0.0"
# encode ukbb.centre using "X54.0.0""
# add PCs using "22009" (with grep?)
# add ID using 'f.eid'

# age encodings (#Year of birth (year 34-0.0, month 52-0.0))
# encode age using "X53.0.0"
# encode age squared using "X53.0.0"
# encode age cubed using "X53.0.0"

## phenotype processing
# open ICD10-ICD9 code bridge file: "/well/lindgren/UKBIOBANK/ferreira/phenotype_extraction/phenotype_lists/ICD10_codes_converted_ICD9_v2v3_codes.txt
# get phenotype data from before
# get primary care data from: "/well/lindgren/UKBIOBANK/DATA/PHENOTYPE/PRIMARY_CARE/gp_clinical.txt"

In [99]:
extract_covars <- function(dt_pheno, dt_sample_qc, dt_sample_fam, keep = 'eid'){
    
    # combine dt and dt_sample_qc
    keep <- c(keep, 'X34.0.0', 'X52.0.0', 'X53.0.0', 'X53.1.0', 'X53.2.0') # keep times
    remove <- colnames(dt_pheno)[!colnames(dt_pheno) %in% keep]
    dt_sample_qc$eid <- dt_sample_fam$V1
    dt_sample_qc <- dt_sample_qc[,c('eid','Submitted.Gender','Inferred.Gender','in.white.British.ancestry.subset')]
    sum(dt_pheno$eid %in% dt_sample_qc$eid)
    dt <- merge(dt_pheno, dt_sample_qc)

    # check inputs
    stopifnot(!is.null(dt$X34.0.0))
    stopifnot(!is.null(dt$X52.0.0))
    
    # get data of birth
    dt$yob <- dt$X34.0.0
    dt$mob <- dt$X52.0.0  
    
    print(dt$yob)
    print(dt$mob)
    
    dt$dob <- as.Date(paste0(dt$yob,'-',dt$mob,'-',1))
    
    # get date of attending recruitment centre
    dt$centre_attend0 <- as.Date(dt$X53.0.0)
    dt$centre_attend1 <- as.Date(dt$X53.1.0)
    dt$centre_attend2 <- as.Date(dt$X53.2.0)
    
    # get age when attending recruitment centre
    dt$centre_attend_age0 <- calc_time_since(dt$dob, dt$centre_attend0)
    dt$centre_attend_age1 <- calc_time_since(dt$dob, dt$centre_attend1)
    dt$centre_attend_age2 <- calc_time_since(dt$dob, dt$centre_attend2)

    # get age to be used as covariates
    dt$age <- dt$centre_attend_age0
    dt$age1 <- dt$centre_attend_age0^2
    dt$age2 <- dt$centre_attend_age0^3

    # get principal components 
    bool_pc <- grep(22009,colnames(dt))
    n <- length(colnames(dt)[bool_pc])
    colnames(dt)[bool_pc] <- paste0('PC',1:n)

    # negative coding from BiLEVE (recoded 1); positive coding from axiom (recoded 2)
    dt$genotyping.array <- ifelse(dt$X22000.0.0 <0, 1, 2)
    dt$sex = ifelse(dt$Inferred.Gender == "F", 2, ifelse(dt$Inferred.Gender == "M", 1, NA))
    colnames(dt)[colnames(dt) == "X54.0.0"] = "ukbb.centre"
    
    # clean up
    bool_keep <- ! colnames(dt) %in% remove
    dt = dt[,bool_keep, with = FALSE]
    
    return(dt)
}

In [27]:
remove <- colnames(dt)[!colnames(dt) %in% 'eid']
c('age') %in% remove
q <- extract_covars(dt, dt_sample_qc)
q

[1] FALSE

       eid     ukbb.centre PC1       PC2       PC3       PC4       PC5
1      1012978 11005       -14.22390  4.316110 -2.583720  4.110260 13.956500
2      1025876 11003       -10.88470  2.597800 -3.181410 -2.436430 -8.347310
3      1026769 11009       -11.73770  4.467900 -0.870203  0.495115 -2.478190
4      1040495 11013       -11.94830  5.276710  0.114861 -5.288530 -4.577080
5      1052795 11020        -8.21625  3.971510 -1.450520 -9.344880 -5.281080
6      1105858 11009        -8.85043  4.623670  1.649860  2.622890  8.842090
7      1141098 11010       -12.89680  4.037370 -2.344310  2.512150 -6.746900
8      1211428 11021       352.54000 69.735200 -4.430110  4.055590  0.879280
9      1225243 11013        -9.84792  2.461370 -0.705939  2.169720  5.664680
10     1255081 11016       -12.13110  5.434320 -3.680390  1.507940 -4.825730
11     1281914 11007       -11.08030  2.354210 -0.619291 -2.338260 -8.527430
12     1290904 11007       -11.05840  2.885930 -2.670940 -1.061110 -3.197920
13     1439300 11013       -11.19020  2.204540 -2.004280  1.929810 -1.124460
14     1510841 11013       -10.72740  4.897340 -3.208850 -0.444468 -7.031270
15     1564291 11002       -15.40360  1.734290 -1.959970 -0.457922 -3.270680
16     1564609 11003        -9.96050  4.987970 -2.442780  3.901900 -1.985770
17     1630686 11022       -15.93840  4.922750 -1.624950  3.653020  7.511430
18     1688807 11004       -15.03140  3.042700 -2.057590 10.435500 19.405900
19     1704493 11016       -12.54830  3.932520 -3.053840  4.068100  8.599810
20     1724225 11009       -12.26810  3.947030 -0.548870  2.795370 -0.474879
21     1772203 11005       -13.62140  0.409363 -1.633160  1.369360  2.595070
22     1788392 11013       -10.38570  0.420676  1.232360  0.693184 -5.521070
23     1788512 11004       -14.21050  4.423680 -2.253710  2.270660  9.991790
24     1887982 11011       -14.78120  3.803870 -0.937699  1.897190  0.223922
25     1919810 11010       -13.06370  0.282918 -2.388140  4.576730 -2.727280
26     1988386 11014       -12.70830  5.200720 -3.099140  4.239060  8.980980
27     2024530 11002       -11.31900  3.779660 -0.145360  0.497923 -0.436955
28     2040953 11022       -13.08130  5.476190 -1.334590  3.772200  5.327930
29     2137034 11022       -13.73840  1.793800 -2.126300  6.534620  9.085440
30     2169372 11016       -11.87380  3.137930 -2.675540  4.277260  5.737350
<U+22EE> <U+22EE> <U+22EE>    <U+22EE>  <U+22EE>  <U+22EE>  <U+22EE>  <U+22EE>
70     4498097 11020       -12.10040  2.13413  -1.491960  5.425740  10.474600
71     4560868 11016       -12.17060  5.14596  -3.974750  2.731630   4.502700
72     4646821 11013       -10.79110  3.97154  -1.190760 -4.485860  -6.597300
73     4676114 11013       -12.38830  4.65253  -1.523110 -1.930420  -9.429270
74     4747165 11013        -9.88766  3.94416  -0.796497  0.702446   0.808130
75     4853664 11016       -10.52140  5.08040  -2.997150  2.614870   1.243610
76     4945489 11006        -2.00317  7.51690   1.498150  5.484780   7.031090
77     4959009 11018       -11.10390  5.36531  -0.343093  0.494209  -6.474520
78     5064701 11018       -12.79670  4.04766  -2.026760  1.255230  -0.568223
79     5084569 11020       -12.23990  1.85633  -0.787974  2.139760  -2.159130
80     5096620 11011       -10.17950  2.35218  -1.607120  2.060630  -5.289900
81     5133124 11016        -8.84772  1.42126  -1.548560 -3.971640  -4.598410
82     5156720 11009       -11.05320  1.05961  -3.541210  1.113400   0.370002
83     5164095 11011       -12.74830  4.44170  -2.097810  0.523219  -5.518430
84     5201867 11020       -11.79130  1.43651   0.186268 -1.123100  -2.402690
85     5257179 11008       -12.50490  3.01040  -0.921331  0.336038  -2.395780
86     5335711 11007       407.92400 78.46650  -3.837740  5.023460  -2.361650
87     5540364 11011       -10.92280  4.71380   0.653275  1.321140  -3.821580
88     5554974 11014       -14.17450  4.28944   0.846251  3.173240   6.140110
89     5560949 11016       -11.62660  3.89408  -3.320440 -1.124750  -5.323750
90     5579847 11017       -12.77360  3.32529   0.479223 -0.212506  -8.253710
91     5595081 11021       393.33700 73.26830  -5.229740  5.071800   0.335860
92     5636400 11013       -13.89920  4.82472  -2.976010  2.972530  -1.513490
93     5680680 11013       -14.62020  4.75043  -1.211430  0.948968   0.179520
94     5791813 11013       -14.13060  4.72826   0.414764 -3.115740  -7.479660
95     5853624 11010       -11.79710  3.32154  -2.973230  4.948880  -0.902571
96     5908756 11020       -14.37090  4.95458  -5.388210  8.748090  28.512900
97     5923272 11013       -11.93020  2.69665  -3.206340  0.623006 -10.114000
98     5939828 11010       -12.26830  2.63041  -1.648640 -0.210796  -6.569820
99     6016236 11018       -10.44430  5.39256  -0.642781  1.837700  -2.368400
       PC6        PC7        PC8        <U+22EF>   centre_attend1 centre_attend2
1       1.5437400  2.5340200  4.2530500 <U+22EF> <NA>           <NA>
2       0.2943190  1.3257300  1.9210100 <U+22EF> <NA>           <NA>
3      -2.9397400 -2.3961400 -1.5207000 <U+22EF> <NA>           <NA>
4      -2.9125600  5.6781700 -0.6177910 <U+22EF> <NA>           <NA>
5      -0.9078920  2.0279400  1.7880100 <U+22EF> <NA>           <NA>
6      -1.4098900  1.5634800  3.6415500 <U+22EF> <NA>           <NA>
7      -1.0318400 -0.2375480 -3.3133400 <U+22EF> <NA>           <NA>
8       2.5685300 -0.7522970 -0.0639162 <U+22EF> <NA>           <NA>
9       0.7055550  0.3443690 -2.1653300 <U+22EF> <NA>           <NA>
10     -2.1093900  3.0862200 -2.1382000 <U+22EF> <NA>           <NA>
11     -1.7530800  3.2338500  0.6042860 <U+22EF> <NA>           <NA>
12      1.0136300  1.1280700 -3.9898000 <U+22EF> <NA>           <NA>
13     -1.4513200  0.3691910  1.8264000 <U+22EF> <NA>           2016-08-20
14     -0.4197010  0.0351663  1.1992500 <U+22EF> <NA>           <NA>
15      1.6821000  5.4784300  0.2423030 <U+22EF> <NA>           <NA>
16      0.1673190  1.2487700  0.2187050 <U+22EF> <NA>           <NA>
17      0.4150650 -2.2819600 -0.5244300 <U+22EF> <NA>           <NA>
18     -0.3261770 -2.3829300  1.8276700 <U+22EF> <NA>           <NA>
19      0.4505740  2.2720800  2.1233800 <U+22EF> <NA>           <NA>
20      1.9419600 -0.1191290 -1.2778600 <U+22EF> <NA>           <NA>
21      0.9676860  1.2044000 -2.6043900 <U+22EF> <NA>           <NA>
22     -2.8447600  0.8618380 -0.1468440 <U+22EF> <NA>           <NA>
23     -2.4980100 -0.4793410  1.7196300 <U+22EF> <NA>           <NA>
24     -2.1263100 -0.9938410 -1.2905000 <U+22EF> <NA>           <NA>
25      0.0136681 -0.3898450 -1.6727800 <U+22EF> 2012-12-12     <NA>
26     -1.7272900  1.5644900  0.7478340 <U+22EF> <NA>           <NA>
27     -1.5189400  4.1294500 -1.5491600 <U+22EF> <NA>           <NA>
28     -0.0664087  0.6367840 -3.4984800 <U+22EF> <NA>           <NA>
29     -3.0738900  1.7141500 -1.3560700 <U+22EF> <NA>           <NA>
30     -1.0981800 -1.3276700 -1.9031700 <U+22EF> <NA>           <NA>
<U+22EE> <U+22EE>   <U+22EE>   <U+22EE>   <U+22F1> <U+22EE>       <U+22EE>
70      1.3641400 -0.4947890  0.7969200 <U+22EF> <NA>           <NA>
71     -1.9682300  1.5957800  0.8240380 <U+22EF> <NA>           <NA>
72     -0.7114180  1.5787300 -2.3933800 <U+22EF> <NA>           <NA>
73      0.2061940  0.9476580 -0.7244380 <U+22EF> <NA>           <NA>
74     -2.8691500  3.7019600 -1.6771800 <U+22EF> <NA>           <NA>
75      0.8227910  0.1042020 -2.0742200 <U+22EF> <NA>           <NA>
76     -1.6635300 -0.8458900  0.0902504 <U+22EF> <NA>           <NA>
77     -0.1948090 -0.9022210  3.5351100 <U+22EF> <NA>           <NA>
78      2.3574100  3.5808300  0.4410570 <U+22EF> <NA>           <NA>
79     -0.9879940  3.6355500  2.1216100 <U+22EF> <NA>           <NA>
80     -0.8918690  1.8085600 -0.2370910 <U+22EF> <NA>           <NA>
81     -0.1695040 -2.3072400  2.3886200 <U+22EF> <NA>           <NA>
82     -0.3436560 -2.2513900  0.8524660 <U+22EF> <NA>           <NA>
83     -1.4083200 -0.8767850  0.7527520 <U+22EF> <NA>           <NA>
84     -0.0139098  2.8516700  1.8461600 <U+22EF> <NA>           <NA>
85      2.1202600 -2.2553500  0.1165770 <U+22EF> <NA>           <NA>
86     -3.3438300 -3.7686400  3.7045700 <U+22EF> <NA>           <NA>
87      2.4127400  0.5340620  1.8382900 <U+22EF> <NA>           <NA>
88     -3.0627300 -2.5394800 -0.4058940 <U+22EF> <NA>           <NA>
89     -0.2490280  0.1789760  0.6327640 <U+22EF> <NA>           <NA>
90     -1.2510700 -1.5050500  2.1512900 <U+22EF> <NA>           <NA>
91     -0.5579020 -1.0851900 -0.6467060 <U+22EF> <NA>           <NA>
92     -2.4464100 -0.0488565 -2.1317400 <U+22EF> <NA>           <NA>
93      1.6045100 -2.9613700  0.1261050 <U+22EF> <NA>           <NA>
94     -0.7302370  1.4326400 -0.9287560 <U+22EF> <NA>           <NA>
95     -4.1282800  0.3270210 -2.4072500 <U+22EF> <NA>           <NA>
96     -3.3965500 -0.2066060  1.8052100 <U+22EF> <NA>           <NA>
97      0.3052880 -0.2688470 -2.5305900 <U+22EF> <NA>           <NA>
98     -1.1771600  3.4373100 -0.0601241 <U+22EF> <NA>           <NA>
99     -0.2137470 -1.2962000 -1.6531500 <U+22EF> <NA>           <NA>
       centre_attend_age0 centre_attend_age1 centre_attend_age2 age    age1
1      51                 NA                 NA                 51     2601
2      41                 NA                 NA                 41     1681
3      66                 NA                 NA                 66     4356
4      66                 NA                 NA                 66     4356
5      59                 NA                 NA                 59     3481
6      49                 NA                 NA                 49     2401
7      58                 NA                 NA                 58     3364
8      50                 NA                 NA                 50     2500
9      48                 NA                 NA                 48     2304
10     63                 NA                 NA                 63     3969
11     63                 NA                 NA                 63     3969
12     56                 NA                 NA                 56     3136
13     60                 NA                 68                 60     3600
14     46                 NA                 NA                 46     2116
15     65                 NA                 NA                 65     4225
16     50                 NA                 NA                 50     2500
17     53                 NA                 NA                 53     2809
18     53                 NA                 NA                 53     2809
19     62                 NA                 NA                 62     3844
20     59                 NA                 NA                 59     3481
21     49                 NA                 NA                 49     2401
22     66                 NA                 NA                 66     4356
23     49                 NA                 NA                 49     2401
24     66                 NA                 NA                 66     4356
25     66                 69                 NA                 66     4356
26     57                 NA                 NA                 57     3249
27     55                 NA                 NA                 55     3025
28     67                 NA                 NA                 67     4489
29     48                 NA                 NA                 48     2304
30     53                 NA                 NA                 53     2809
<U+22EE> <U+22EE>           <U+22EE>           <U+22EE>           <U+22EE> <U+22EE>
70     59                 NA                 NA                 59     3481
71     46                 NA                 NA                 46     2116
72     49                 NA                 NA                 49     2401
73     47                 NA                 NA                 47     2209
74     63                 NA                 NA                 63     3969
75     58                 NA                 NA                 58     3364
76     61                 NA                 NA                 61     3721
77     69                 NA                 NA                 69     4761
78     44                 NA                 NA                 44     1936
79     57                 NA                 NA                 57     3249
80     66                 NA                 NA                 66     4356
81     46                 NA                 NA                 46     2116
82     64                 NA                 NA                 64     4096
83     63                 NA                 NA                 63     3969
84     63                 NA                 NA                 63     3969
85     57                 NA                 NA                 57     3249
86     66                 NA                 NA                 66     4356
87     60                 NA                 NA                 60     3600
88     53                 NA                 NA                 53     2809
89     62                 NA                 NA                 62     3844
90     63                 NA                 NA                 63     3969
91     43                 NA                 NA                 43     1849
92     67                 NA                 NA                 67     4489
93     43                 NA                 NA                 43     1849
94     64                 NA                 NA                 64     4096
95     67                 NA                 NA                 67     4489
96     66                 NA                 NA                 66     4356
97     65                 NA                 NA                 65     4225
98     41                 NA                 NA                 41     1681
99     66                 NA                 NA                 66     4356
       age2   genotyping.array sex
1      132651 2                2
2       68921 2                2
3      287496 2                2
4      287496 2                1
5      205379 2                1
6      117649 2                2
7      195112 2                2
8      125000 2                1
9      110592 2                2
10     250047 2                2
11     250047 2                2
12     175616 2                2
13     216000 2                2
14      97336 2                2
15     274625 2                1
16     125000 2                1
17     148877 2                1
18     148877 2                1
19     238328 2                2
20     205379 2                2
21     117649 2                1
22     287496 2                2
23     117649 1                1
24     287496 2                2
25     287496 2                1
26     185193 2                1
27     166375 2                2
28     300763 2                2
29     110592 2                2
30     148877 1                1
<U+22EE> <U+22EE> <U+22EE>         <U+22EE>
70     205379 2                1
71      97336 1                2
72     117649 2                1
73     103823 2                2
74     250047 1                2
75     195112 2                1
76     226981 2                1
77     328509 2                2
78      85184 2                1
79     185193 2                2
80     287496 1                1
81      97336 2                1
82     262144 2                1
83     250047 2                2
84     250047 2                1
85     185193 2                2
86     287496 2                2
87     216000 2                1
88     148877 1                2
89     238328 2                1
90     250047 2                1
91      79507 2                2
92     300763 2                2
93      79507 2                2
94     262144 2                2
95     300763 2                1
96     287496 2                1
97     274625 2                2
98      68921 2                2
99     287496 2                2

[1] NA                             "Trachea_bronchus_lung_cancer"

In [14]:
# count gender / white british
out_df <- as.data.frame(table(mrg$Inferred.Gender, mrg$in.white.British.ancestry.subset))
colnames(out_df) <- c('sex','wb','count')
out_df

ERROR: Error in table(mrg$Inferred.Gender, mrg$in.white.British.ancestry.subset): object 'mrg' not found

In [ ]:
#dt[['X22000.0.0']]
colnames(dt)[grepl('22000',colnames(dt))]

In [30]:
gp=fread("/well/lindgren/UKBIOBANK/DATA/PHENOTYPE/PRIMARY_CARE/gp_clinical.txt", header=T, sep="\t", nrows = 100)

In [55]:
dt_biomarker <- fread('/gpfs1/well/lindgren/UKBIOBANK/DATA/Biomarker_data/ukb27722.csv', nrows = 1000 )

Warning message in require_bit64_if_needed(ans):
"Some columns are type 'integer64' but package bit64 is not installed. Those columns will print as strange looking floating point data. There is no need to reload the data. Simply install.packages('bit64') to obtain the integer64 print method and print the data again."

Warning message in require_bit64_if_needed(ans):
"Some columns are type 'integer64' but package bit64 is not installed. Those columns will print as strange looking floating point data. There is no need to reload the data. Simply install.packages('bit64') to obtain the integer64 print method and print the data again."

In [104]:
find_data_fields <- function(traits='chrons', by = 'coding_description'){
    
    #m <- fread('../utils/modules/R/ukbtools/extdata/pan_ukbb_manifest_210916.csv')
    stopifnot(by %in% colnames(m))
    
    
    
    lapply(traits, function(tr) m[ m[[by]] == tr,])
    
    
}


find_data_fields()

Warning message in cbind(parts$left, ellip_h, parts$right, deparse.level = 0L):
"number of rows of result is not a multiple of vector length (arg 2)"
Warning message in cbind(parts$left, ellip_h, parts$right, deparse.level = 0L):
"number of rows of result is not a multiple of vector length (arg 2)"
Warning message in cbind(parts$left, ellip_h, parts$right, deparse.level = 0L):
"number of rows of result is not a multiple of vector length (arg 2)"

[[1]]
Empty data.table (0 rows and 48 cols): trait_type,phenocode,pheno_sex,coding,modifier,description...

In [131]:
manifest_search_trait <- function(traits, by = 'coding_description', manifest_file = '/utils/modules/R/ukbtools/extdata/pan_ukbb_manifest_210916.csv'){
    stopifnot(by %in% colnames(m))
    search_matrix <- do.call(rbind, lapply(traits, function(tr) { 
        col = tolower(m[[by]])
        bool_trait = grepl(tr, col)
        bool_not = grepl('not', col)
        m = m[bool_trait & !bool_not,]
        m$search_term = tr
        return(m)
    }))
    return(search_matrix)
}

In [153]:

cancer_manifest <- manifest_search_trait('bladder +cancer')



#field_code_summary

cdt <- data.frame(origin = colnames(dt))
cdt$phenocode <- NA
phenocode_bool <- grepl('X', cdt$origin)
phenocodes <- strsplit( phenocodes[phenocode_bool], split = "X|\\.")
#cdt$phenocode[phenocode_bool] <- 
#phenocodes

# Look for trait we want to investigate
#trait = 'cancer'
#bool = grepl(trait, m$coding_description)
#cur_phenocode = m[bool,]$phenocode
#print(cur_phenocode)


# code.time_of_assesment.number_of_values
#'X20001.0.0'


#dt_bool = colnames(dt) == 'X20001.0.0'
#coding = as.vector(na.omit(dt[,dt_bool, with = F]))

ERROR: Error in strsplit(phenocodes[phenocode_bool], split = "X|\\."): non-character argument

In [69]:
#sum(grepl('30640',colnames(dt_biomarker)))

bool = grepl('1002', colnames(dt))
colnames(dt)[bool]

 [1] "X21002.0.0"  "X21002.1.0"  "X21002.2.0"  "X100200.0.0" "X100200.1.0"
 [6] "X100200.2.0" "X100200.3.0" "X100200.4.0" "X100210.0.0" "X100210.1.0"
[11] "X100210.2.0" "X100210.3.0" "X100210.4.0" "X100220.0.0" "X100220.1.0"
[16] "X100220.2.0" "X100220.3.0" "X100220.4.0" "X100230.0.0" "X100230.1.0"
[21] "X100230.2.0" "X100230.3.0" "X100230.4.0" "X100240.0.0" "X100240.1.0"
[26] "X100240.2.0" "X100240.3.0" "X100240.4.0" "X100250.0.0" "X100250.1.0"
[31] "X100250.2.0" "X100250.3.0" "X100250.4.0" "X100260.0.0" "X100260.1.0"
[36] "X100260.2.0" "X100260.3.0" "X100260.4.0" "X100270.0.0" "X100270.1.0"
[41] "X100270.2.0" "X100270.3.0" "X100270.4.0" "X100280.0.0" "X100280.1.0"
[46] "X100280.2.0" "X100280.3.0" "X100280.4.0" "X100290.0.0" "X100290.1.0"
[51] "X100290.2.0" "X100290.3.0" "X100290.4.0"

In [45]:
icd10 <- make_icd_mapping('ICD10','DESCRIPTION_ICD10')
icd9_icd10 <- make_icd_mapping('ICD9','ICD10')
icd9 <- make_icd_mapping('ICD9','DESCRIPTION_ICD9')

In [33]:
m <- dt
cn <- colnames(m)
bool <- grepl('41202',cn)
print(sum(bool))
m[,bool, with = F]

[1] 380

       X41202.0.0 X41202.0.1 X41202.0.2 X41202.0.3 X41202.0.4 X41202.0.5
1
2      M169
3      N390       N133       K296       K259       D122
4      O049       K660       N946       J329
5      K083
6      H830       K409
7      R001       I48
8      L721
9      R31        R194       N40        K573       N459
10     K137       Z092       K20
11     Z421       Z411       Z349       O680       C502       I500
12     O342
13     M232
14     S5200      S510       M0699      M0690      M069       L405
15     S610       G560
16     S930       H269
17     K297       M2333      M2322
18     S0240      R102       N899       D259
19     M2323      N47        H330
20     G439
21     M232       L82        H521       H251       C445
22     R933       R12        R074       R073       M2324      M2316
23     T840
24     R103       M7667      M7666      K419       H024       D24
25     K409
26
27     C440
28     T432       K625       F432
29
30     N359
<U+22EE> <U+22EE>   <U+22EE>   <U+22EE>   <U+22EE>   <U+22EE>   <U+22EE>
71
72     R040
73     O800       O420
74
75     D168
76
77     S5250      N840       D259       K635
78
79
80     R068       D225
81     K760
82     R073       I841       Z466       C61
83
84     N508       F200       C859       C062       B212
85     I723       I714
86     D509
87     R071       J939
88     Z452       R31        R103       K620       J069       D120
89
90     N816       M201       I471       B028       H160
91     M201       C504
92     Z138       R101       M7989      M7986      M0699      K808
93     N950
94     Z018       Q387       H401       N328       K221
95     R69        N12        H332       H269       K590
96     N200       K359       I251       I200       I080       B07
97     D170
98     I639
99     R074       H950
100
       X41202.0.6 X41202.0.7 X41202.0.8 X41202.0.9 <U+22EF>   X41202.0.370
1                                                  <U+22EF> NA
2                                                  <U+22EF> NA
3                                                  <U+22EF> NA
4                                                  <U+22EF> NA
5                                                  <U+22EF> NA
6                                                  <U+22EF> NA
7                                                  <U+22EF> NA
8                                                  <U+22EF> NA
9                                                  <U+22EF> NA
10                                                 <U+22EF> NA
11     I420                                        <U+22EF> NA
12                                                 <U+22EF> NA
13                                                 <U+22EF> NA
14                                                 <U+22EF> NA
15                                                 <U+22EF> NA
16                                                 <U+22EF> NA
17                                                 <U+22EF> NA
18                                                 <U+22EF> NA
19                                                 <U+22EF> NA
20                                                 <U+22EF> NA
21                                                 <U+22EF> NA
22     K219       I200       M6534                 <U+22EF> NA
23                                                 <U+22EF> NA
24     H251                                        <U+22EF> NA
25                                                 <U+22EF> NA
26                                                 <U+22EF> NA
27                                                 <U+22EF> NA
28                                                 <U+22EF> NA
29                                                 <U+22EF> NA
30                                                 <U+22EF> NA
<U+22EE> <U+22EE>   <U+22EE>   <U+22EE>   <U+22EE>   <U+22F1> <U+22EE>
71                                                 <U+22EF> NA
72                                                 <U+22EF> NA
73                                                 <U+22EF> NA
74                                                 <U+22EF> NA
75                                                 <U+22EF> NA
76                                                 <U+22EF> NA
77                                                 <U+22EF> NA
78                                                 <U+22EF> NA
79                                                 <U+22EF> NA
80                                                 <U+22EF> NA
81                                                 <U+22EF> NA
82                                                 <U+22EF> NA
83                                                 <U+22EF> NA
84                                                 <U+22EF> NA
85                                                 <U+22EF> NA
86                                                 <U+22EF> NA
87                                                 <U+22EF> NA
88     C259                                        <U+22EF> NA
89                                                 <U+22EF> NA
90                                                 <U+22EF> NA
91                                                 <U+22EF> NA
92     K625       G560       D352       K439       <U+22EF> NA
93                                                 <U+22EF> NA
94                                                 <U+22EF> NA
95                                                 <U+22EF> NA
96                                                 <U+22EF> NA
97                                                 <U+22EF> NA
98                                                 <U+22EF> NA
99                                                 <U+22EF> NA
100                                                <U+22EF> NA
       X41202.0.371 X41202.0.372 X41202.0.373 X41202.0.374 X41202.0.375
1      NA           NA           NA           NA           NA
2      NA           NA           NA           NA           NA
3      NA           NA           NA           NA           NA
4      NA           NA           NA           NA           NA
5      NA           NA           NA           NA           NA
6      NA           NA           NA           NA           NA
7      NA           NA           NA           NA           NA
8      NA           NA           NA           NA           NA
9      NA           NA           NA           NA           NA
10     NA           NA           NA           NA           NA
11     NA           NA           NA           NA           NA
12     NA           NA           NA           NA           NA
13     NA           NA           NA           NA           NA
14     NA           NA           NA           NA           NA
15     NA           NA           NA           NA           NA
16     NA           NA           NA           NA           NA
17     NA           NA           NA           NA           NA
18     NA           NA           NA           NA           NA
19     NA           NA           NA           NA           NA
20     NA           NA           NA           NA           NA
21     NA           NA           NA           NA           NA
22     NA           NA           NA           NA           NA
23     NA           NA           NA           NA           NA
24     NA           NA           NA           NA           NA
25     NA           NA           NA           NA           NA
26     NA           NA           NA           NA           NA
27     NA           NA           NA           NA           NA
28     NA           NA           NA           NA           NA
29     NA           NA           NA           NA           NA
30     NA           NA           NA           NA           NA
<U+22EE> <U+22EE>     <U+22EE>     <U+22EE>     <U+22EE>     <U+22EE>
71     NA           NA           NA           NA           NA
72     NA           NA           NA           NA           NA
73     NA           NA           NA           NA           NA
74     NA           NA           NA           NA           NA
75     NA           NA           NA           NA           NA
76     NA           NA           NA           NA           NA
77     NA           NA           NA           NA           NA
78     NA           NA           NA           NA           NA
79     NA           NA           NA           NA           NA
80     NA           NA           NA           NA           NA
81     NA           NA           NA           NA           NA
82     NA           NA           NA           NA           NA
83     NA           NA           NA           NA           NA
84     NA           NA           NA           NA           NA
85     NA           NA           NA           NA           NA
86     NA           NA           NA           NA           NA
87     NA           NA           NA           NA           NA
88     NA           NA           NA           NA           NA
89     NA           NA           NA           NA           NA
90     NA           NA           NA           NA           NA
91     NA           NA           NA           NA           NA
92     NA           NA           NA           NA           NA
93     NA           NA           NA           NA           NA
94     NA           NA           NA           NA           NA
95     NA           NA           NA           NA           NA
96     NA           NA           NA           NA           NA
97     NA           NA           NA           NA           NA
98     NA           NA           NA           NA           NA
99     NA           NA           NA           NA           NA
100    NA           NA           NA           NA           NA
       X41202.0.376 X41202.0.377 X41202.0.378 X41202.0.379
1      NA           NA           NA           NA
2      NA           NA           NA           NA
3      NA           NA           NA           NA
4      NA           NA           NA           NA
5      NA           NA           NA           NA
6      NA           NA           NA           NA
7      NA           NA           NA           NA
8      NA           NA           NA           NA
9      NA           NA           NA           NA
10     NA           NA           NA           NA
11     NA           NA           NA           NA
12     NA           NA           NA           NA
13     NA           NA           NA           NA
14     NA           NA           NA           NA
15     NA           NA           NA           NA
16     NA           NA           NA           NA
17     NA           NA           NA           NA
18     NA           NA           NA           NA
19     NA           NA           NA           NA
20     NA           NA           NA           NA
21     NA           NA           NA           NA
22     NA           NA           NA           NA
23     NA           NA           NA           NA
24     NA           NA           NA           NA
25     NA           NA           NA           NA
26     NA           NA           NA           NA
27     NA           NA           NA           NA
28     NA           NA           NA           NA
29     NA           NA           NA           NA
30     NA           NA           NA           NA
<U+22EE> <U+22EE>     <U+22EE>     <U+22EE>     <U+22EE>
71     NA           NA           NA           NA
72     NA           NA           NA           NA
73     NA           NA           NA           NA
74     NA           NA           NA           NA
75     NA           NA           NA           NA
76     NA           NA           NA           NA
77     NA           NA           NA           NA
78     NA           NA           NA           NA
79     NA           NA           NA           NA
80     NA           NA           NA           NA
81     NA           NA           NA           NA
82     NA           NA           NA           NA
83     NA           NA           NA           NA
84     NA           NA           NA           NA
85     NA           NA           NA           NA
86     NA           NA           NA           NA
87     NA           NA           NA           NA
88     NA           NA           NA           NA
89     NA           NA           NA           NA
90     NA           NA           NA           NA
91     NA           NA           NA           NA
92     NA           NA           NA           NA
93     NA           NA           NA           NA
94     NA           NA           NA           NA
95     NA           NA           NA           NA
96     NA           NA           NA           NA
97     NA           NA           NA           NA
98     NA           NA           NA           NA
99     NA           NA           NA           NA
100    NA           NA           NA           NA

In [54]:
icd10(c('M169','I48','J329'))

[1] "Coxarthrosis, unspecified"      NA
[3] "Chronic sinusitis, unspecified"

In [59]:
#dt_biomarker[,grepl('40006',cn), with = F]

In [113]:
# for each "disease"
# extract ICD10 code
# use dt_biomarker file to extract relevant disease using ICD10 code

test <- fread(icd_conversion)
length(unique(test$ICD10))

[1] 219

In [90]:
disease <- make_icd_mapping('disease','ICD10')

In [101]:
disease('breast_cancer')

[1] "C50"

In [99]:
length(unique(test$disease))
unique(test$disease)

[1] 37

 [1] "colorectal_cancer"
 [2] "Trachea_bronchus_lung_cancer"
 [3] "breast_cancer"
 [4] "hypothalamic_amenorrhea"
 [5] "PCOS"
 [6] "POI"
 [7] "dementia"
 [8] "Alzheimers_disease"
 [9] "depression"
[10] "ADHD"
[11] "renal_failure"
[12] "coronary_artery_disease"
[13] "ischaemic_heart_disease"
[14] "stroke"
[15] "stroke_hemorrhagic"
[16] "ischaemic_stroke"
[17] "chronic_obstructive_pulmonary_disease"
[18] "Crohns_disease"
[19] "IBD"
[20] "Cirrhosis"
[21] "NASH"
[22] "NAFLD"
[23] "psoriais"
[24] "hyperandrogenism"
[25] "hematuria"
[26] "proteinuria"
[27] "acute_renal_failure"
[28] "chronic_kidney_disease"
[29] "male_infertility"
[30] "oligomenorrhea"
[31] "habitual_aborter"
[32] "female_infertility"
[33] "ectopic_pregnancy"
[34] "Preeclampsia"
[35] "GDM"
[36] "intrahepatic_cholestasis_in_pregnancy"
[37] "polycystic_kidney_disease"

In [106]:
'N133' %in% test$V2_code
'N133' %in% test$V2_code
'N133' %in% test$V3_code

[1] FALSE

[1] FALSE

In [30]:
colnames(x)

[1] "ICD9"              "DESCRIPTION_ICD9"  "ICD10"
[4] "DESCRIPTION_ICD10"