In [5]:
# extract phenotypes
library(de)
library(data.table)
library(tidyverse)
library(ggrepel)
library(lubridate)
#install.packages('bit64')
setwd('/well/lindgren/UKBIOBANK/flassen/projects/KO/wes_ko_ukbb/')

ERROR: Error in library(devtools): there is no package called 'devtools'

In [4]:
#devtools::load_all('utils/modules/R/ukbtools/ukbtools.Rproj')

ERROR: Error in loadNamespace(x): there is no package called 'devtools'

In [18]:
# phenotype tables
imp <- list(
    phenotypes = "/well/lindgren/UKBIOBANK_DATA_LINDGREN/Phenotype_data/October2017/ukb10844.csv", # october 2018 release
    sample_genetic_eur = "/well/lindgren/UKBIOBANK/laura/k_means_clustering_pcs/ukbb_genetically_european_k4_4PCs_self_rep_Nov2020.txt",
    sample_sex = "/well/lindgren/UKBIOBANK/nbaya/resources/ukb11867_sex.tsv",
    sample_qc = "/well/lindgren/UKBIOBANK/DATA/QC/ukb_sqc_v2.txt",
    sample_fam = "/well/lindgren/UKBIOBANK/DATA/SAMPLE_FAM/ukb11867_cal_chr1_v2_s488363.fam", # family and indiviudal IDs
    sample_excl = "/well/lindgren/UKBIOBANK/ferreira/SAMPLE_QC/ukb10844_QCexclIDs_TF_21082020", #General QC - exclusion IDs (created in March 2020 by TF; see hormones project for criteria(, including individuals that withdrew consent as of Aug/2020)
    pcs = "/gpfs3/well/lindgren/UKBIOBANK/nbaya/resources/ukb_40pcs.txt.gz"
)

# 
wes <- list(
    phenotypes = "/well/lindgren/UKBIOBANK_DATA_LINDGREN/Phenotype_data/October2017/ukb10844.csv", # october 2018 release
    sample_genetic_eur = "/well/lindgren/UKBIOBANK/laura/k_means_clustering_pcs/ukbb_genetically_european_k4_4PCs_self_rep_Nov2020.txt",
    sample_sex = "/well/lindgren/UKBIOBANK/nbaya/resources/ukb11867_sex.tsv",
    sample_qc = "/well/lindgren/UKBIOBANK/DATA/QC/ukb_sqc_v2.txt",
    sample_fam = "/well/lindgren/UKBIOBANK/DATA/WES_200k/ukb23155_c1_b0_v1_s200632.fam", # family and indiviudal IDs
    sample_excl = "/well/lindgren/UKBIOBANK/ferreira/SAMPLE_QC/ukb10844_QCexclIDs_TF_21082020", #General QC - exclusion IDs (created in March 2020 by TF; see hormones project for criteria(, including individuals that withdrew consent as of Aug/2020)
    pcs = "/gpfs3/well/lindgren/UKBIOBANK/nbaya/resources/ukb_40pcs.txt.gz"
)

# conversion tables
sample_conversion <- "/well/lindgren/UKBIOBANK/DATA/WES/bridge_11867_12788.csv" # eid_11867, eid_12788
icd_conversion <- "/well/lindgren/UKBIOBANK/ferreira/convert_disease_codes/icd9_icd10_lkps.txt"

In [19]:
# 
#validate_list_paths <- function(lst){
#    files_found = unlist(lapply(lst, file.exists))
#    paths_not_found = paste0(unlist(lst)[!files_found], collapse = '\n')
#    if (any(!files_found)) stop(paste0('The following paths does not exists:\n',paths_not_found))
#    return(invisible(TRUE))
#}
#
"%nin%" <- function(x, y) !(x %in% y)

In [20]:
#' calculate time since
calc_time_since <- function(time, age_day = lubridate::today(), units = "years", floor = TRUE) {
  the_age = lubridate::interval(time, age_day) / lubridate::duration(num = 1, units = units)
  if (floor) return(as.integer(floor(the_age)))
  return(the_age)
}

In [21]:
#dt = fread(wes$phenotypes, header = TRUE)

#obj <- imp

# how many individuals in the FAM file is in the Pheno file?
#dt <- fread(obj$phenotypes)
#dt_sample_fam <- fread(obj$sample_fam)
#n_found <- sum(dt_sample_fam[[1]] %in% dt$eid)
#n_not_found <- sum(dt_sample_fam[[1]] %nin% dt$eid)
#write(paste('*',n_not_found,'of',n_found,'individuals could not be mapped.'),stdout())

In [22]:
obj <- imp
dt <- fread(obj$phenotypes, nrows = 100)

In [23]:
# setup core feature matrix
dt_sample_fam <- fread(obj$sample_fam)
dt_genetic_eur <- fread(obj$sample_genetic_eur)
dt_sample_qc <- fread(obj$sample_qc)

In [24]:
#dt <- head(d1, n = 100)

In [25]:
colnames(dt) <- gsub('-','.',colnames(dt))
colnames(dt)[colnames(dt) != 'eid'] <- paste0('X', colnames(dt)[colnames(dt) != 'eid'])

In [40]:
## sample level QC and standard phenotypes
# read exclusion samples
# add ID to ukb_sqc_v2.txt using ukb11867_cal_chr1_v2_s488363.fam 
# use ukb_sqc_v2.txt to add submitted gender
# use ukb_sqc_v2.txt to add inferred gender
# use ukb_sqc_v2.txt to add white british ancestry
# tally up current men/women/white british

# add recruitment age
# encode genotyping array using "X22000.0.0"
# encode ukbb.centre using "X54.0.0""
# add PCs using "22009" (with grep?)
# add ID using 'f.eid'

# age encodings (#Year of birth (year 34-0.0, month 52-0.0))
# encode age using "X53.0.0"
# encode age squared using "X53.0.0"
# encode age cubed using "X53.0.0"

## phenotype processing
# open ICD10-ICD9 code bridge file: "/well/lindgren/UKBIOBANK/ferreira/phenotype_extraction/phenotype_lists/ICD10_codes_converted_ICD9_v2v3_codes.txt
# get phenotype data from before
# get primary care data from: "/well/lindgren/UKBIOBANK/DATA/PHENOTYPE/PRIMARY_CARE/gp_clinical.txt"

In [26]:
extract_covars <- function(dt_pheno, dt_sample_qc, keep = 'eid'){
    
    # combine dt and dt_sample_qc
    #keep = c('eid','Submitted.Gender','Inferred.Gender','in.white.British.ancestry.subset')
    remove <- colnames(dt_pheno)[!colnames(dt_pheno) %in% keep]
    dt_sample_qc$eid <- dt_sample_fam$V1
    dt_sample_qc <- dt_sample_qc[,c('eid','Submitted.Gender','Inferred.Gender','in.white.British.ancestry.subset')]
    sum(dt_pheno$eid %in% dt_sample_qc$eid)
    dt <- merge(dt_pheno, dt_sample_qc)

    # get data of birth
    dt$yob <- dt$X34.0.0
    dt$mob <- dt$X52.0.0
    dt$dob <- as.Date(paste0(dt$yob,'-',dt$mob,'-',1))

    # get date of attending recruitment centre
    dt$centre_attend0 <- as.Date(dt$X53.0.0)
    dt$centre_attend1 <- as.Date(dt$X53.1.0)
    dt$centre_attend2 <- as.Date(dt$X53.2.0)

    # get age when attending recruitment centre
    dt$centre_attend_age0 <- calc_time_since(dt$dob, dt$centre_attend0)
    dt$centre_attend_age1 <- calc_time_since(dt$dob, dt$centre_attend1)
    dt$centre_attend_age2 <- calc_time_since(dt$dob, dt$centre_attend2)

    # get age to be used as covariates
    dt$age <- dt$centre_attend_age0
    dt$age1 <- dt$centre_attend_age0^2
    dt$age2 <- dt$centre_attend_age0^3

    # get principal components 
    bool_pc <- grep(22009,colnames(dt))
    n <- length(colnames(dt)[bool_pc])
    colnames(dt)[bool_pc] <- paste0('PC',1:n)

    # negative coding from BiLEVE (recoded 1); positive coding from axiom (recoded 2)
    dt$genotyping.array <- ifelse(dt$X22000.0.0 <0, 1, 2)
    dt$sex = ifelse(dt$Inferred.Gender == "F", 2, ifelse(dt$Inferred.Gender == "M", 1, NA))
    colnames(dt)[colnames(dt) == "X54.0.0"] = "ukbb.centre"
    
    # clean up
    bool_keep <- ! colnames(dt) %in% remove
    dt = dt[,bool_keep, with = FALSE]
    
    return(dt)
}

In [27]:
remove <- colnames(dt)[!colnames(dt) %in% 'eid']
c('age') %in% remove
q <- extract_covars(dt, dt_sample_qc)
q

[1] FALSE

       eid     ukbb.centre PC1       PC2       PC3       PC4       PC5
1      1012978 11005       -14.22390  4.316110 -2.583720  4.110260 13.956500
2      1025876 11003       -10.88470  2.597800 -3.181410 -2.436430 -8.347310
3      1026769 11009       -11.73770  4.467900 -0.870203  0.495115 -2.478190
4      1040495 11013       -11.94830  5.276710  0.114861 -5.288530 -4.577080
5      1052795 11020        -8.21625  3.971510 -1.450520 -9.344880 -5.281080
6      1105858 11009        -8.85043  4.623670  1.649860  2.622890  8.842090
7      1141098 11010       -12.89680  4.037370 -2.344310  2.512150 -6.746900
8      1211428 11021       352.54000 69.735200 -4.430110  4.055590  0.879280
9      1225243 11013        -9.84792  2.461370 -0.705939  2.169720  5.664680
10     1255081 11016       -12.13110  5.434320 -3.680390  1.507940 -4.825730
11     1281914 11007       -11.08030  2.354210 -0.619291 -2.338260 -8.527430
12     1290904 11007       -11.05840  2.885930 -2.670940 -1.061110 -3.197920
13     1439300 11013       -11.19020  2.204540 -2.004280  1.929810 -1.124460
14     1510841 11013       -10.72740  4.897340 -3.208850 -0.444468 -7.031270
15     1564291 11002       -15.40360  1.734290 -1.959970 -0.457922 -3.270680
16     1564609 11003        -9.96050  4.987970 -2.442780  3.901900 -1.985770
17     1630686 11022       -15.93840  4.922750 -1.624950  3.653020  7.511430
18     1688807 11004       -15.03140  3.042700 -2.057590 10.435500 19.405900
19     1704493 11016       -12.54830  3.932520 -3.053840  4.068100  8.599810
20     1724225 11009       -12.26810  3.947030 -0.548870  2.795370 -0.474879
21     1772203 11005       -13.62140  0.409363 -1.633160  1.369360  2.595070
22     1788392 11013       -10.38570  0.420676  1.232360  0.693184 -5.521070
23     1788512 11004       -14.21050  4.423680 -2.253710  2.270660  9.991790
24     1887982 11011       -14.78120  3.803870 -0.937699  1.897190  0.223922
25     1919810 11010       -13.06370  0.282918 -2.388140  4.576730 -2.727280
26     1988386 11014       -12.70830  5.200720 -3.099140  4.239060  8.980980
27     2024530 11002       -11.31900  3.779660 -0.145360  0.497923 -0.436955
28     2040953 11022       -13.08130  5.476190 -1.334590  3.772200  5.327930
29     2137034 11022       -13.73840  1.793800 -2.126300  6.534620  9.085440
30     2169372 11016       -11.87380  3.137930 -2.675540  4.277260  5.737350
<U+22EE> <U+22EE> <U+22EE>    <U+22EE>  <U+22EE>  <U+22EE>  <U+22EE>  <U+22EE>
70     4498097 11020       -12.10040  2.13413  -1.491960  5.425740  10.474600
71     4560868 11016       -12.17060  5.14596  -3.974750  2.731630   4.502700
72     4646821 11013       -10.79110  3.97154  -1.190760 -4.485860  -6.597300
73     4676114 11013       -12.38830  4.65253  -1.523110 -1.930420  -9.429270
74     4747165 11013        -9.88766  3.94416  -0.796497  0.702446   0.808130
75     4853664 11016       -10.52140  5.08040  -2.997150  2.614870   1.243610
76     4945489 11006        -2.00317  7.51690   1.498150  5.484780   7.031090
77     4959009 11018       -11.10390  5.36531  -0.343093  0.494209  -6.474520
78     5064701 11018       -12.79670  4.04766  -2.026760  1.255230  -0.568223
79     5084569 11020       -12.23990  1.85633  -0.787974  2.139760  -2.159130
80     5096620 11011       -10.17950  2.35218  -1.607120  2.060630  -5.289900
81     5133124 11016        -8.84772  1.42126  -1.548560 -3.971640  -4.598410
82     5156720 11009       -11.05320  1.05961  -3.541210  1.113400   0.370002
83     5164095 11011       -12.74830  4.44170  -2.097810  0.523219  -5.518430
84     5201867 11020       -11.79130  1.43651   0.186268 -1.123100  -2.402690
85     5257179 11008       -12.50490  3.01040  -0.921331  0.336038  -2.395780
86     5335711 11007       407.92400 78.46650  -3.837740  5.023460  -2.361650
87     5540364 11011       -10.92280  4.71380   0.653275  1.321140  -3.821580
88     5554974 11014       -14.17450  4.28944   0.846251  3.173240   6.140110
89     5560949 11016       -11.62660  3.89408  -3.320440 -1.124750  -5.323750
90     5579847 11017       -12.77360  3.32529   0.479223 -0.212506  -8.253710
91     5595081 11021       393.33700 73.26830  -5.229740  5.071800   0.335860
92     5636400 11013       -13.89920  4.82472  -2.976010  2.972530  -1.513490
93     5680680 11013       -14.62020  4.75043  -1.211430  0.948968   0.179520
94     5791813 11013       -14.13060  4.72826   0.414764 -3.115740  -7.479660
95     5853624 11010       -11.79710  3.32154  -2.973230  4.948880  -0.902571
96     5908756 11020       -14.37090  4.95458  -5.388210  8.748090  28.512900
97     5923272 11013       -11.93020  2.69665  -3.206340  0.623006 -10.114000
98     5939828 11010       -12.26830  2.63041  -1.648640 -0.210796  -6.569820
99     6016236 11018       -10.44430  5.39256  -0.642781  1.837700  -2.368400
       PC6        PC7        PC8        <U+22EF>   centre_attend1 centre_attend2
1       1.5437400  2.5340200  4.2530500 <U+22EF> <NA>           <NA>
2       0.2943190  1.3257300  1.9210100 <U+22EF> <NA>           <NA>
3      -2.9397400 -2.3961400 -1.5207000 <U+22EF> <NA>           <NA>
4      -2.9125600  5.6781700 -0.6177910 <U+22EF> <NA>           <NA>
5      -0.9078920  2.0279400  1.7880100 <U+22EF> <NA>           <NA>
6      -1.4098900  1.5634800  3.6415500 <U+22EF> <NA>           <NA>
7      -1.0318400 -0.2375480 -3.3133400 <U+22EF> <NA>           <NA>
8       2.5685300 -0.7522970 -0.0639162 <U+22EF> <NA>           <NA>
9       0.7055550  0.3443690 -2.1653300 <U+22EF> <NA>           <NA>
10     -2.1093900  3.0862200 -2.1382000 <U+22EF> <NA>           <NA>
11     -1.7530800  3.2338500  0.6042860 <U+22EF> <NA>           <NA>
12      1.0136300  1.1280700 -3.9898000 <U+22EF> <NA>           <NA>
13     -1.4513200  0.3691910  1.8264000 <U+22EF> <NA>           2016-08-20
14     -0.4197010  0.0351663  1.1992500 <U+22EF> <NA>           <NA>
15      1.6821000  5.4784300  0.2423030 <U+22EF> <NA>           <NA>
16      0.1673190  1.2487700  0.2187050 <U+22EF> <NA>           <NA>
17      0.4150650 -2.2819600 -0.5244300 <U+22EF> <NA>           <NA>
18     -0.3261770 -2.3829300  1.8276700 <U+22EF> <NA>           <NA>
19      0.4505740  2.2720800  2.1233800 <U+22EF> <NA>           <NA>
20      1.9419600 -0.1191290 -1.2778600 <U+22EF> <NA>           <NA>
21      0.9676860  1.2044000 -2.6043900 <U+22EF> <NA>           <NA>
22     -2.8447600  0.8618380 -0.1468440 <U+22EF> <NA>           <NA>
23     -2.4980100 -0.4793410  1.7196300 <U+22EF> <NA>           <NA>
24     -2.1263100 -0.9938410 -1.2905000 <U+22EF> <NA>           <NA>
25      0.0136681 -0.3898450 -1.6727800 <U+22EF> 2012-12-12     <NA>
26     -1.7272900  1.5644900  0.7478340 <U+22EF> <NA>           <NA>
27     -1.5189400  4.1294500 -1.5491600 <U+22EF> <NA>           <NA>
28     -0.0664087  0.6367840 -3.4984800 <U+22EF> <NA>           <NA>
29     -3.0738900  1.7141500 -1.3560700 <U+22EF> <NA>           <NA>
30     -1.0981800 -1.3276700 -1.9031700 <U+22EF> <NA>           <NA>
<U+22EE> <U+22EE>   <U+22EE>   <U+22EE>   <U+22F1> <U+22EE>       <U+22EE>
70      1.3641400 -0.4947890  0.7969200 <U+22EF> <NA>           <NA>
71     -1.9682300  1.5957800  0.8240380 <U+22EF> <NA>           <NA>
72     -0.7114180  1.5787300 -2.3933800 <U+22EF> <NA>           <NA>
73      0.2061940  0.9476580 -0.7244380 <U+22EF> <NA>           <NA>
74     -2.8691500  3.7019600 -1.6771800 <U+22EF> <NA>           <NA>
75      0.8227910  0.1042020 -2.0742200 <U+22EF> <NA>           <NA>
76     -1.6635300 -0.8458900  0.0902504 <U+22EF> <NA>           <NA>
77     -0.1948090 -0.9022210  3.5351100 <U+22EF> <NA>           <NA>
78      2.3574100  3.5808300  0.4410570 <U+22EF> <NA>           <NA>
79     -0.9879940  3.6355500  2.1216100 <U+22EF> <NA>           <NA>
80     -0.8918690  1.8085600 -0.2370910 <U+22EF> <NA>           <NA>
81     -0.1695040 -2.3072400  2.3886200 <U+22EF> <NA>           <NA>
82     -0.3436560 -2.2513900  0.8524660 <U+22EF> <NA>           <NA>
83     -1.4083200 -0.8767850  0.7527520 <U+22EF> <NA>           <NA>
84     -0.0139098  2.8516700  1.8461600 <U+22EF> <NA>           <NA>
85      2.1202600 -2.2553500  0.1165770 <U+22EF> <NA>           <NA>
86     -3.3438300 -3.7686400  3.7045700 <U+22EF> <NA>           <NA>
87      2.4127400  0.5340620  1.8382900 <U+22EF> <NA>           <NA>
88     -3.0627300 -2.5394800 -0.4058940 <U+22EF> <NA>           <NA>
89     -0.2490280  0.1789760  0.6327640 <U+22EF> <NA>           <NA>
90     -1.2510700 -1.5050500  2.1512900 <U+22EF> <NA>           <NA>
91     -0.5579020 -1.0851900 -0.6467060 <U+22EF> <NA>           <NA>
92     -2.4464100 -0.0488565 -2.1317400 <U+22EF> <NA>           <NA>
93      1.6045100 -2.9613700  0.1261050 <U+22EF> <NA>           <NA>
94     -0.7302370  1.4326400 -0.9287560 <U+22EF> <NA>           <NA>
95     -4.1282800  0.3270210 -2.4072500 <U+22EF> <NA>           <NA>
96     -3.3965500 -0.2066060  1.8052100 <U+22EF> <NA>           <NA>
97      0.3052880 -0.2688470 -2.5305900 <U+22EF> <NA>           <NA>
98     -1.1771600  3.4373100 -0.0601241 <U+22EF> <NA>           <NA>
99     -0.2137470 -1.2962000 -1.6531500 <U+22EF> <NA>           <NA>
       centre_attend_age0 centre_attend_age1 centre_attend_age2 age    age1
1      51                 NA                 NA                 51     2601
2      41                 NA                 NA                 41     1681
3      66                 NA                 NA                 66     4356
4      66                 NA                 NA                 66     4356
5      59                 NA                 NA                 59     3481
6      49                 NA                 NA                 49     2401
7      58                 NA                 NA                 58     3364
8      50                 NA                 NA                 50     2500
9      48                 NA                 NA                 48     2304
10     63                 NA                 NA                 63     3969
11     63                 NA                 NA                 63     3969
12     56                 NA                 NA                 56     3136
13     60                 NA                 68                 60     3600
14     46                 NA                 NA                 46     2116
15     65                 NA                 NA                 65     4225
16     50                 NA                 NA                 50     2500
17     53                 NA                 NA                 53     2809
18     53                 NA                 NA                 53     2809
19     62                 NA                 NA                 62     3844
20     59                 NA                 NA                 59     3481
21     49                 NA                 NA                 49     2401
22     66                 NA                 NA                 66     4356
23     49                 NA                 NA                 49     2401
24     66                 NA                 NA                 66     4356
25     66                 69                 NA                 66     4356
26     57                 NA                 NA                 57     3249
27     55                 NA                 NA                 55     3025
28     67                 NA                 NA                 67     4489
29     48                 NA                 NA                 48     2304
30     53                 NA                 NA                 53     2809
<U+22EE> <U+22EE>           <U+22EE>           <U+22EE>           <U+22EE> <U+22EE>
70     59                 NA                 NA                 59     3481
71     46                 NA                 NA                 46     2116
72     49                 NA                 NA                 49     2401
73     47                 NA                 NA                 47     2209
74     63                 NA                 NA                 63     3969
75     58                 NA                 NA                 58     3364
76     61                 NA                 NA                 61     3721
77     69                 NA                 NA                 69     4761
78     44                 NA                 NA                 44     1936
79     57                 NA                 NA                 57     3249
80     66                 NA                 NA                 66     4356
81     46                 NA                 NA                 46     2116
82     64                 NA                 NA                 64     4096
83     63                 NA                 NA                 63     3969
84     63                 NA                 NA                 63     3969
85     57                 NA                 NA                 57     3249
86     66                 NA                 NA                 66     4356
87     60                 NA                 NA                 60     3600
88     53                 NA                 NA                 53     2809
89     62                 NA                 NA                 62     3844
90     63                 NA                 NA                 63     3969
91     43                 NA                 NA                 43     1849
92     67                 NA                 NA                 67     4489
93     43                 NA                 NA                 43     1849
94     64                 NA                 NA                 64     4096
95     67                 NA                 NA                 67     4489
96     66                 NA                 NA                 66     4356
97     65                 NA                 NA                 65     4225
98     41                 NA                 NA                 41     1681
99     66                 NA                 NA                 66     4356
       age2   genotyping.array sex
1      132651 2                2
2       68921 2                2
3      287496 2                2
4      287496 2                1
5      205379 2                1
6      117649 2                2
7      195112 2                2
8      125000 2                1
9      110592 2                2
10     250047 2                2
11     250047 2                2
12     175616 2                2
13     216000 2                2
14      97336 2                2
15     274625 2                1
16     125000 2                1
17     148877 2                1
18     148877 2                1
19     238328 2                2
20     205379 2                2
21     117649 2                1
22     287496 2                2
23     117649 1                1
24     287496 2                2
25     287496 2                1
26     185193 2                1
27     166375 2                2
28     300763 2                2
29     110592 2                2
30     148877 1                1
<U+22EE> <U+22EE> <U+22EE>         <U+22EE>
70     205379 2                1
71      97336 1                2
72     117649 2                1
73     103823 2                2
74     250047 1                2
75     195112 2                1
76     226981 2                1
77     328509 2                2
78      85184 2                1
79     185193 2                2
80     287496 1                1
81      97336 2                1
82     262144 2                1
83     250047 2                2
84     250047 2                1
85     185193 2                2
86     287496 2                2
87     216000 2                1
88     148877 1                2
89     238328 2                1
90     250047 2                1
91      79507 2                2
92     300763 2                2
93      79507 2                2
94     262144 2                2
95     300763 2                1
96     287496 2                1
97     274625 2                2
98      68921 2                2
99     287496 2                2

In [28]:
make_icd_mapping <- function(from, to, icd_path = "/well/lindgren/UKBIOBANK/ferreira/convert_disease_codes/icd9_icd10_lkps.txt"){
    
    # Read icd code
    icd <- fread(icd_path)
    colnames(icd) <- gsub('_code','',colnames(icd))
    stopifnot(c(from,to) %in% colnames(icd))
    
    # Deal with NAs
    icd <- icd[,colnames(icd) %in% c(from, to),with = F]
    icd <- icd[!duplicated(icd)]
    icd[icd==''] <- NA
    icd[icd=='UNDEF'] <- NA
    icd <- icd[!is.na(icd[[from]]), ]
    mapping <- as.list(icd[[to]])
    names(mapping) <- icd[[from]]

    # return function that can do the mapping
    mapper <- function(code){
        map <- mapping[code]
        ids <- names(map)
        is_na <- is.na(ids)
        names(map) <- code
        map[is_na] <- NA
        return(as.character(unlist(map)))
    }
    
    return(mapper)
}

[1] NA                             "Trachea_bronchus_lung_cancer"

In [14]:
# count gender / white british
out_df <- as.data.frame(table(mrg$Inferred.Gender, mrg$in.white.British.ancestry.subset))
colnames(out_df) <- c('sex','wb','count')
out_df

ERROR: Error in table(mrg$Inferred.Gender, mrg$in.white.British.ancestry.subset): object 'mrg' not found

In [ ]:
#dt[['X22000.0.0']]
colnames(dt)[grepl('22000',colnames(dt))]

In [30]:
gp=fread("/well/lindgren/UKBIOBANK/DATA/PHENOTYPE/PRIMARY_CARE/gp_clinical.txt", header=T, sep="\t", nrows = 100)

In [55]:
dt_biomarker <- fread('/gpfs1/well/lindgren/UKBIOBANK/DATA/Biomarker_data/ukb27722.csv', nrows = 1000 )

Warning message in require_bit64_if_needed(ans):
"Some columns are type 'integer64' but package bit64 is not installed. Those columns will print as strange looking floating point data. There is no need to reload the data. Simply install.packages('bit64') to obtain the integer64 print method and print the data again."

Warning message in require_bit64_if_needed(ans):
"Some columns are type 'integer64' but package bit64 is not installed. Those columns will print as strange looking floating point data. There is no need to reload the data. Simply install.packages('bit64') to obtain the integer64 print method and print the data again."

In [104]:
find_data_fields <- function(traits='chrons', by = 'coding_description'){
    
    #m <- fread('../utils/modules/R/ukbtools/extdata/pan_ukbb_manifest_210916.csv')
    stopifnot(by %in% colnames(m))
    
    
    
    lapply(traits, function(tr) m[ m[[by]] == tr,])
    
    
}


find_data_fields()

Warning message in cbind(parts$left, ellip_h, parts$right, deparse.level = 0L):
"number of rows of result is not a multiple of vector length (arg 2)"
Warning message in cbind(parts$left, ellip_h, parts$right, deparse.level = 0L):
"number of rows of result is not a multiple of vector length (arg 2)"
Warning message in cbind(parts$left, ellip_h, parts$right, deparse.level = 0L):
"number of rows of result is not a multiple of vector length (arg 2)"

[[1]]
Empty data.table (0 rows and 48 cols): trait_type,phenocode,pheno_sex,coding,modifier,description...

In [131]:
manifest_search_trait <- function(traits, by = 'coding_description', manifest_file = '/utils/modules/R/ukbtools/extdata/pan_ukbb_manifest_210916.csv'){
    stopifnot(by %in% colnames(m))
    search_matrix <- do.call(rbind, lapply(traits, function(tr) { 
        col = tolower(m[[by]])
        bool_trait = grepl(tr, col)
        bool_not = grepl('not', col)
        m = m[bool_trait & !bool_not,]
        m$search_term = tr
        return(m)
    }))
    return(search_matrix)
}

In [153]:

cancer_manifest <- manifest_search_trait('bladder +cancer')



#field_code_summary

cdt <- data.frame(origin = colnames(dt))
cdt$phenocode <- NA
phenocode_bool <- grepl('X', cdt$origin)
phenocodes <- strsplit( phenocodes[phenocode_bool], split = "X|\\.")
#cdt$phenocode[phenocode_bool] <- 
#phenocodes

# Look for trait we want to investigate
#trait = 'cancer'
#bool = grepl(trait, m$coding_description)
#cur_phenocode = m[bool,]$phenocode
#print(cur_phenocode)


# code.time_of_assesment.number_of_values
#'X20001.0.0'


#dt_bool = colnames(dt) == 'X20001.0.0'
#coding = as.vector(na.omit(dt[,dt_bool, with = F]))

ERROR: Error in strsplit(phenocodes[phenocode_bool], split = "X|\\."): non-character argument

In [69]:
#sum(grepl('30640',colnames(dt_biomarker)))

bool = grepl('1002', colnames(dt))
colnames(dt)[bool]

 [1] "X21002.0.0"  "X21002.1.0"  "X21002.2.0"  "X100200.0.0" "X100200.1.0"
 [6] "X100200.2.0" "X100200.3.0" "X100200.4.0" "X100210.0.0" "X100210.1.0"
[11] "X100210.2.0" "X100210.3.0" "X100210.4.0" "X100220.0.0" "X100220.1.0"
[16] "X100220.2.0" "X100220.3.0" "X100220.4.0" "X100230.0.0" "X100230.1.0"
[21] "X100230.2.0" "X100230.3.0" "X100230.4.0" "X100240.0.0" "X100240.1.0"
[26] "X100240.2.0" "X100240.3.0" "X100240.4.0" "X100250.0.0" "X100250.1.0"
[31] "X100250.2.0" "X100250.3.0" "X100250.4.0" "X100260.0.0" "X100260.1.0"
[36] "X100260.2.0" "X100260.3.0" "X100260.4.0" "X100270.0.0" "X100270.1.0"
[41] "X100270.2.0" "X100270.3.0" "X100270.4.0" "X100280.0.0" "X100280.1.0"
[46] "X100280.2.0" "X100280.3.0" "X100280.4.0" "X100290.0.0" "X100290.1.0"
[51] "X100290.2.0" "X100290.3.0" "X100290.4.0"

In [45]:
icd10 <- make_icd_mapping('ICD10','DESCRIPTION_ICD10')
icd9_icd10 <- make_icd_mapping('ICD9','ICD10')
icd9 <- make_icd_mapping('ICD9','DESCRIPTION_ICD9')

In [33]:
m <- dt
cn <- colnames(m)
bool <- grepl('41202',cn)
print(sum(bool))
m[,bool, with = F]

[1] 380

       X41202.0.0 X41202.0.1 X41202.0.2 X41202.0.3 X41202.0.4 X41202.0.5
1
2      M169
3      N390       N133       K296       K259       D122
4      O049       K660       N946       J329
5      K083
6      H830       K409
7      R001       I48
8      L721
9      R31        R194       N40        K573       N459
10     K137       Z092       K20
11     Z421       Z411       Z349       O680       C502       I500
12     O342
13     M232
14     S5200      S510       M0699      M0690      M069       L405
15     S610       G560
16     S930       H269
17     K297       M2333      M2322
18     S0240      R102       N899       D259
19     M2323      N47        H330
20     G439
21     M232       L82        H521       H251       C445
22     R933       R12        R074       R073       M2324      M2316
23     T840
24     R103       M7667      M7666      K419       H024       D24
25     K409
26
27     C440
28     T432       K625       F432
29
30     N359
<U+22EE> <U+22EE>   <U+22EE>   <U+22EE>   <U+22EE>   <U+22EE>   <U+22EE>
71
72     R040
73     O800       O420
74
75     D168
76
77     S5250      N840       D259       K635
78
79
80     R068       D225
81     K760
82     R073       I841       Z466       C61
83
84     N508       F200       C859       C062       B212
85     I723       I714
86     D509
87     R071       J939
88     Z452       R31        R103       K620       J069       D120
89
90     N816       M201       I471       B028       H160
91     M201       C504
92     Z138       R101       M7989      M7986      M0699      K808
93     N950
94     Z018       Q387       H401       N328       K221
95     R69        N12        H332       H269       K590
96     N200       K359       I251       I200       I080       B07
97     D170
98     I639
99     R074       H950
100
       X41202.0.6 X41202.0.7 X41202.0.8 X41202.0.9 <U+22EF>   X41202.0.370
1                                                  <U+22EF> NA
2                                                  <U+22EF> NA
3                                                  <U+22EF> NA
4                                                  <U+22EF> NA
5                                                  <U+22EF> NA
6                                                  <U+22EF> NA
7                                                  <U+22EF> NA
8                                                  <U+22EF> NA
9                                                  <U+22EF> NA
10                                                 <U+22EF> NA
11     I420                                        <U+22EF> NA
12                                                 <U+22EF> NA
13                                                 <U+22EF> NA
14                                                 <U+22EF> NA
15                                                 <U+22EF> NA
16                                                 <U+22EF> NA
17                                                 <U+22EF> NA
18                                                 <U+22EF> NA
19                                                 <U+22EF> NA
20                                                 <U+22EF> NA
21                                                 <U+22EF> NA
22     K219       I200       M6534                 <U+22EF> NA
23                                                 <U+22EF> NA
24     H251                                        <U+22EF> NA
25                                                 <U+22EF> NA
26                                                 <U+22EF> NA
27                                                 <U+22EF> NA
28                                                 <U+22EF> NA
29                                                 <U+22EF> NA
30                                                 <U+22EF> NA
<U+22EE> <U+22EE>   <U+22EE>   <U+22EE>   <U+22EE>   <U+22F1> <U+22EE>
71                                                 <U+22EF> NA
72                                                 <U+22EF> NA
73                                                 <U+22EF> NA
74                                                 <U+22EF> NA
75                                                 <U+22EF> NA
76                                                 <U+22EF> NA
77                                                 <U+22EF> NA
78                                                 <U+22EF> NA
79                                                 <U+22EF> NA
80                                                 <U+22EF> NA
81                                                 <U+22EF> NA
82                                                 <U+22EF> NA
83                                                 <U+22EF> NA
84                                                 <U+22EF> NA
85                                                 <U+22EF> NA
86                                                 <U+22EF> NA
87                                                 <U+22EF> NA
88     C259                                        <U+22EF> NA
89                                                 <U+22EF> NA
90                                                 <U+22EF> NA
91                                                 <U+22EF> NA
92     K625       G560       D352       K439       <U+22EF> NA
93                                                 <U+22EF> NA
94                                                 <U+22EF> NA
95                                                 <U+22EF> NA
96                                                 <U+22EF> NA
97                                                 <U+22EF> NA
98                                                 <U+22EF> NA
99                                                 <U+22EF> NA
100                                                <U+22EF> NA
       X41202.0.371 X41202.0.372 X41202.0.373 X41202.0.374 X41202.0.375
1      NA           NA           NA           NA           NA
2      NA           NA           NA           NA           NA
3      NA           NA           NA           NA           NA
4      NA           NA           NA           NA           NA
5      NA           NA           NA           NA           NA
6      NA           NA           NA           NA           NA
7      NA           NA           NA           NA           NA
8      NA           NA           NA           NA           NA
9      NA           NA           NA           NA           NA
10     NA           NA           NA           NA           NA
11     NA           NA           NA           NA           NA
12     NA           NA           NA           NA           NA
13     NA           NA           NA           NA           NA
14     NA           NA           NA           NA           NA
15     NA           NA           NA           NA           NA
16     NA           NA           NA           NA           NA
17     NA           NA           NA           NA           NA
18     NA           NA           NA           NA           NA
19     NA           NA           NA           NA           NA
20     NA           NA           NA           NA           NA
21     NA           NA           NA           NA           NA
22     NA           NA           NA           NA           NA
23     NA           NA           NA           NA           NA
24     NA           NA           NA           NA           NA
25     NA           NA           NA           NA           NA
26     NA           NA           NA           NA           NA
27     NA           NA           NA           NA           NA
28     NA           NA           NA           NA           NA
29     NA           NA           NA           NA           NA
30     NA           NA           NA           NA           NA
<U+22EE> <U+22EE>     <U+22EE>     <U+22EE>     <U+22EE>     <U+22EE>
71     NA           NA           NA           NA           NA
72     NA           NA           NA           NA           NA
73     NA           NA           NA           NA           NA
74     NA           NA           NA           NA           NA
75     NA           NA           NA           NA           NA
76     NA           NA           NA           NA           NA
77     NA           NA           NA           NA           NA
78     NA           NA           NA           NA           NA
79     NA           NA           NA           NA           NA
80     NA           NA           NA           NA           NA
81     NA           NA           NA           NA           NA
82     NA           NA           NA           NA           NA
83     NA           NA           NA           NA           NA
84     NA           NA           NA           NA           NA
85     NA           NA           NA           NA           NA
86     NA           NA           NA           NA           NA
87     NA           NA           NA           NA           NA
88     NA           NA           NA           NA           NA
89     NA           NA           NA           NA           NA
90     NA           NA           NA           NA           NA
91     NA           NA           NA           NA           NA
92     NA           NA           NA           NA           NA
93     NA           NA           NA           NA           NA
94     NA           NA           NA           NA           NA
95     NA           NA           NA           NA           NA
96     NA           NA           NA           NA           NA
97     NA           NA           NA           NA           NA
98     NA           NA           NA           NA           NA
99     NA           NA           NA           NA           NA
100    NA           NA           NA           NA           NA
       X41202.0.376 X41202.0.377 X41202.0.378 X41202.0.379
1      NA           NA           NA           NA
2      NA           NA           NA           NA
3      NA           NA           NA           NA
4      NA           NA           NA           NA
5      NA           NA           NA           NA
6      NA           NA           NA           NA
7      NA           NA           NA           NA
8      NA           NA           NA           NA
9      NA           NA           NA           NA
10     NA           NA           NA           NA
11     NA           NA           NA           NA
12     NA           NA           NA           NA
13     NA           NA           NA           NA
14     NA           NA           NA           NA
15     NA           NA           NA           NA
16     NA           NA           NA           NA
17     NA           NA           NA           NA
18     NA           NA           NA           NA
19     NA           NA           NA           NA
20     NA           NA           NA           NA
21     NA           NA           NA           NA
22     NA           NA           NA           NA
23     NA           NA           NA           NA
24     NA           NA           NA           NA
25     NA           NA           NA           NA
26     NA           NA           NA           NA
27     NA           NA           NA           NA
28     NA           NA           NA           NA
29     NA           NA           NA           NA
30     NA           NA           NA           NA
<U+22EE> <U+22EE>     <U+22EE>     <U+22EE>     <U+22EE>
71     NA           NA           NA           NA
72     NA           NA           NA           NA
73     NA           NA           NA           NA
74     NA           NA           NA           NA
75     NA           NA           NA           NA
76     NA           NA           NA           NA
77     NA           NA           NA           NA
78     NA           NA           NA           NA
79     NA           NA           NA           NA
80     NA           NA           NA           NA
81     NA           NA           NA           NA
82     NA           NA           NA           NA
83     NA           NA           NA           NA
84     NA           NA           NA           NA
85     NA           NA           NA           NA
86     NA           NA           NA           NA
87     NA           NA           NA           NA
88     NA           NA           NA           NA
89     NA           NA           NA           NA
90     NA           NA           NA           NA
91     NA           NA           NA           NA
92     NA           NA           NA           NA
93     NA           NA           NA           NA
94     NA           NA           NA           NA
95     NA           NA           NA           NA
96     NA           NA           NA           NA
97     NA           NA           NA           NA
98     NA           NA           NA           NA
99     NA           NA           NA           NA
100    NA           NA           NA           NA

In [54]:
icd10(c('M169','I48','J329'))

[1] "Coxarthrosis, unspecified"      NA
[3] "Chronic sinusitis, unspecified"

In [59]:
#dt_biomarker[,grepl('40006',cn), with = F]

In [113]:
# for each "disease"
# extract ICD10 code
# use dt_biomarker file to extract relevant disease using ICD10 code

test <- fread(icd_conversion)
length(unique(test$ICD10))

[1] 219

In [90]:
disease <- make_icd_mapping('disease','ICD10')

In [101]:
disease('breast_cancer')

[1] "C50"

In [99]:
length(unique(test$disease))
unique(test$disease)

[1] 37

 [1] "colorectal_cancer"
 [2] "Trachea_bronchus_lung_cancer"
 [3] "breast_cancer"
 [4] "hypothalamic_amenorrhea"
 [5] "PCOS"
 [6] "POI"
 [7] "dementia"
 [8] "Alzheimers_disease"
 [9] "depression"
[10] "ADHD"
[11] "renal_failure"
[12] "coronary_artery_disease"
[13] "ischaemic_heart_disease"
[14] "stroke"
[15] "stroke_hemorrhagic"
[16] "ischaemic_stroke"
[17] "chronic_obstructive_pulmonary_disease"
[18] "Crohns_disease"
[19] "IBD"
[20] "Cirrhosis"
[21] "NASH"
[22] "NAFLD"
[23] "psoriais"
[24] "hyperandrogenism"
[25] "hematuria"
[26] "proteinuria"
[27] "acute_renal_failure"
[28] "chronic_kidney_disease"
[29] "male_infertility"
[30] "oligomenorrhea"
[31] "habitual_aborter"
[32] "female_infertility"
[33] "ectopic_pregnancy"
[34] "Preeclampsia"
[35] "GDM"
[36] "intrahepatic_cholestasis_in_pregnancy"
[37] "polycystic_kidney_disease"

In [106]:
'N133' %in% test$V2_code
'N133' %in% test$V2_code
'N133' %in% test$V3_code

[1] FALSE

[1] FALSE

In [30]:
colnames(x)

[1] "ICD9"              "DESCRIPTION_ICD9"  "ICD10"
[4] "DESCRIPTION_ICD10"