In [1]:
setwd('/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb')
library(data.table)

In [2]:
path <- "data/phased/wes_union_calls/200k/shapeit5/phasing_conf/ukb_wes_union_calls_200k_chr21.phasingConf.txt.gz"

In [49]:
d <- fread(path)

In [50]:
d <- d[d$rsid %in% c("chr21:39199148:A:AG","chr21:39199143:TC:T"),]

In [52]:
# how many samples are cis/ch cariers
dtest <- d[d$PP > 0.999,]
tbl <- data.frame(table(dtest$s))
ok_samples <- tbl$Var1[tbl$Freq > 1 ]
dtest <- dtest[dtest$s %in% ok_samples ,]
dfinal <- aggregate(rsid~s, data = dtest, FUN = function(x) paste(x, collapse = ';'))
dfinal

   s       rsid
1  1316330 chr21:39199143:TC:T;chr21:39199148:A:AG
2  1356828 chr21:39199143:TC:T;chr21:39199148:A:AG
3  1410920 chr21:39199143:TC:T;chr21:39199148:A:AG
4  1722462 chr21:39199143:TC:T;chr21:39199148:A:AG
5  1727132 chr21:39199143:TC:T;chr21:39199148:A:AG
6  1844450 chr21:39199143:TC:T;chr21:39199148:A:AG
7  2049962 chr21:39199143:TC:T;chr21:39199148:A:AG
8  2077264 chr21:39199143:TC:T;chr21:39199148:A:AG
9  2243599 chr21:39199143:TC:T;chr21:39199148:A:AG
10 2327611 chr21:39199143:TC:T;chr21:39199148:A:AG
11 2451427 chr21:39199143:TC:T;chr21:39199148:A:AG
12 2513296 chr21:39199143:TC:T;chr21:39199148:A:AG
13 2555927 chr21:39199143:TC:T;chr21:39199148:A:AG
14 2818863 chr21:39199143:TC:T;chr21:39199148:A:AG
15 2830457 chr21:39199143:TC:T;chr21:39199148:A:AG
16 2900498 chr21:39199143:TC:T;chr21:39199148:A:AG
17 2915900 chr21:39199143:TC:T;chr21:39199148:A:AG
18 3078166 chr21:39199143:TC:T;chr21:39199148:A:AG
19 3129810 chr21:39199143:TC:T;chr21:39199148:A:AG
20 3207023 chr21:39199143:TC:T;chr21:39199148:A:AG
21 3280920 chr21:39199143:TC:T;chr21:39199148:A:AG
22 3301823 chr21:39199143:TC:T;chr21:39199148:A:AG
23 3328500 chr21:39199143:TC:T;chr21:39199148:A:AG
24 3436364 chr21:39199143:TC:T;chr21:39199148:A:AG
25 3597856 chr21:39199143:TC:T;chr21:39199148:A:AG
26 3664631 chr21:39199143:TC:T;chr21:39199148:A:AG
27 3744847 chr21:39199143:TC:T;chr21:39199148:A:AG
28 3900856 chr21:39199143:TC:T;chr21:39199148:A:AG
29 3923146 chr21:39199143:TC:T;chr21:39199148:A:AG
30 3924025 chr21:39199143:TC:T;chr21:39199148:A:AG
31 3966896 chr21:39199143:TC:T;chr21:39199148:A:AG
32 4149243 chr21:39199143:TC:T;chr21:39199148:A:AG
33 4231693 chr21:39199143:TC:T;chr21:39199148:A:AG
34 4433460 chr21:39199143:TC:T;chr21:39199148:A:AG
35 4614686 chr21:39199143:TC:T;chr21:39199148:A:AG
36 4650742 chr21:39199143:TC:T;chr21:39199148:A:AG
37 4668535 chr21:39199143:TC:T;chr21:39199148:A:AG
38 4701570 chr21:39199143:TC:T;chr21:39199148:A:AG
39 4920190 chr21:39199143:TC:T;chr21:39199148:A:AG
40 4932140 chr21:39199143:TC:T;chr21:39199148:A:AG
41 4959642 chr21:39199143:TC:T;chr21:39199148:A:AG
42 5000830 chr21:39199143:TC:T;chr21:39199148:A:AG
43 5097755 chr21:39199143:TC:T;chr21:39199148:A:AG
44 5137788 chr21:39199143:TC:T;chr21:39199148:A:AG
45 5180059 chr21:39199143:TC:T;chr21:39199148:A:AG
46 5302247 chr21:39199143:TC:T;chr21:39199148:A:AG
47 5792743 chr21:39199143:TC:T;chr21:39199148:A:AG
48 5962072 chr21:39199143:TC:T;chr21:39199148:A:AG
49 5970916 chr21:39199143:TC:T;chr21:39199148:A:AG
50 6006379 chr21:39199143:TC:T;chr21:39199148:A:AG

In [17]:
d[d$s %in% tbl$Var1,]

ERROR: Error: $ operator is invalid for atomic vectors

In [2]:
d_ac <- fread("data/conditional/rare/combined/ukb_eur_wes_200k_chr15_maf0to5e-2_pLoF_damaging_missense_AC.txt.gz")
d_hash <- fread("data/conditional/rare/combined/ukb_eur_wes_200k_chr15_maf0to5e-2_pLoF_damaging_missense_hash.txt.gz")

In [ ]:
markers <- fread()

In [11]:
#vcf_path <- "data/conditional/rare/combined/ukb_eur_wes_200k_chr15_maf0to5e-2_pLoF_damaging_missense.vcf.bgz"
#cmd <- paste("zcat",vcf_path,"| grep -v '##' | cut -f3")
#d <- fread(cmd = cmd)

In [18]:
phenotype <- "BC_combined_primary_care"

In [41]:
vcf_markers <- d$ID[grepl("chr",d$ID)]
ac_markers <- d_ac$id[d_ac[[phenotype]] >= 4]

In [42]:
markers <- intersect(vcf_markers, ac_markers)

In [43]:
d_hash_subset <- d_hash[d_hash$id %in% markers,]
dups <- duplicated(d_hash_subset[[phenotype]])
d_hash_subset <- d_hash_subset[!dups, ]
hash_markers <- d_hash_subset$id

In [46]:
final_markers <- intersect(markers, hash_markers)

In [51]:
ord <- order(final_markers)

In [54]:
head(final_markers[ord]); head(final_markers)

[1] "chr15:100048888:G:A"  "chr15:100051578:C:T"  "chr15:100096364:C:CG"
[4] "chr15:100096382:C:T"  "chr15:100096467:A:G"  "chr15:100109000:C:T"

[1] "chr15:22883001:A:T" "chr15:22909192:A:G" "chr15:22943171:A:T"
[4] "chr15:22944890:C:T" "chr15:23004107:C:A" "chr15:23009944:C:T"

In [56]:
lst <- lapply(strsplit(final_markers, split = ':'), function(x) as.numeric(x[2]))

In [67]:
ac <- d_ac[[phenotype]][d_ac$id %in% final_markers]

In [68]:
all(ac == round(ac))

[1] TRUE

In [69]:
length(final_markers)

[1] 6775

In [3]:
m <- fread("data/mt/vep/ukb_eur_wes_200k_csqs_chr15.tsv.gz")

In [5]:
args <- list(
    p_cutoff = 5e-3,
    phenotype = "CC_combined",
    vep_path_with_CHR = "data/mt/vep/ukb_eur_wes_200k_csqs_chrCHR.tsv.gz",
    in_spa_file = "data/saige/output/binary/step2/min_mac4/ukb_eur_wes_200k_maf0to5e-2_CC_combined_pLoF_damaging_missense_locoprs.txt.gz"
)

In [10]:
stopifnot(file.exists(args$in_spa_file))
spa <- fread(args$in_spa_file)
spa_n <- nrow(spa)

# test P-value
p_cutoff <- as.numeric(args$p_cutoff)
stopifnot(p_cutoff > 0 && p_cutoff < 1)
spa <- spa[spa$p.value < p_cutoff,]
write("Note: using standard column $p.value to check cutoff", stderr())

# only continue if something is significant
if (nrow(spa) > 0){
    
    lst <- list()
    # iterate over each row and recover variants for the gene
    #lst <- lapply(1:nrow(spa), function(row_idx){
    for (row_idx in 1:nrow(spa))
    
    
        row <- spa[row_idx,]
        gene <- row$MarkerID
        chrom <- row$CHR

        # read in vep
        vep_path <- gsub("chrCHR", chrom, args$vep_path_with_CHR)
        stopifnot(file.exists(vep_path))
        print(row_idx)
        
        if (vep_path != vep_path_old){
            print(vep_path)
            vep <<- fread(vep_path)
        }
        
        # save old VEP path as global
        vep_path_old <<- vep_path

        # filter to genes in that are significant
        vep_subset <- vep[vep$csqs.gene_id %in% gene,]
        vep_subset <- vep_subset[,c("varid","csqs.gene_id","consequence_category")]
        colnames(vep_subset) <- c('rsid',"ensembl_gene_id","consequence_category")
        return(vep_subset)
    
    })
    
    # combine variants for phenotype
    d <- do.call(rbind, lst)
    d$phenotype <- args$phenotype
    
    stopifnot(nrow(d) > 0)
    
    # write file
    outfile = paste0(args$out_prefix, '.tsv.gz')
    write(paste("writing to", outfile), stderr())
    #fwrite(out, outfile, sep = '\t')
    
}

[1] 1
[1] "data/mt/vep/ukb_eur_wes_200k_csqs_chr1.tsv.gz"
[1] 2
[1] "data/mt/vep/ukb_eur_wes_200k_csqs_chr2.tsv.gz"
[1] 3
[1] "data/mt/vep/ukb_eur_wes_200k_csqs_chr4.tsv.gz"
[1] 4
[1] "data/mt/vep/ukb_eur_wes_200k_csqs_chr7.tsv.gz"
[1] 5
[1] 6
[1] "data/mt/vep/ukb_eur_wes_200k_csqs_chr12.tsv.gz"
[1] 7
[1] "data/mt/vep/ukb_eur_wes_200k_csqs_chr18.tsv.gz"
[1] 8
[1] "data/mt/vep/ukb_eur_wes_200k_csqs_chr19.tsv.gz"

In [18]:
d[d$consequence_category %in% c('pLoF',"damaging_missense"),]

       rsid                     ensembl_gene_id consequence_category
1      chr1:45329315:TG:T       ENSG00000132781 pLoF
2      chr1:45329439:T:C        ENSG00000132781 pLoF
3      chr1:45330515:C:A        ENSG00000132781 pLoF
4      chr1:45330551:G:A        ENSG00000132781 damaging_missense
5      chr1:45330557:C:A        ENSG00000132781 damaging_missense
6      chr1:45331175:GTAGTGCC:G ENSG00000132781 pLoF
7      chr1:45331193:C:T        ENSG00000132781 damaging_missense
8      chr1:45331196:TG:T       ENSG00000132781 pLoF
9      chr1:45331228:G:A        ENSG00000132781 damaging_missense
10     chr1:45331301:A:T        ENSG00000132781 damaging_missense
11     chr1:45331327:T:C        ENSG00000132781 damaging_missense
12     chr1:45331421:TC:T       ENSG00000132781 pLoF
13     chr1:45331462:C:T        ENSG00000132781 pLoF
14     chr1:45331472:A:G        ENSG00000132781 damaging_missense
15     chr1:45331476:C:A        ENSG00000132781 pLoF
16     chr1:45331514:T:TCC      ENSG00000132781 pLoF
17     chr1:45331529:G:A        ENSG00000132781 damaging_missense
18     chr1:45331542:G:T        ENSG00000132781 damaging_missense
19     chr1:45331556:C:T        ENSG00000132781 damaging_missense
20     chr1:45331558:T:C        ENSG00000132781 pLoF
21     chr1:45331699:AG:A       ENSG00000132781 pLoF
22     chr1:45331744:C:G        ENSG00000132781 damaging_missense
23     chr1:45331745:T:C        ENSG00000132781 damaging_missense
24     chr1:45331745:TG:T       ENSG00000132781 pLoF
25     chr1:45331757:G:A        ENSG00000132781 damaging_missense
26     chr1:45331771:G:A        ENSG00000132781 damaging_missense
27     chr1:45331772:G:T        ENSG00000132781 damaging_missense
28     chr1:45331835:G:A        ENSG00000132781 pLoF
29     chr1:45332080:G:A        ENSG00000132781 pLoF
30     chr1:45332164:ACT:A      ENSG00000132781 pLoF
<U+22EE> <U+22EE>                 <U+22EE>        <U+22EE>
1421   chr18:2954542:C:T        ENSG00000101577 damaging_missense
1422   chr18:2954547:T:A        ENSG00000101577 damaging_missense
1423   chr18:2954592:A:G        ENSG00000101577 damaging_missense
1424   chr18:2960650:A:G        ENSG00000101577 damaging_missense
1425   chr18:2960681:T:C        ENSG00000101577 damaging_missense
1426   chr18:2960689:C:T        ENSG00000101577 damaging_missense
1427   chr18:2960704:G:A        ENSG00000101577 damaging_missense
1428   chr18:2960713:T:C        ENSG00000101577 damaging_missense
1429   chr18:2960720:C:G        ENSG00000101577 damaging_missense
1430   chr18:2960738:C:T        ENSG00000101577 damaging_missense
1431   chr18:2960770:T:C        ENSG00000101577 damaging_missense
1432   chr18:2960785:T:C        ENSG00000101577 damaging_missense
1433   chr18:2960801:T:A        ENSG00000101577 damaging_missense
1434   chr18:2960831:CA:C       ENSG00000101577 pLoF
1435   chr18:2960840:T:C        ENSG00000101577 damaging_missense
1436   chr19:41677492:G:A       ENSG00000007306 pLoF
1437   chr19:41683784:C:T       ENSG00000007306 pLoF
1438   chr19:41683802:AC:A      ENSG00000007306 pLoF
1439   chr19:41683974:G:A       ENSG00000007306 pLoF
1440   chr19:41684046:AG:A      ENSG00000007306 pLoF
1441   chr19:41684065:T:A       ENSG00000007306 pLoF
1442   chr19:41684065:T:C       ENSG00000007306 pLoF
1443   chr19:41686991:G:A       ENSG00000007306 pLoF
1444   chr19:41687016:AT:A      ENSG00000007306 pLoF
1445   chr19:41687026:CTT:C     ENSG00000007306 pLoF
1446   chr19:41687045:CT:C      ENSG00000007306 pLoF
1447   chr19:41687215:A:AG      ENSG00000007306 pLoF
1448   chr19:41688101:C:A       ENSG00000007306 pLoF
1449   chr19:41688114:GC:G      ENSG00000007306 pLoF
1450   chr19:41688139:G:C       ENSG00000007306 pLoF
       phenotype
1      CC_combined
2      CC_combined
3      CC_combined
4      CC_combined
5      CC_combined
6      CC_combined
7      CC_combined
8      CC_combined
9      CC_combined
10     CC_combined
11     CC_combined
12     CC_combined
13     CC_combined
14     CC_combined
15     CC_combined
16     CC_combined
17     CC_combined
18     CC_combined
19     CC_combined
20     CC_combined
21     CC_combined
22     CC_combined
23     CC_combined
24     CC_combined
25     CC_combined
26     CC_combined
27     CC_combined
28     CC_combined
29     CC_combined
30     CC_combined
<U+22EE> <U+22EE>
1421   CC_combined
1422   CC_combined
1423   CC_combined
1424   CC_combined
1425   CC_combined
1426   CC_combined
1427   CC_combined
1428   CC_combined
1429   CC_combined
1430   CC_combined
1431   CC_combined
1432   CC_combined
1433   CC_combined
1434   CC_combined
1435   CC_combined
1436   CC_combined
1437   CC_combined
1438   CC_combined
1439   CC_combined
1440   CC_combined
1441   CC_combined
1442   CC_combined
1443   CC_combined
1444   CC_combined
1445   CC_combined
1446   CC_combined
1447   CC_combined
1448   CC_combined
1449   CC_combined
1450   CC_combined

In [144]:
nrow(vep)

[1] 657618

In [126]:
d <- do.call(rbind, lst)

  locus         alleles    rsid info.AC info.AF    info.AN MAF        MAC
1 chr1:45329315 ["TG","T"] NA   1       2.8263e-06 353822  2.8263e-06 1
2 chr1:45329316 ["G","A"]  NA   1       2.8263e-06 353822  2.8263e-06 1
3 chr1:45329318 ["A","T"]  NA   1       2.8262e-06 353830  2.8262e-06 1
4 chr1:45329319 ["C","G"]  NA   2       5.6524e-06 353830  5.6524e-06 2
5 chr1:45329321 ["G","A"]  NA   1       2.8262e-06 353828  2.8262e-06 1
6 chr1:45329330 ["G","A"]  NA   3       8.4786e-06 353830  8.4786e-06 3
  varid              csqs.allele_num <U+22EF>   csqs.swissprot csqs.transcript_id
1 chr1:45329315:TG:T 1               <U+22EF> NA             ENST00000372098
2 chr1:45329316:G:A  1               <U+22EF> NA             ENST00000372098
3 chr1:45329318:A:T  1               <U+22EF> NA             ENST00000372098
4 chr1:45329319:C:G  1               <U+22EF> NA             ENST00000372098
5 chr1:45329321:G:A  1               <U+22EF> NA             ENST00000372098
6 chr1:45329330:G:A  1               <U+22EF> NA             ENST00000372098
  csqs.trembl csqs.uniparc csqs.variant_allele csqs.revel_score csqs.cadd_phred
1 NA          NA           -                      NA                NA
2 NA          NA           A                   0.113             1.466
3 NA          NA           T                   0.131            14.660
4 NA          NA           G                   0.103             2.431
5 NA          NA           A                      NA                NA
6 NA          NA           A                      NA                NA
  csqs.most_severe_consequence csqs.csq_score consequence_category
1 frameshift_variant           -496.0         pLoF
2 missense_variant               10.9         other_missense
3 missense_variant               10.9         other_missense
4 missense_variant               10.9         other_missense
5 synonymous_variant             17.0         synonymous
6 synonymous_variant             17.0         synonymous

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8

In [19]:
markers_by_gene <- "data/conditional/rare/combined/genes/min_mac4//ukb_eur_wes_200k_maf0to5e-2_CC_combined_primary_care_pLoF_damaging_missense.txt.gz"

In [ ]:
filter_to_selected_genes <- function(markers_by_gene, chrom, phenotype, csqs = c("pLoF", "damaging_missense")){
    
    # get table of markers by genes
    d <- markers_by_gene
    
    # check columns
    stopifnot("rsid" %in% colnames(d))
    stopifnot("phenotype" %in% colnames(d))
    stopifnot("consequence_category" %in% colnames(d))
    
    # generate columns of chromosomes and ensure integrity
    d$chr <- unlist(lapply(d$rsid, function(x) unlist(strsplit(x, split = ':'))[1]))
    autosomes <- paste0("chr",1:22)
    stopifnot(d_gene$chr %in% autosomes)

    # perform subsetting
    d <- d[d$chr %in% chrom,]
    d <- d[d$phenotype %in% phenotype,]
    d <- d[d$consequence_category %in% csqs,]
    n_genes <- length(unique(d$ensembl_gene_id))
    n_gene_markers <- length(markers)

    msg <- paste("Note: Subsetting to", n_gene_markers, "markers near", n_genes, "relevant gene(s) on", chromosome)
    write(msg, stderr())
    
    
}

In [71]:
  print(args)

  stopifnot(file.exists(args$path_markers))
  stopifnot(file.exists(args$path_ac_by_phenotypes))
  stopifnot(file.exists(args$path_hash_by_phenotypes))
  

  chromosome <- args$chromosome
  phenotype <- args$phenotype
  min_mac <- as.numeric(args$min_mac)

  
  d_phenos <- fread(args$path_ac_by_phenotypes)
  d_hash <- fread(args$path_hash_by_phenotypes)
  d_marker <- fread(args$path_markers)

  ### check how many total variants available ###
  n_start <- nrow(d_marker)
  msg <- paste0("Markers available: ", n_start)
  write(msg, stderr())

  ### filter by markers near "causal" genes ###

  stopifnot("rsid" %in% colnames(d_gene))
  stopifnot("phenotype" %in% colnames(d_gene))
  stopifnot("consequence_category" %in% colnames(d_gene))

  d_gene$chr <- unlist(lapply(d_gene$rsid, function(x) unlist(strsplit(x, split = ':'))[1]))
  autosomes <- paste0("chr",1:22)
  stopifnot(d_gene$chr %in% autosomes)

  # perform subsetting
  d_gene <- d_gene[d_gene$chr %in% chromosome,]
  d_gene <- d_gene[d_gene$phenotype %in% phenotype,]
  d_gene <- d_gene[d_gene$consequence_category %in% c("pLoF", "damaging_missense"),]
  markers <- intersect(d_marker$rsid, d_gene$rsid)
  n_genes <- length(unique(d_gene$ensembl_gene_id))
  n_gene_markers <- length(markers)

  msg <- paste("Note: Subsetting to", n_gene_markers, "markers near", n_genes, "relevant gene(s) on", chromosome)
  write(msg, stderr())

  ### filter by allele count ###

  # check integrity of phenotype
  stopifnot(phenotype %in% colnames(d_phenos))
  stopifnot("id" %in% colnames(d_phenos))
  stopifnot(min_mac >= 0)
  cols <- c("id", phenotype)

  # perform subset
  d_phenos <- d_phenos[,cols, with = FALSE]
  d_phenos <- d_phenos[ d_phenos[[phenotype]] >=  min_mac,]
  if (nrow(d_phenos) == 0) stop(paste0("No variants left after filtering on min_mac>=",min_mac))

  # check integrity of marker file
  stopifnot("consequence_category" %in% colnames(d_marker))
  stopifnot("rsid" %in% colnames(d_marker))

  # check how many annotations are present
  annotation <- unlist(strsplit(args$annotation, split = ','))
  annotation_found <- unlist(lapply(annotation, function(x) x %in% d_marker$consequence_category))
  if (sum(annotation_found) == 0) stop(paste("annotation", args$annotation, "was/were not in the data?"))
  if (sum(annotation_found) != length(annotation_found)) warning("Some csqs categories were not found!")

  # subset markers
  d_marker <- d_marker[d_marker$consequence_category %in% annotation,]
  if (nrow(d_marker) == 0) stop(paste0("No variants left after filtering by ", args$annotation))

  # combine the two files into a set of final variants
  markers <- intersect(markers, d_phenos$id)
  n_ac_markers <- length(markers)
  msg <- paste("Note: Subsetting from",n_gene_markers,"to", n_ac_markers, "marker(s) using AC >=",min_mac, "for", phenotype)
  write(msg, stderr())

  ### filter by perfect LD ###

  # Prune markers in perfect LD
  stopifnot("id" %in% colnames(d_hash))
  d_hash <- d_hash[,cols, with = FALSE]
  d_hash <- d_hash[d_hash$id %in% markers, ]
  in_perfect_ld <- duplicated(d_hash[[phenotype]])
  d_hash <- d_hash[!in_perfect_ld, ]

  # ensure that only overlapping markers are kept
  markers <- intersect(markers, d_hash$id)
  n_ld_markers <- length(markers)
  msg <- paste("Note: Subsetting from", n_ac_markers, "to", n_ld_markers, "marker(s) beacuse of perfect LD for", phenotype)
  write(msg, stderr())

  if (length(markers) > 0) {
    # ensure variants follow input formatting required by saige
    markers <- gwastools::order_markers(markers)
    fwrite(data.table(x=markers), args$outfile, row.names = FALSE, col.names = FALSE)
  } else {
    write("No markers present after subsetting", stderr())
  }

  locus       alleles   rsid info.AC info.AF    info.AN MAF        MAC
1 chr8:240846 ["T","C"] NA   1       2.8311e-06 353224  2.8311e-06 1
2 chr8:240846 ["T","C"] NA   1       2.8311e-06 353224  2.8311e-06 1
3 chr8:240849 ["T","C"] NA   1       2.8294e-06 353430  2.8294e-06 1
4 chr8:240849 ["T","C"] NA   1       2.8294e-06 353430  2.8294e-06 1
5 chr8:240850 ["G","C"] NA   1       2.8302e-06 353330  2.8302e-06 1
6 chr8:240850 ["G","C"] NA   1       2.8302e-06 353330  2.8302e-06 1
  varid           csqs.allele_num <U+22EF>   csqs.swissprot csqs.transcript_id
1 chr8:240846:T:C 1               <U+22EF> NA             ENST00000398612
2 chr8:240846:T:C 1               <U+22EF> NA             ENST00000610248
3 chr8:240849:T:C 1               <U+22EF> NA             ENST00000398612
4 chr8:240849:T:C 1               <U+22EF> NA             ENST00000610248
5 chr8:240850:G:C 1               <U+22EF> NA             ENST00000398612
6 chr8:240850:G:C 1               <U+22EF> NA             ENST00000610248
  csqs.trembl csqs.uniparc csqs.variant_allele csqs.revel_score csqs.cadd_phred
1 NA          NA           C                   NA               NA
2 NA          NA           C                   NA               NA
3 NA          NA           C                   NA               NA
4 NA          NA           C                   NA               NA
5 NA          NA           C                   NA               NA
6 NA          NA           C                   NA               NA
  csqs.most_severe_consequence csqs.csq_score consequence_category
1 5_prime_UTR_variant          20             non_coding
2 downstream_gene_variant      29             non_coding
3 5_prime_UTR_variant          20             non_coding
4 downstream_gene_variant      29             non_coding
5 5_prime_UTR_variant          20             non_coding
6 downstream_gene_variant      29             non_coding

In [23]:
d <- fread("data/saige/output/binary/step2_common_cond/min_mac4/ukb_eur_wes_200k_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.txt.gz")

ERROR: Error in `[.data.table`(d, , col_pvalue): j (the 2nd argument inside [...]) is a single symbol but column name 'col_pvalue' is not found. Perhaps you intended DT[, ..col_pvalue]. This difference to data.frame is deliberate and explained in FAQ 1.1.

In [ ]:
main <- function(args){

    print(args)
    stopifnot(dir.exists(args$spa_cts_dir))
    stopifnot(dir.exists(args$spa_bin_dir))

    spa_cts_files <- list.files(args$spa_cts_dir, pattern = ".txt.gz", full.names = TRUE)
    spa_bin_files <- list.files(args$spa_bin_dir, pattern = ".txt.gz", full.names = TRUE)

    # read in all the SPA step 2 results
    spa_cts_full <- rbindlist(lapply(spa_cts_files, fread_with_basename))
    spa_bin_full <- rbindlist(lapply(spa_bin_files, fread_with_basename))
    write("Loaded all cts/binary files..", stdout())

    print(head(spa_cts_full, n=2))
    print(head(spa_bin_full, n=2))

    # combine and subset
    cols <- c("CHR","MarkerID","basename", "p.value", "Tstat", "p.value_c", "Tstat_c")
    spa_full <- rbindlist(list(spa_cts_full, spa_bin_full))
    spa_full <- spa_full[,cols]
    n <- nrow(spa_full)
    
    # use conditional P-value when available
    cond_p_avail <- !is.na(spa_full$p.value_c)
    cond_tstat_avail <- !is.na(spa_full$p.value_c)
    
    
    lapply(1:n, function(row_idx) {
        
        pval <- spa_full$p.value[row_idx]
        pval_cond <- spa_full$p.value_c[row_idx]
        
        if(is.na())
        
        
    })
    
    
    # format to avoid scientific notation
    spa_full$p.value <- format(spa_full$p.value, scientific = FALSE)
    spa_full$Tstat <- format(spa_full$Tstat, scientific = FALSE)
    out_prefix_true_p <- paste0(args$out_prefix, "_true_p.tsv.gz")
    fwrite(spa_full, out_prefix_true_p, sep = '\t', quote = FALSE)
    write(paste("Note: wrote", out_prefix_true_p),stderr())

    # write out genes and chromosomes used
    spa_genes <- spa_full[,c("MarkerID","CHR")]
    spa_genes <- spa_genes[!duplicated(spa_genes),]
    out_prefix_genes <- paste0(args$out_prefix, "_genes.tsv.gz")
    fwrite(spa_genes, out_prefix_genes, sep = '\t')
    write(paste("Note: wrote", out_prefix_genes),stderr())

}