In [7]:
setwd("/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb")
library(data.table)

In [17]:
samples <- fread("data/phenotypes/filtered_phenotypes_cts.tsv.gz")

In [19]:
samples <- samples$eid[samples$genetic.eur.no.fin.oct2021]

In [8]:
fs <- list.files('data/knockouts/alt/', pattern = "pLoF_damaging_missense.tsv.gz", full.names = TRUE)

In [9]:
fread(fs[1])

       gene_id         s       gts
1      ENSG00000014919 1107208 ["1|0","0|1"]
2      ENSG00000014919 1355462 ["1|0","0|1"]
3      ENSG00000014919 5601762 ["0|1","1|0"]
4      ENSG00000015171 3184983 ["0/1","0/1"]
5      ENSG00000023839 1360575 ["0|1","1|0"]
6      ENSG00000023839 1793277 ["1|0","0|1"]
7      ENSG00000023839 2074594 ["0/1","0|1"]
8      ENSG00000023839 2195560 ["0|1","1|0"]
9      ENSG00000023839 2451353 ["0|1","1|0"]
10     ENSG00000023839 2481548 ["1|0","0|1"]
11     ENSG00000023839 2602922 ["1|0","0|1"]
12     ENSG00000023839 2875630 ["0|1","1|0","0|1"]
13     ENSG00000023839 2882352 ["1|1"]
14     ENSG00000023839 2925261 ["0|1","0|1","1|0"]
15     ENSG00000023839 2954167 ["1|0","0|1"]
16     ENSG00000023839 3296497 ["1|0","0|1"]
17     ENSG00000023839 3307301 ["1|1"]
18     ENSG00000023839 3606271 ["1|0","0|1"]
19     ENSG00000023839 3714037 ["1|0","0|1"]
20     ENSG00000023839 3720759 ["0|1","1|0"]
21     ENSG00000023839 3957484 ["0|1","1|0"]
22     ENSG00000023839 4123780 ["0|1","1|0"]
23     ENSG00000023839 4566655 ["1|1"]
24     ENSG00000023839 4586206 ["0|1","1|0"]
25     ENSG00000023839 4617752 ["0|1","1|0"]
26     ENSG00000023839 4627786 ["1|0","0|1"]
27     ENSG00000023839 4903550 ["0|1","0/1"]
28     ENSG00000023839 4927815 ["0|1","1|0"]
29     ENSG00000023839 5237901 ["0|1","1|0"]
30     ENSG00000023839 5289620 ["0|1","1|0"]
<U+22EE> <U+22EE>        <U+22EE> <U+22EE>
760    ENSG00000225830 2539143 ["1|1"]
761    ENSG00000225830 2561706 ["1|0","0|1"]
762    ENSG00000225830 3170316 ["1|0","0|1"]
763    ENSG00000225830 3276084 ["1|0","0|1"]
764    ENSG00000225830 3347134 ["1|1"]
765    ENSG00000225830 3358603 ["0|1","1|0"]
766    ENSG00000225830 3598187 ["0|1","1|0"]
767    ENSG00000225830 3627053 ["1|0","0|1"]
768    ENSG00000225830 3878172 ["1|0","0|1"]
769    ENSG00000225830 3918426 ["0/1","0/1"]
770    ENSG00000225830 3966363 ["1|0","0|1"]
771    ENSG00000225830 4042163 ["1|0","0|1"]
772    ENSG00000225830 4552648 ["0/1","0/1"]
773    ENSG00000225830 4611017 ["0|1","1|0"]
774    ENSG00000225830 4617787 ["0|1","1|0"]
775    ENSG00000225830 4842025 ["1|1"]
776    ENSG00000225830 4986656 ["1|1"]
777    ENSG00000225830 5261769 ["0/1","0/1"]
778    ENSG00000225830 5367272 ["1|0","0|1"]
779    ENSG00000225830 5940284 ["0|1","1|0"]
780    ENSG00000229544 3357510 ["1|0","0|1"]
781    ENSG00000235376 1129531 ["1|1"]
782    ENSG00000235376 2028949 ["1|1"]
783    ENSG00000235376 2809183 ["1|1"]
784    ENSG00000235376 2960636 ["1|1"]
785    ENSG00000235376 3332784 ["1|1"]
786    ENSG00000235376 4073268 ["1|1"]
787    ENSG00000235376 5347966 ["1|1"]
788    ENSG00000241935 1044794 ["0/1","0/1"]
789    ENSG00000283496 1803257 ["0|1","1|0"]
       varid
1      ["chr10:99727030:C:T","chr10:99729614:G:A"]
2      ["chr10:99716369:CAG:C","chr10:99727454:G:A"]
3      ["chr10:99714667:C:T","chr10:99727030:C:T"]
4      ["chr10:242069:T:TC","chr10:242070:G:T"]
5      ["chr10:99800532:G:A","chr10:99805400:A:G"]
6      ["chr10:99805400:A:G","chr10:99832069:C:T"]
7      ["chr10:99807474:C:T","chr10:99836218:G:T"]
8      ["chr10:99805400:A:G","chr10:99842000:C:A"]
9      ["chr10:99805400:A:G","chr10:99831809:G:A"]
10     ["chr10:99805400:A:G","chr10:99830715:G:T"]
11     ["chr10:99805400:A:G","chr10:99832069:C:T"]
12     ["chr10:99807439:G:A","chr10:99832083:A:AT","chr10:99832112:T:C"]
13     ["chr10:99805400:A:G"]
14     ["chr10:99807439:G:A","chr10:99832112:T:C","chr10:99836218:G:T"]
15     ["chr10:99805400:A:G","chr10:99832109:G:A"]
16     ["chr10:99805400:A:G","chr10:99834419:C:T"]
17     ["chr10:99805400:A:G"]
18     ["chr10:99805400:A:G","chr10:99817461:G:C"]
19     ["chr10:99805400:A:G","chr10:99836127:C:A"]
20     ["chr10:99836218:G:T","chr10:99851521:G:A"]
21     ["chr10:99805400:A:G","chr10:99832108:C:T"]
22     ["chr10:99805400:A:G","chr10:99832069:C:T"]
23     ["chr10:99805400:A:G"]
24     ["chr10:99805400:A:G","chr10:99842000:C:A"]
25     ["chr10:99831735:G:T","chr10:99834393:T:C"]
26     ["chr10:99805400:A:G","chr10:99834419:C:T"]
27     ["chr10:99805400:A:G","chr10:99831824:GC:G"]
28     ["chr10:99832109:G:A","chr10:99844350:C:T"]
29     ["chr10:99805400:A:G","chr10:99834419:C:A"]
30     ["chr10:99804153:T:G","chr10:99805400:A:G"]
<U+22EE> <U+22EE>
760    ["chr10:49472376:C:T"]
761    ["chr10:49458867:T:A","chr10:49472376:C:T"]
762    ["chr10:49472376:C:T","chr10:49482860:G:A"]
763    ["chr10:49472376:C:T","chr10:49472467:G:A"]
764    ["chr10:49482860:G:A"]
765    ["chr10:49472376:C:T","chr10:49482860:G:A"]
766    ["chr10:49461529:T:G","chr10:49482860:G:A"]
767    ["chr10:49458897:C:T","chr10:49472997:G:A"]
768    ["chr10:49472376:C:T","chr10:49472997:G:A"]
769    ["chr10:49472930:C:A","chr10:49472931:C:T"]
770    ["chr10:49473007:G:C","chr10:49493118:T:A"]
771    ["chr10:49472376:C:T","chr10:49482689:G:A"]
772    ["chr10:49476213:ACC:A","chr10:49476216:TGCATCTC:T"]
773    ["chr10:49472376:C:T","chr10:49472997:G:A"]
774    ["chr10:49472997:G:A","chr10:49474085:A:G"]
775    ["chr10:49472376:C:T"]
776    ["chr10:49472376:C:T"]
777    ["chr10:49500586:A:G","chr10:49500589:A:G"]
778    ["chr10:49472376:C:T","chr10:49493118:T:A"]
779    ["chr10:49472376:C:T","chr10:49482860:G:A"]
780    ["chr10:124447809:T:C","chr10:124449932:C:T"]
781    ["chr10:103246174:C:T"]
782    ["chr10:103246174:C:T"]
783    ["chr10:103246174:C:T"]
784    ["chr10:103246174:C:T"]
785    ["chr10:103246174:C:T"]
786    ["chr10:103246174:C:T"]
787    ["chr10:103246174:C:T"]
788    ["chr10:97611552:GA:G","chr10:97611554:CTGGTTTGGCTA:C"]
789    ["chr10:133309421:A:C","chr10:133309873:T:C"]
       hom_alt_n phased.a1 phased.a2 unphased.n pKO
1      0         1         1         0          1.0
2      0         1         1         0          1.0
3      0         1         1         0          1.0
4      0         0         0         2          0.5
5      0         1         1         0          1.0
6      0         1         1         0          1.0
7      0         0         1         1          0.5
8      0         1         1         0          1.0
9      0         1         1         0          1.0
10     0         1         1         0          1.0
11     0         1         1         0          1.0
12     0         1         2         0          1.0
13     1         0         0         0          1.0
14     0         1         2         0          1.0
15     0         1         1         0          1.0
16     0         1         1         0          1.0
17     1         0         0         0          1.0
18     0         1         1         0          1.0
19     0         1         1         0          1.0
20     0         1         1         0          1.0
21     0         1         1         0          1.0
22     0         1         1         0          1.0
23     1         0         0         0          1.0
24     0         1         1         0          1.0
25     0         1         1         0          1.0
26     0         1         1         0          1.0
27     0         0         1         1          0.5
28     0         1         1         0          1.0
29     0         1         1         0          1.0
30     0         1         1         0          1.0
<U+22EE> <U+22EE>  <U+22EE>  <U+22EE>  <U+22EE>   <U+22EE>
760    1         0         0         0          1.0
761    0         1         1         0          1.0
762    0         1         1         0          1.0
763    0         1         1         0          1.0
764    1         0         0         0          1.0
765    0         1         1         0          1.0
766    0         1         1         0          1.0
767    0         1         1         0          1.0
768    0         1         1         0          1.0
769    0         0         0         2          0.5
770    0         1         1         0          1.0
771    0         1         1         0          1.0
772    0         0         0         2          0.5
773    0         1         1         0          1.0
774    0         1         1         0          1.0
775    1         0         0         0          1.0
776    1         0         0         0          1.0
777    0         0         0         2          0.5
778    0         1         1         0          1.0
779    0         1         1         0          1.0
780    0         1         1         0          1.0
781    1         0         0         0          1.0
782    1         0         0         0          1.0
783    1         0         0         0          1.0
784    1         0         0         0          1.0
785    1         0         0         0          1.0
786    1         0         0         0          1.0
787    1         0         0         0          1.0
788    0         0         0         2          0.5
789    0         1         1         0          1.0
       knockout
1      Compound heterozygote
2      Compound heterozygote
3      Compound heterozygote
4      Possible Compound heterozygote
5      Compound heterozygote
6      Compound heterozygote
7      Possible Compound heterozygote
8      Compound heterozygote
9      Compound heterozygote
10     Compound heterozygote
11     Compound heterozygote
12     Compound heterozygote
13     Homozygote
14     Compound heterozygote
15     Compound heterozygote
16     Compound heterozygote
17     Homozygote
18     Compound heterozygote
19     Compound heterozygote
20     Compound heterozygote
21     Compound heterozygote
22     Compound heterozygote
23     Homozygote
24     Compound heterozygote
25     Compound heterozygote
26     Compound heterozygote
27     Possible Compound heterozygote
28     Compound heterozygote
29     Compound heterozygote
30     Compound heterozygote
<U+22EE> <U+22EE>
760    Homozygote
761    Compound heterozygote
762    Compound heterozygote
763    Compound heterozygote
764    Homozygote
765    Compound heterozygote
766    Compound heterozygote
767    Compound heterozygote
768    Compound heterozygote
769    Possible Compound heterozygote
770    Compound heterozygote
771    Compound heterozygote
772    Possible Compound heterozygote
773    Compound heterozygote
774    Compound heterozygote
775    Homozygote
776    Homozygote
777    Possible Compound heterozygote
778    Compound heterozygote
779    Compound heterozygote
780    Compound heterozygote
781    Homozygote
782    Homozygote
783    Homozygote
784    Homozygote
785    Homozygote
786    Homozygote
787    Homozygote
788    Possible Compound heterozygote
789    Compound heterozygote

In [46]:
read_ko <- function(f){
    d <- fread(f)
    d <- d[,c(2,1,9,10), with = FALSE]
    d <- d[d$s %in% samples]
    in_genes <- unique(d$gene_id)
    in_samples <- unique(d$s)
    out_samples <- samples[!samples %in% in_samples]
    grid <- expand.grid(out_samples, in_genes)
    colnames(grid) <- c("s","gene_id")
    grid$pKO <- 0
    grid$knockout <- NA
    mrg <- rbind(d, grid)
    return(mrg)
}

In [53]:
for (f in fs){
    d <- read_ko(f)
    chrom <- stringr::str_extract(f, "chr[0-9]+")
    print(chrom)
    genes <- unique(d$gene_id)
    thedir <- paste0("data/survival/knockouts/eur_no_fin/pLoF_damaging_missense/",chrom)
    dir.create(thedir)
    for (g in genes){
        d_gene <- d[d$gene_id %in% g,]
        if (sum(d_gene$pKO) >= 4){
            outfile = paste0(thedir,"/",g,".txt.gz")
            fwrite(d_gene, outfile, sep = '\t', quote = FALSE)
        }
    }
}

[1] "chr10"
[1] "chr11"
[1] "chr12"
[1] "chr13"
[1] "chr14"
[1] "chr15"
[1] "chr16"
[1] "chr17"
[1] "chr18"
[1] "chr19"
[1] "chr1"
[1] "chr20"
[1] "chr21"
[1] "chr22"
[1] "chr2"
[1] "chr3"
[1] "chr4"
[1] "chr5"
[1] "chr6"
[1] "chr7"
[1] "chr8"
[1] "chr9"

In [48]:
outfile

[1] "data/survival/knockouts/eur_no_fin/chr10/ENSG00000014919.txt.gz"

In [52]:
d_gene

       s       gene_id         pKO    knockout
1      1856209 ENSG00000166788 0.5    Possible Compound heterozygote
2      4748374 ENSG00000166788 1.0    Compound heterozygote
3      1000028 ENSG00000166788 0.0    NA
4      1000034 ENSG00000166788 0.0    NA
5      1000087 ENSG00000166788 0.0    NA
6      1000118 ENSG00000166788 0.0    NA
7      1000120 ENSG00000166788 0.0    NA
8      1000162 ENSG00000166788 0.0    NA
9      1000171 ENSG00000166788 0.0    NA
10     1000196 ENSG00000166788 0.0    NA
11     1000254 ENSG00000166788 0.0    NA
12     1000278 ENSG00000166788 0.0    NA
13     1000297 ENSG00000166788 0.0    NA
14     1000302 ENSG00000166788 0.0    NA
15     1000329 ENSG00000166788 0.0    NA
16     1000337 ENSG00000166788 0.0    NA
17     1000341 ENSG00000166788 0.0    NA
18     1000353 ENSG00000166788 0.0    NA
19     1000370 ENSG00000166788 0.0    NA
20     1000406 ENSG00000166788 0.0    NA
21     1000427 ENSG00000166788 0.0    NA
22     1000465 ENSG00000166788 0.0    NA
23     1000473 ENSG00000166788 0.0    NA
24     1000488 ENSG00000166788 0.0    NA
25     1000508 ENSG00000166788 0.0    NA
26     1000566 ENSG00000166788 0.0    NA
27     1000579 ENSG00000166788 0.0    NA
28     1000582 ENSG00000166788 0.0    NA
29     1000600 ENSG00000166788 0.0    NA
30     1000617 ENSG00000166788 0.0    NA
<U+22EE> <U+22EE> <U+22EE>        <U+22EE> <U+22EE>
175006 6025692 ENSG00000166788 0      NA
175007 6025720 ENSG00000166788 0      NA
175008 6025812 ENSG00000166788 0      NA
175009 6025864 ENSG00000166788 0      NA
175010 6025898 ENSG00000166788 0      NA
175011 6025901 ENSG00000166788 0      NA
175012 6025913 ENSG00000166788 0      NA
175013 6025938 ENSG00000166788 0      NA
175014 6025942 ENSG00000166788 0      NA
175015 6025967 ENSG00000166788 0      NA
175016 6025980 ENSG00000166788 0      NA
175017 6025999 ENSG00000166788 0      NA
175018 6026004 ENSG00000166788 0      NA
175019 6026018 ENSG00000166788 0      NA
175020 6026020 ENSG00000166788 0      NA
175021 6026128 ENSG00000166788 0      NA
175022 6026152 ENSG00000166788 0      NA
175023 6026187 ENSG00000166788 0      NA
175024 6026202 ENSG00000166788 0      NA
175025 6026229 ENSG00000166788 0      NA
175026 6026237 ENSG00000166788 0      NA
175027 6026268 ENSG00000166788 0      NA
175028 6026270 ENSG00000166788 0      NA
175029 6026295 ENSG00000166788 0      NA
175030 6026311 ENSG00000166788 0      NA
175031 6026322 ENSG00000166788 0      NA
175032 6026335 ENSG00000166788 0      NA
175033 6026383 ENSG00000166788 0      NA
175034 6026397 ENSG00000166788 0      NA
175035 6026401 ENSG00000166788 0      NA