In [1]:
setwd("/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb")
library(data.table)
library(digest)

In [2]:
args <- list(
    in_vcf="data/conditional/rare/combined/ukb_eur_wes_200k_chr21_maf0to5e-2_pLoF_damaging_missense.vcf.bgz",
    out_prefix="data/conditional/rare/combined/ukb_eur_wes_200k_chr21_maf0to5e-2_pLoF_damaging_missense_ld_BC_combined_primary_care",
    phenotype="BC_combined_primary_care",
    pheno_file="data/phenotypes/curated_covar_phenotypes_binary_200k.tsv",
    covariates="data/phenotypes/covars1.csv"
)

In [3]:
gsub_to_dosage <- function(gt){
    gt <- gsub("\\|", "\\\\", gt)
    gt <- gsub("0/1", "1", gt)
    gt <- gsub("1/0", "1", gt)
    gt <- gsub("0/0", "0", gt)
    gt <- gsub("1/1", "2", gt)
    return(gt)
}

hash_genotypes <- function(G, algo = "xxhash32"){
    require(digest)
    gt_string <- unlist(apply(G, 1, function(x) as.character(paste(x, collapse = '-'))))
    dosage_string <- gsub_to_dosage(gt_string)
    the_hash <- unlist(lapply(dosage_string, function(x) digest(x, algo=algo)))
    return(the_hash)
}

In [4]:
stopifnot(file.exists(args$in_vcf))
stopifnot(file.exists(args$pheno_file))
stopifnot(file.exists(args$covariates))
stopifnot(dir.exists(dirname(args$out_prefix)))

In [29]:
lines <- 7089
lines_per_chunk <- 1000
chunks <- ceiling(lines / lines_per_chunk)

[1] 8

In [31]:
header_cmd <- cmd <- paste0("zcat ", args$in_vcf, " | grep '#CHR' ")
header <- fread(cmd = header_cmd, header = FALSE)
header <- as.character(t(header)[,1])

    [1] "#CHROM"  "POS"     "ID"      "REF"     "ALT"     "QUAL"    "FILTER"
    [8] "INFO"    "FORMAT"  "1705888" "3544034" "1065590" "1130642" "1237482"
   [15] "2351928" "3310264" "5800421" "3708144" "1728817" "1663370" "1116994"
   [22] "5254480" "2469141" "3099220" "1944907" "1759153" "2654239" "4290321"
   [29] "5746106" "5622376" "4282759" "2459760" "5223469" "4015841" "1233880"
   [36] "1056021" "2251532" "3999334" "4791741" "2839607" "5201370" "2891431"
   [43] "2428518" "2566462" "1204799" "2556278" "5123554" "2008606" "5465675"
   [50] "3997469" "3161144" "1547561" "2480913" "3313152" "1185247" "5204183"
   [57] "2731723" "4749899" "1314648" "1795433" "1942376" "4110487" "5767264"
   [64] "3999627" "3214056" "3556035" "1418092" "4785067" "2759451" "4849039"
   [71] "4046434" "5867275" "2862267" "2603624" "3398040" "4118210" "5944693"
   [78] "1337856" "3019362" "5295624" "2630554" "5029846" "4906545" "1970243"
   [85] "2237845" "5043109" "4624166" "1824199" "5125842" "4659790" "1911540"
   [92] "4670967" "3967443" "3166988" "1371232" "1301095" "5459352" "1532409"
   [99] "1661364" "4375686" "4880350" "1208529" "3854622" "4311257" "3453817"
  [106] "3879171" "5602611" "2724793" "5114706" "2962037" "4930708" "3511932"
  [113] "5432264" "4626529" "3274212" "6017705" "3235064" "2667735" "4125528"
  [120] "4263821" "2380441" "4750642" "2891054" "3824851" "3670917" "2067341"
  [127] "3053001" "5708521" "1340372" "1666963" "5546257" "1912963" "4725959"
  [134] "2450143" "1006685" "4803161" "3609162" "4555669" "4497348" "4281245"
  [141] "5041328" "4396795" "5555593" "4159474" "4265939" "1298172" "3627163"
  [148] "3580010" "5366456" "4049423" "1430841" "2771666" "4558728" "5084174"
  [155] "4610447" "4985299" "4057246" "3547740" "3727934" "3828066" "1544351"
  [162] "3738340" "2180415" "4953165" "2225545" "3962383" "1234576" "2144121"
  [169] "3896268" "4216690" "2441099" "3795825" "1559743" "3194107" "3820998"
  [176] "2941159" "2463648" "5021502" "4628813" "4056692" "3317068" "4779253"
  [183] "4874169" "3849378" "2129083" "4589876" "4041291" "1458307" "4605300"
  [190] "2724157" "1131087" "3096118" "1110070" "4293464" "1602765" "1197384"
  [197] "1327244" "3465033" "1393091" "2910267" "1290889" "1021041" "5950288"
  [204] "2324481" "4534519" "3420695" "1417504" "2562318" "4908345" "4190707"
  [211] "1195214" "2984992" "4775473" "2098099" "2472940" "2452657" "1679456"
  [218] "2038893" "2950645" "3834757" "3243051" "3266420" "4840030" "3227951"
  [225] "4528900" "2641063" "2879817" "4900656" "4341176" "2455313" "5677299"
  [232] "1063365" "1360779" "3765737" "3285932" "3020679" "4695609" "5441587"
  [239] "3475054" "5357848" "4491712" "2114726" "5066484" "3017459" "5109269"
  [246] "3344471" "5390647" "1483458" "4062737" "2335843" "6017640" "3793747"
  [253] "5587095" "2828558" "5028033" "3426959" "4136501" "3904739" "2645247"
  [260] "4633627" "5358812" "5036815" "3578426" "1623753" "3425087" "4629250"
  [267] "3105349" "1462714" "2507249" "3909385" "5978987" "1231386" "4826446"
  [274] "4415015" "2178766" "3354431" "1176524" "2073460" "4547249" "2874206"
  [281] "3157507" "2185708" "3092496" "2167796" "3636902" "4057316" "2506774"
  [288] "4139905" "5080226" "4914850" "4886583" "3670358" "1020702" "5961853"
  [295] "1460192" "4498121" "5309471" "2690552" "5163060" "2092402" "2662896"
  [302] "4403121" "2829488" "3225181" "1016284" "2913800" "3362540" "3298771"
  [309] "1417681" "3684769" "2914313" "3785957" "2089723" "5450712" "3887195"
  [316] "1900610" "1469717" "4050453" "3885014" "1205179" "2648307" "1090536"
  [323] "2608866" "1768082" "5402693" "5289659" "4334295" "2408378" "4050632"
  [330] "5091947" "3886741" "1568289" "3402117" "2848891" "1143552" "3500469"
  [337] "4934305" "5391936" "4306527" "1618686" "4883920" "1996819" "3762792"
  [344] "5593422" "5005971" "4653415" "3232692" "5951448" "2087555" "5996400"
  [351] "4805846" "2699563" "5638110" "3347561" "3839860" "2530045" "4430346"
  [358] "1887663" "1944666" "5051507" "2824785" "1377192" "3353436" "3025893"
  [365] "2476506" "2706117" "4174098" "2774116" "2057543" "5790881" "2432210"
  [372] "5246413" "1088622" "5169091" "5845983" "1957867" "5300386" "4858783"
  [379] "1220011" "1106939" "4377353" "4817156" "2207841" "4088869" "1023463"
  [386] "4757228" "5933115" "4358412" "4090862" "3135974" "4822413" "4005190"
  [393] "1581887" "5927845" "3527437" "3482927" "2099033" "2830408" "1443209"
  [400] "2205609" "1900854" "4130646" "4648295" "2372630" "4818860" "1496660"
  [407] "2419054" "2045720" "1336578" "4086157" "2191518" "4630021" "3513829"
  [414] "5795526" "3323477" "1550730" "4329379" "1715534" "1673688" "4414410"
  [421] "4505453" "5359048" "3080029" "1397304" "4951514" "3021574" "3955777"
  [428] "1602336" "3963691" "2733352" "4903157" "5441612" "4342465" "2378483"
  [435] "3825122" "5330125" "3879010" "2301849" "3557623" "3303820" "1899891"
  [442] "3651437" "5459627" "4761339" "4453899" "3242302" "2853296" "2050655"
  [449] "2657801" "1608284" "3089358" "4038844" "2971328" "5330292" "2195938"
  [456] "1356803" "2317265" "5552847" "5329175" "5704553" "2844406" "2883658"
  [463] "1126513" "1722349" "1217174" "4011368" "5043976" "3384677" "3366982"
  [470] "1853145" "1292576" "2903951" "5953077" "1571744" "6008586" "5970263"
  [477] "2598345" "2247216" "5372778" "4249956" "3237056" "2255825" "2573044"
  [484] "5127528" "4828400" "5047786" "4871137" "3819747" "3218171" "5312144"
  [491] "2368104" "2240497" "1638508" "2712581" "4378561" "4190488" "2525762"
  [498] "5692671" "1543866" "5069497" "4257919" "1136307" "4118678" "4060697"
  [505] "2364691" "3484087" "3561403" "2994918" "3014743" "5750870" "2671101"
  [512] "4658946" "6010199" "2881464" "5096590" "2875688" "2283087" "2326497"
  [519] "3192214" "1784601" "5046875" "5978730" "5747668" "2601845" "1957986"
  [526] "3805783" "2716020" "4830388" "2920049" "4045220" "4662268" "4136866"
  [533] "5898863" "2871852" "1834241" "2249715" "4084427" "3538310" "4981901"
  [540] "3659439" "3117528" "3118025" "5184368" "4709418" "5374890" "5844773"
  [547] "5783776" "1680493" "3699411" "3214929" "2114162" "3103526" "4081481"
  [554] "4110647" "4595673" "5962312" "2665474" "5213423" "1794129" "3022568"
  [561] "5700444" "3909752" "1693335" "2257214" "2805143" "3359284" "3691176"
  [568] "5712195" "4309593" "2810257" "5027449" "5076924" "1159301" "3926431"
  [575] "3550273" "5473267" "4784357" "3199159" "4012360" "4093969" "4327541"
  [582] "2100040" "4150556" "1834397" "4326413" "1321742" "2888422" "3026669"
  [589] "1149511" "5294272" "2778362" "1749036" "1574039" "5712622" "5317916"
  [596] "4438151" "1992738" "3456535" "3372777" "5733213" "4272519" "2796512"
  [603] "5432189" "1184851" "5446867" "4416839" "3227667" "5188165" "4258414"
  [610] "1381950" "1251684" "5660027" "5971547" "1635061" "2228694" "3758483"
  [617] "5020093" "2026256" "3684415" "2049996" "5768596" "3802800" "4074256"
  [624] "5444626" "1318089" "3351027" "2994861" "4571772" "2771786" "5897976"
  [631] "2963453" "4917484" "2077978" "2740242" "1565244" "5396838" "2262196"
  [638] "4892936" "2799215" "4372064" "4592935" "4168035" "1207317" "4042208"
  [645] "5538700" "2268046" "1758599" "5531935" "2780779" "2203174" "5756943"
  [652] "2890437" "5475695" "1907745" "1032441" "5728426" "5601762" "3197072"
  [659] "5668170" "1239405" "3975166" "1949787" "4830123" "5936227" "1205108"
  [666] "4603321" "3693073" "2310111" "2402012" "5911191" "2335163" "4256927"
  [673] "1934323" "5630267" "1745757" "5582902" "1928306" "1686377" "2315661"
  [680] "4780472" "2560743" "4552515" "3365772" "5059851" "4979821" "1316610"
  [687] "3820147" "5332767" "4446503" "4155842" "1193405" "2543301" "1749225"
  [694] "1065172" "4300220" "2221965" "1385526" "3733480" "3664548" "4734275"
  [701] "5415209" "1908602" "3842072" "1184640" "3122623" "2069327" "1510853"
  [708] "3381364" "4759280" "4068662" "3510132" "3649213" "3740275" "3846848"
  [715] "2995645" "1502408" "1839973" "1651133" "2435783" "3311716" "5876537"
  [722] "3426412" "3176696" "4055650" "4403826" "5250594" "5698987" "4620422"
  [729] "4776767" "1201657" "5337311" "1980958" "2778097" "1432462" "5010853"
  [736] "5662676" "1092570" "4074339" "1738267" "5260017" "1315660" "3014152"
  [743] "4738384" "4733220" "4651330" "1293516" "2984060" "5710142" "5054261"
  [750] "4827933" "2351204" "1762509" "1382378" "4552211" "3832866" "5523183"
  [757] "3273551" "1654432" "3643219" "3868635" "3838110" "4924323" "2837962"
  [764] "4466117" "1337028" "4371638" "3399011" "4002092" "1957557" "5051715"
  [771] "5665248" "2229811" "5878763" "2577744" "4209086" "4793786" "5974650"
  [778] "3072632" "1809990" "2729723" "4224974" "2044142" "5730159" "1295176"
  [785] "2370278" "4778290" "3075297" "1503082" "4807355" "5294466" "1047617"
  [792] "2151849" "2761427" "4965454" "1460869" "4183451" "4918954" "2577986"
  [799] "2947153" "2928549" "2166222" "5829616" "1362793" "1083018" "6016832"
  [806] "1886987" "2300369" "5090726" "1621490" "5607397" "4662712" "1887256"
  [813] "2797829" "3643793" "2148883" "1579106" "2803892" "2341768" "2236348"
  [820] "3176618" "3245809" "4294978" "3271710" "5542501" "5137574" "4816611"
  [827] "1617700" "3750010" "4375528" "5329163" "2218996" "5776630" "3608065"
  [834] "2512228" "3442942" "1181824" "2378753" "2146315" "3917289" "5993855"
  [841] "2979073" "2817641" "5565205" "3354035" "5650704" "3383943" "1877028"
  [848] "1795258" "2433324" "3913707" "1357285" "4919508" "2986443" "4693409"
  [855] "5164037" "5620707" "3317843" "3876204" "5045571" "3394103" "5811224"
  [862] "2206970" "3774758" "4470702" "2672067" "3269472" "5346991" "1877842"
  [869] "2356459" "2482624" "2415218" "3587115" "4635171" "2625368" "3609118"
  [876] "1092482" "4734897" "5995015" "4955160" "5663806" "5356138" "4826961"
  [883] "1004721" "4723989" "5447208" "3481727" "2731563" "1190957" "5899227"
  [890] "4769725" "5867420" "1317006" "3709213" "3617508" "5241735" "4440440"
  [897] "5675524" "5740614" "3855687" "2652135" "3273799" "1377398" "1897549"
  [904] "4321416" "4338094" "1529420" "2403184" "1272747" "3813008" "5195321"
  [911] "1531676" "1806245" "1616731" "5492199" "3253548" "4456712" "4870368"
  [918] "4445434" "2193370" "1778118" "2462659" "5047865" "4633190" "5555640"
  [925] "4110092" "2831196" "1434940" "3421633" "5167468" "2145196" "1997103"
  [932] "4322922" "1362937" "5123511" "5772197" "2147023" "5219880" "4509277"
  [939] "1413320" "5068680" "3998299" "2708094" "2823359" "3058400" "2750592"
  [946] "1540265" "1579061" "1893123" "2797014" "5879647" "5317968" "2898383"
  [953] "5137637" "4202194" "4381736" "4841180" "1428516" "2572501" "3498594"
  [960] "1576924" "2881565" "2562097" "2986592" "5388951" "4721463" "1163163"
  [967] "3599485" "2842083" "3443845" "1891732" "4885008" "5499104" "2248406"
  [974] "2585103" "5466601" "4857286" "5865706" "1182489" "2968446" "1573953"
  [981] "3935838" "5891750" "2763521" "5878758" "5645449" "3957852" "1992697"
  [988] "5996980" "5028892" "1547401" "3484813" "2279484" "1494844" "4660680"
  [995] "2620602" "4990879" "1935038" "3303478" "2964085" "5073080" "4110581"
 [1002] "1163877" "2687469" "3517432" "3785994" "2294401" "2939511" "1888088"
 [1009] "4971773" "4518957" "3331447" "4917876" "5991734" "6025455" "2932177"
 [1016] "1662030" "5971746" "5348006" "2131638" "4163794" "4946467" "5475407"
 [1023] "3284704" "4267605" "3795838" "4279962" "3613609" "4347765" "3274380"
 [1030] "3257489" "2712092" "5687683" "4753042" "4086543" "4910918" "1766870"
 [1037] "5643215" "4786000" "1516211" "5788313" "3510606" "2567313" "4879745"
 [1044] "5468899" "4834545" "4303980" "3906277" "3207650" "3071445" "3013441"
 [1051] "1192285" "1294812" "5488401" "1694966" "1172507" "2029702" "5287047"
 [1058] "1914458" "3300059" "2248899" "5694552" "3029688" "4325688" "1787230"
 [1065] "5575822" "5056379" "2670148" "5577730" "5621308" "4423474" "4685200"
 [1072] "3035225" "3258506" "1054649" "1693944" "2594393" "2234029" "2883339"
 [1079] "5237877" "5517466" "2786977" "5541601" "2268988" "2532144" "1405604"
 [1086] "4511372" "3167346" "3163976" "3054039" "3039469" "1738783" "1344479"
 [1093] "5350304" "3484337" "3062671" "4399280" "1475252" "4485147" "2590293"
 [1100] "3364756" "5014940" "5374150" "1017482" "2886895" "4870838" "1927199"
 [1107] "4244661" "1225978" "3709024" "2527482" "5722193" "2190521" "4066271"
 [1114] "3366979" "3846450" "1359174" "5397898" "4262242" "3384227" "3701790"
 [1121] "4807005" "3368890" "5996665" "1828490" "4348674" "5976062" "5401561"
 [1128] "4727342" "4459405" "2821793" "4572664" "2056212" "1686130" "5392968"
 [1135] "5281279" "2587242" "1453305" "3232041" "4299717" "5797933" "4778854"
 [1142] "3106114" "4197447" "1537256" "5143644" "5426818" "4562275" "3744446"
 [1149] "2607791" "3404770" "1141247" "5565659" "2151268" "3473679" "4609601"
 [1156] "5370765" "3595591" "1389114" "2500393" "5091611" "5110482" "5915970"
 [1163] "3559853" "2755798" "5724167" "3297007" "5439683" "4460052" "2077148"
 [1170] "2520179" "4596128" "2345656" "1370394" "4869313" "2808701" "2410087"
 [1177] "4120915" "3901153" "4355482" "3582522" "2920469" "5459119" "4348011"
 [1184] "5678532" "3718558" "4557146" "5042141" "1326884" "1329371" "4437816"
 [1191] "5135263" "3460464" "4984669" "4261428" "5312126" "3572685" "1955031"
 [1198] "2519740" "4346299" "3054629" "1346141" "3101963" "2099268" "4158984"
 [1205] "5057057" "4483771" "5737968" "5039636" "5385822" "1796437" "1081576"
 [1212] "4969550" "5151236" "2036540" "5056635" "4622592" "3313705" "5885964"
 [1219] "4992305" "1562617" "3014216" "4510849" "4887726" "5222283" "2108395"
 [1226] "1943055" "5974057" "4484537" "4756411" "2133697" "1501389" "1650642"
 [1233] "2983489" "5810165" "4769170" "1082496" "3734994" "6009311" "5361201"
 [1240] "1167650" "2706487" "5760615" "2915332" "2086584" "1641166" "4601738"
 [1247] "3086495" "1104658" "1009826" "2497812" "1958608" "2734601" "3004841"
 [1254] "4007890" "3887918" "2747370" "4686069" "1017930" "2311342" "1589756"
 [1261] "3465963" "3293761" "4465317" "4429903" "3827314" "2135698" "5052048"
 [1268] "1708909" "2571139" "2648199" "3160847" "3854551" "1715332" "5487297"
 [1275] "5849437" "1948896" "2061680" "2818083" "4040594" "4979535" "5177436"
 [1282] "3412524" "1732819" "5397877" "5506491" "2376221" "3312108" "4248061"
 [1289] "2675217" "3267264" "1932515" "4842263" "3631749" "4454993" "2897120"
 [1296] "5707031" "4231693" "4865165" "1747774" "1049194" "1486121" "3104044"
 [1303] "4098120" "3436982" "3182361" "3807640" "5796741" "4745739" "3674902"
 [1310] "2469573" "2502061" "3261792" "3948888" "2488791" "3094644" "4610157"
 [1317] "4735690" "2883994" "1446777" "2180097" "5821833" "3703275" "2373783"
 [1324] "1361961" "4577149" "5129134" "2422112" "4376029" "2258447" "1986724"
 [1331] "3207066" "3194037" "2481517" "3058812" "4329195" "2367191" "2429424"
 [1338] "3080037" "1603725" "1633670" "2885668" "2771346" "4611619" "1422582"
 [1345] "1501934" "2835014" "1387514" "2457184" "3401274" "1876294" "3281140"
 [1352] "4159110" "3446659" "5515310" "1750157" "4383680" "1262780" "5588044"
 [1359] "3375532" "1574475" "5417156" "5572069" "4539835" "1660748" "1010902"
 [1366] "1264835" "6005353" "5287851" "5247992" "3139291" "5667886" "5859697"
 [1373] "2024565" "5269755" "2110608" "4648360" "5858426" "2802373" "4539365"
 [1380] "5601279" "1322144" "2867167" "2413299" "1457388" "1080155" "5905973"
 [1387] "4373063" "5809880" "1895250" "1670233" "1276428" "2681751" "2304394"
 [1394] "3875657" "3744023" "2472722" "1509282" "2773954" "5627365" "4021239"
 [1401] "5567549" "5757560" "4918212" "1283228" "4143389" "2068944" "3039731"
 [1408] "5379830" "3374513" "5726865" "4625201" "1314406" "1053457" "4694329"
 [1415] "4479662" "5160081" "4602704" "5855812" "5356605" "5907901" "4951153"
 [1422] "4544875" "3272542" "1079859" "4066021" "5951328" "2713899" "5923927"
 [1429] "2561296" "3132014" "5377057" "1963752" "2654526" "2169154" "3867068"
 [1436] "3420879" "1406409" "4420239" "3060226" "3083731" "2777109" "4672185"
 [1443] "2664606" "1744602" "1204366" "5299631" "1184615" "2076166" "2701683"
 [1450] "5729701" "4552531" "2302353" "3279941" "3450994" "2963339" "5589556"
 [1457] "3441195" "1082244" "3391464" "5635101" "2340829" "2963810" "2514610"
 [1464] "3514269" "5914195" "2578322" "5077611" "5014735" "4899986" "2937853"
 [1471] "1766671" "5128388" "4825100" "3180663" "5020596" "2480999" "4028929"
 [1478] "2825442" "4569348" "5550063" "2164658" "1753867" "5950409" "2310879"
 [1485] "1249419" "2006993" "5884248" "1713767" "3683144" "3822597" "2652629"
 [1492] "5641491" "4135360" "1731407" "1104312" "1354210" "3865139" "5800836"
 [1499] "2917302" "5316445" "5122256" "4169031" "2050775" "4170479" "4147548"
 [1506] "5974008" "2599845" "1204026" "2801332" "5731592" "2393674" "5923807"
 [1513] "1953506" "4412866" "2707001" "2233164" "1419758" "4247051" "3493788"
 [1520] "4064282" "3874821" "1976147" "2763447" "4770160" "4653601" "4230832"
 [1527] "5613332" "1427259" "1914556" "2064575" "3059441" "4829681" "1190797"
 [1534] "1098876" "2425032" "1093847" "3440582" "1590693" "1539719" "5059919"
 [1541] "5041651" "1694055" "2595563" "1208674" "3578773" "3844844" "2774920"
 [1548] "5145976" "4345131" "3275741" "2363481" "1614694" "3928091" "2586012"
 [1555] "3876111" "5491179" "3305799" "5802770" "3628725" "2174877" "1092875"
 [1562] "4900584" "1325393" "2590502" "2634701" "1258957" "5655013" "4909149"
 [1569] "3845648" "4972642" "5930674" "1170564" "5701558" "5075662" "2197105"
 [1576] "4941429" "3811556" "2029358" "5181300" "5640599" "1036379" "4523274"
 [1583] "2022813" "1633111" "4161020" "5452371" "4485473" "4673410" "2972063"
 [1590] "2267815" "3799990" "5139101" "3924001" "2302451" "1461255" "2286397"
 [1597] "2483708" "1533097" "1165465" "5734640" "6007411" "5486279" "4709793"
 [1604] "1481583" "1064336" "4006270" "5403816" "5835116" "4506769" "5601352"
 [1611] "3210677" "3861677" "1528071" "5473350" "3747601" "5651851" "2921552"
 [1618] "1132346" "5693566" "3898670" "1265607" "1028209" "2160870" "3476246"
 [1625] "4430926" "2075635" "2115920" "2390527" "5546560" "2970375" "3945409"
 [1632] "2795486" "2424531" "5715339" "1533568" "1784347" "1298325" "1842337"
 [1639] "1166007" "1476809" "5693427" "1975595" "4320645" "5560656" "4633181"
 [1646] "5886081" "1660373" "3683181" "5138728" "1557023" "2349934" "5680745"
 [1653] "3457825" "3689926" "5274159" "1942898" "5003621" "2570797" "4080865"
 [1660] "3294336" "5772372" "3774672" "5473876" "1809777" "4637409" "4076222"
 [1667] "4774186" "4757058" "1169191" "1417709" "1964472" "5711417" "4549608"
 [1674] "1042616" "3898684" "2216118" "2297001" "3463083" "5094062" "3870904"
 [1681] "5385330" "1802663" "5712315" "5239840" "5135717" "1427668" "3362254"
 [1688] "2594773" "1037900" "1901173" "2491587" "5582042" "1587516" "2529315"
 [1695] "1065575" "4983458" "3181674" "5570041" "5683306" "2435149" "2040001"
 [1702] "3415841" "1482486" "5867878" "4349587" "1964016" "1045955" "3822387"
 [1709] "4578338" "4412670" "5345608" "3509336" "5363492" "1533745" "3195888"
 [1716] "3918928" "5161968" "3690126" "3713009" "5534832" "3252157" "2875266"
 [1723] "2256855" "2998078" "3902535" "5940284" "5711704" "2798994" "3217851"
 [1730] "5156606" "2883089" "4409028" "3245539" "4640495" "4255979" "1195993"
 [1737] "3681006" "2167417" "1920481" "2414798" "2272932" "3883459" "2235322"
 [1744] "4402446" "1009248" "3023686" "3423107" "3327624" "3126528" "5123352"
 [1751] "4919430" "4636959" "4065536" "2992921" "2879421" "5966646" "3761826"
 [1758] "1469854" "1350041" "1616922" "1382739" "1814512" "5030551" "5772684"
 [1765] "5639603" "2226279" "4174831" "1239486" "5219977" "4876342" "1202744"
 [1772] "1395352" "4456499" "2855722" "4570405" "2109136" "5454406" "3118970"
 [1779] "1628495" "4785577" "5736410" "4120797" "4310896" "4478566" "4992644"
 [1786] "1973712" "1740347" "5702299" "4255518" "5994659" "4767745" "2557461"

In [43]:
vcf_lines

ERROR: Error in eval(expr, envir, enclos): object 'vcf_lines' not found

In [41]:
idx_start <- 0
idx_end <- lines_per_chunk
for (chunk in 1:chunks){
    
    msg <- paste("reading chunk",chunk,"of",chunks)
    write(msg, stdout())
    idx_end <- idx_end + lines_per_chunk
    idx_start <- idx_start + lines_per_chunk
    print(paste(idx_start,'-',idx_end))
    
}

reading chunk 1 of 8
[1] "0 - 1000"
reading chunk 2 of 8
[1] "1000 - 2000"
reading chunk 3 of 8
[1] "2000 - 3000"
reading chunk 4 of 8
[1] "3000 - 4000"
reading chunk 5 of 8
[1] "4000 - 5000"
reading chunk 6 of 8
[1] "5000 - 6000"
reading chunk 7 of 8
[1] "6000 - 7000"
reading chunk 8 of 8
[1] "7000 - 8000"

In [18]:
#md sed -n 5,8p


#iter_ <- 0
#stop_line <- 

cmd <- paste0("zcat ", args$in_vcf, " | grep -v '##' | sed -n 5,8p" )
cmd

[1] "zcat data/conditional/rare/combined/ukb_eur_wes_200k_chr21_maf0to5e-2_pLoF_damaging_missense.vcf.bgz | grep -v '##' | sed -n 5,8p"

In [19]:


# read in VCF
#cmd <- paste0("zcat ", args$in_vcf, " | grep -v '##' | head -n 500" )
d <- fread(cmd = cmd)

In [42]:
head(d)

  V1    V2 V3              V4   V5   V6 V7 V8 V9 V10 <U+22EF>   V176915 V176916
1 chr21  7 ENSG00000142173 fMTb okHJ .  .  .  DS 0   <U+22EF> 0       0
2 chr21  9 ENSG00000142185 nibn ppVn .  .  .  DS 0   <U+22EF> 0       0
3 chr21 11 ENSG00000142192 uFwA aBgc .  .  .  DS 0   <U+22EF> 0       0
4 chr21 12 ENSG00000142197 TACC dXNt .  .  .  DS 0   <U+22EF> 0       0
  V176917 V176918 V176919 V176920 V176921 V176922 V176923 V176924
1 0       0       0       0       0       0       0       0
2 0       0       0       0       0       0       0       0
3 0       0       0       0       0       0       0       0
4 0       0       0       0       0       0       0       0

In [5]:
path <- "data/conditional/rare/combined/test.txt.gz"
d <- fread(path, showProgress = TRUE, verbose = TRUE)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [6]:
dim(d)

[1]   7088 176924

In [63]:
# get columns with genotypes / metaid
genotype_cols <- suppressWarnings(!is.na(as.numeric(colnames(d))))
id_cols <- suppressWarnings(is.na(as.numeric(colnames(d))))

In [73]:
# Need to ensure that G is all numerics
G <- d[,genotype_cols, with = FALSE]
suppressWarnings(G[, names(G) := lapply(.SD, as.numeric)])

In [65]:
# read in phenotypes
phenotype <- args$phenotype
pheno_df <- fread(args$pheno_file)
stopifnot(phenotype %in% colnames(pheno_df))

# are there samples with missing covariates?
col_cov <- unlist(strsplit(readLines(args$covariates), split = ","))
lst <- lapply(col_cov, function(col){row_ok <- is.na(pheno_df[[col]])})
missing_cov <- rowSums(do.call(cbind, lst)) > 0
pheno_df <- pheno_df[!missing_cov, ]
msg <- paste("Note: Removed", sum(missing_cov),"samples with missing covariates.")
write(msg, stdout())

# get defined phenotypes
defined_phenos <- !is.na(pheno_df[[phenotype]])
eid_with_defined_phenos <- pheno_df$eid[defined_phenos]
stopifnot(length(eid_with_defined_phenos) > 0)

Note: Removed 20 samples with missing covariates.

In [66]:
# get subset of G which contains defiend phenotypes
G_with_defined_phenos <- colnames(G) %in% eid_with_defined_phenos
G_subset <- G[,G_with_defined_phenos, with = FALSE]

In [67]:
# Get allele count and hash for genotypes
G_subset_AC <- rowSums(G_subset, na.rm = TRUE)
G_subset_hash <- hash_genotypes(G_subset, "xxhash32")

In [69]:
id <- d[,id_cols, with = FALSE]
out <- data.table(
    chr = id$`#CHROM`, 
    pos = id$POS, 
    id = id$ID, 
    ref = id$REF,
    alt = id$ALT
)

In [70]:
# generate allele count outfile
outfile_ac <- paste0(args$out_prefix,"_AC.txt.gz")
out[[phenotype]] <- G_subset_AC
#fwrite(out, outfile_ac, sep = '\t')

In [71]:
# generate allele count outfile
outfile_hash <- paste0(args$out_prefix,"_AC.txt.gz")
out[[phenotype]] <- G_subset_hash
#fwrite(out, outfile_hash, sep = '\t')

In [72]:
out

       chr    pos      id                                       ref
1      chr21    1      ENSG00000141956                          UpSX
2      chr21    2      ENSG00000141959                          mGzq
3      chr21    4      ENSG00000142156                          UpCp
4      chr21    7      ENSG00000142173                          fMTb
5      chr21    9      ENSG00000142185                          nibn
6      chr21   11      ENSG00000142192                          uFwA
7      chr21   12      ENSG00000142197                          TACC
8      chr21   13      ENSG00000142207                          tdbv
9      chr21   28      ENSG00000155313                          fVIj
10     chr21   30      ENSG00000156253                          ccpx
11     chr21   36      ENSG00000156284                          CFfn
12     chr21   38      ENSG00000156304                          HRua
13     chr21   42      ENSG00000157551                          aPeI
14     chr21   45      ENSG00000157578                          mPtp
15     chr21   46      ENSG00000157601                          riNj
16     chr21   50      ENSG00000159082                          noLT
17     chr21   59      ENSG00000159216                          vqsm
18     chr21   63      ENSG00000159259                          ClgV
19     chr21   64      ENSG00000159261                          cEbD
20     chr21   71      ENSG00000160183                          uhgF
21     chr21   73      ENSG00000160188                          RTEJ
22     chr21   74      ENSG00000160190                          vDzI
23     chr21   80      ENSG00000160208                          wRfY
24     chr21   86      ENSG00000160224                          NMLX
25     chr21   91      ENSG00000160282                          SwEp
26     chr21   97      ENSG00000160305                          Duqs
27     chr21  100      ENSG00000166265                          qojJ
28     chr21  104      ENSG00000171587                          TMel
29     chr21  105      ENSG00000173276                          pAAV
30     chr21  106      ENSG00000173638                          gFva
<U+22EE> <U+22EE> <U+22EE> <U+22EE>                                 <U+22EE>
470    chr21  25603922 chr21:25603922:C:T                       C
471    chr21  25606448 chr21:25606448:C:T                       C
472    chr21  25606470 chr21:25606470:T:C                       T
473    chr21  25606537 chr21:25606537:CT:C                      CT
474    chr21  25606548 chr21:25606548:G:A                       G
475    chr21  25606556 chr21:25606556:A:C                       A
476    chr21  25606610 chr21:25606610:A:T                       A
477    chr21  25606629 chr21:25606629:G:A                       G
478    chr21  25607402 chr21:25607402:C:T                       C
479    chr21  25639874 chr21:25639874:TG:T                      TG
480    chr21  25693770 chr21:25693770:C:G                       C
481    chr21  25693770 chr21:25693770:C:T                       C
482    chr21  25693827 chr21:25693827:G:A                       G
483    chr21  25698675 chr21:25698675:A:AG                      A
484    chr21  25698700 chr21:25698700:GA:G                      GA
485    chr21  25698742 chr21:25698742:C:T                       C
486    chr21  25698766 chr21:25698766:C:A                       C
487    chr21  25698767 chr21:25698767:C:T                       C
488    chr21  25702257 chr21:25702257:C:T                       C
489    chr21  25702267 chr21:25702267:TA:T                      TA
490    chr21  25705984 chr21:25705984:C:T                       C
491    chr21  25706003 chr21:25706003:T:A                       T
492    chr21  25706032 chr21:25706032:A:ATTTCCGTTTGTGGCCTTGGTGT A
493    chr21  25706050 chr21:25706050:G:C                       G
494    chr21  25724648 chr21:25724648:G:A                       G
495    chr21  25725268 chr21:25725268:C:G                       C
496    chr21  25725274 chr21:25725274:TTTGC:T                   TTTGC
497    chr21  25729635 chr21:25729635:G:A                       G
498    chr21  25729671 chr21:25729671:GT:G                      GT
499    chr21  25729761 chr21:25729761:CAG:C                     CAG
       alt                     BC_combined_primary_care
1      zBVE                    9080e1ea
2      EoIP                    5a4352bc
3      rWjl                    01ed5d56
4      okHJ                    ae8fbd0d
5      ppVn                    67cba766
6      aBgc                    a3dddb76
7      dXNt                    9b543033
8      TvnG                    42f34ac5
9      TKUz                    cb0e8b39
10     akFE                    88d8e344
11     oOAh                    294f33e2
12     IJac                    2fa993b4
13     WXoo                    c0aa3ed2
14     hSOj                    63f6924a
15     OBVw                    c88dd4fb
16     tsiw                    3c6f6187
17     Denr                    d8fec47b
18     dxfc                    a3473da5
19     mrAL                    117f870e
20     OBgR                    1a53a3b7
21     ncWw                    283ef5f4
22     mHMQ                    45e7951e
23     sMin                    7845ed10
24     cTRJ                    fe0c490c
25     KOPX                    a888411c
26     IBaf                    698456bc
27     ecAL                    939a536a
28     nVIa                    2b916eb5
29     YLQs                    24f48dfe
30     rxrs                    ee7b7a0f
<U+22EE> <U+22EE>                <U+22EE>
470    T                       55578dc3
471    T                       ca48bc7e
472    C                       a41850d1
473    C                       429f6e6b
474    A                       3db292b8
475    C                       0b571b4c
476    T                       cf9858cd
477    A                       5e190288
478    T                       79c8c460
479    T                       3448dd8e
480    G                       0b005cb1
481    T                       68b8e7be
482    A                       1ba32cca
483    AG                      e7308f60
484    G                       fa6e2759
485    T                       e2028f2f
486    A                       29cd19e1
487    T                       3ce02c82
488    T                       d1355a4a
489    T                       a13c2b1d
490    T                       458bc257
491    A                       577bdaf2
492    ATTTCCGTTTGTGGCCTTGGTGT b7212490
493    C                       6554306a
494    A                       bd3aebaa
495    G                       ddde6d05
496    T                       d2028fb2
497    A                       d0577ba9
498    G                       55c629e8
499    C                       f3bdd0aa