In [1]:
setwd('/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb')
library(data.table)
library(parallel)

In [66]:
fread_with_basename <- function(f){
    d <- fread(f)
    if (! "V1" %in% colnames(d)){
        file_sans_gz <- tools::file_path_sans_ext(basename(f))
        file_sans_txt <- tools::file_path_sans_ext(file_sans_gz)
        d$basename <- file_sans_txt
        return(d)
    } else {
        warning(paste(f, "had NA's in colname! Skipping.."))
        return(NULL)
    }
}

In [62]:
args <- list(
    spa_cts_dir = 'data/saige/output/cts/step2/',
    spa_bin_dir = 'data/saige/output/binary/step2/'
)

In [67]:
spa_cts_files <- NULL #list.files(args$spa_cts_dir, pattern = ".txt.gz", full.names = TRUE)[100:101]
spa_bin_files <- list.files(args$spa_bin_dir, pattern = ".txt.gz", full.names = TRUE)[233:235]

# read in all the SPA step 2 results
spa_cts_full <- do.call(rbind, lapply(spa_cts_files, fread_with_basename))
spa_bin_full <- do.call(rbind, lapply(spa_bin_files, fread_with_basename))

#print(head(spa_cts_full))
#print(head(spa_bin_full))

# write out gene-spa p-value pairs
spa_full <- rbind(
    spa_cts_full[,c("CHR","MarkerID","basename", "p.value", "Tstat")],
    spa_bin_full[,c("CHR","MarkerID","basename", "p.value", "Tstat")]
)
out_prefix_true_p <- paste0(args$out_prefix, "_true_p.tsv.gz")
#fwrite(spa_full, out_prefix_true_p, sep = '\t')

# write out genes and chromosomes used
spa_genes <- spa_full[,c("MarkerID","CHR")]
spa_genes <- spa_genes[!duplicated(spa_genes),]
out_prefix_genes <- paste0(args$out_prefix, "_genes.tsv.gz")
#fwrite(spa_genes, out_prefix_genes, sep = '\t')

Warning message in FUN(X[[i]], ...):
"data/saige/output/binary/step2//ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_damaging_missense.txt.gzhad NA's in colname! Skipping.."

In [68]:
spa_full

       CHR    MarkerID
1      chr1   ENSG00000014914
2      chr1   ENSG00000042781
3      chr1   ENSG00000065600
4      chr1   ENSG00000067533
5      chr1   ENSG00000094963
6      chr1   ENSG00000116731
7      chr1   ENSG00000116977
8      chr1   ENSG00000117115
9      chr1   ENSG00000120337
10     chr1   ENSG00000121310
11     chr1   ENSG00000121900
12     chr1   ENSG00000125703
13     chr1   ENSG00000127423
14     chr1   ENSG00000132854
15     chr1   ENSG00000134389
16     chr1   ENSG00000135773
17     chr1   ENSG00000135828
18     chr1   ENSG00000137959
19     chr1   ENSG00000142609
20     chr1   ENSG00000142621
21     chr1   ENSG00000142661
22     chr1   ENSG00000142733
23     chr1   ENSG00000142794
24     chr1   ENSG00000143199
25     chr1   ENSG00000143318
26     chr1   ENSG00000143341
27     chr1   ENSG00000143365
28     chr1   ENSG00000150337
29     chr1   ENSG00000154358
30     chr1   ENSG00000154451
<U+22EE> <U+22EE> <U+22EE>
2208   chr22  ENSG00000100191
2209   chr22  ENSG00000100228
2210   chr22  ENSG00000100243
2211   chr22  ENSG00000100285
2212   chr22  ENSG00000100345
2213   chr22  ENSG00000100346
2214   chr22  ENSG00000100360
2215   chr22  ENSG00000100364
2216   chr22  ENSG00000100412
2217   chr22  ENSG00000100427
2218   chr22  ENSG00000100429
2219   chr22  ENSG00000128309
2220   chr22  ENSG00000133454
2221   chr22  ENSG00000159307
2222   chr22  ENSG00000167065
2223   chr22  ENSG00000172404
2224   chr22  ENSG00000175329
2225   chr22  ENSG00000176177
2226   chr22  ENSG00000182257
2227   chr22  ENSG00000183569
2228   chr22  ENSG00000183579
2229   chr22  ENSG00000183765
2230   chr22  ENSG00000185133
2231   chr22  ENSG00000186976
2232   chr22  ENSG00000187045
2233   chr22  ENSG00000188130
2234   chr22  ENSG00000196431
2235   chr22  ENSG00000198951
2236   chr22  ENSG00000205560
2237   chr22  ENSG00000242259
       basename
1      ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
2      ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
3      ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
4      ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
5      ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
6      ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
7      ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
8      ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
9      ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
10     ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
11     ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
12     ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
13     ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
14     ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
15     ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
16     ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
17     ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
18     ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
19     ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
20     ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
21     ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
22     ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
23     ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
24     ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
25     ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
26     ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
27     ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
28     ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
29     ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
30     ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF
<U+22EE> <U+22EE>
2208   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2209   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2210   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2211   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2212   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2213   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2214   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2215   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2216   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2217   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2218   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2219   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2220   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2221   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2222   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2223   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2224   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2225   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2226   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2227   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2228   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2229   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2230   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2231   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2232   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2233   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2234   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2235   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2236   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
2237   ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF_damaging_missense
       p.value     Tstat
1      0.591879000 -0.5370350
2      0.761616000 -0.1767090
3      0.714899000 -0.2478340
4      0.727889000 -0.2303000
5      0.988281000  0.1061800
6      0.696426000 -0.2758330
7      0.309363000 -5.4784800
8      0.643448000 -0.3912630
9      0.846393000 -0.0733356
10     0.687159000 -0.3033870
11     0.692954000 -0.2731860
12     0.784797000 -0.1437930
13     0.543709000 -0.7068050
14     0.641141000  0.7205400
15     0.397714000 -1.3378200
16     0.734070000 -0.2226890
17     0.626709000 -0.4445500
18     0.688462000 -0.3087850
19     0.775063000 -0.1556390
20     0.000980968  3.7891800
21     0.812016000 -0.1096520
22     0.632195000 -0.4215770
23     0.678910000 -0.3293000
24     0.778216000 -0.1246510
25     0.762629000 -0.1757000
26     0.534527000 -0.6860520
27     0.801622000 -0.1223540
28     0.514817000 -0.7868890
29     0.651563000 -1.2537600
30     0.798142000  0.4399320
<U+22EE> <U+22EE>    <U+22EE>
2208   0.99188600   0.0192987
2209   0.72010800  -0.2371820
2210   0.81792800  -0.1025870
2211   0.61535200  -0.4652470
2212   0.42215800  -1.1271300
2213   0.06442670   0.8366340
2214   0.69220600  -0.2942600
2215   0.65663000  -0.3684100
2216   0.50758700   0.9129920
2217   0.78580900  -0.1144740
2218   0.75206900  -0.1911780
2219   0.55427000  -0.6632870
2220   0.36714400  -1.5055500
2221   0.01954490   3.2273900
2222   0.53075700  -0.7290270
2223   0.87217100  -0.0509859
2224   0.05238990   1.6253200
2225   0.54359200  -0.6643670
2226   0.76344400  -0.1726120
2227   0.77235600  -0.1614730
2228   0.73985900  -0.2121660
2229   0.00967746   3.4120400
2230   0.64763500  -0.3428120
2231   0.02446710   1.8247500
2232   0.04804370   1.7028200
2233   0.64794300  -0.3171980
2234   0.43574000   1.0445700
2235   0.13171100   1.4845900
2236   0.31841500   1.1953200
2237   0.84391000  -0.0756015

In [49]:
head(fread("data/saige/output/binary/step2//ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_damaging_missense.txt.gz"))

  V1   V2 V3              V4 V5 V6  V7          V8 V9        V10      V11
1 chr2 1  ENSG00000006607 0  1  220 6.40127e-04 0  -0.275007 0.254391 -4.249520
2 chr2 1  ENSG00000018280 0  1   28 8.14707e-05 0  -0.535053 0.699647 -1.093050
3 chr2 1  ENSG00000021826 0  1    8 2.32773e-05 0  -0.527027 1.370320 -0.280665
4 chr2 1  ENSG00000023228 0  1    7 2.03677e-05 0  -0.569866 1.855500 -0.165521
5 chr2 1  ENSG00000049323 0  1    6 1.74580e-05 0  -0.536388 1.249630 -0.343489
6 chr2 1  ENSG00000064933 0  1    6 1.74580e-05 0  -0.523768 1.594830 -0.205927
  V12       V13      V14      V15   V16         V17         V18  V19
1 15.452400 0.279679 0.279679 FALSE 0.000304044 6.53504e-04 6578 165263
2  2.042880 0.444422 0.444422 FALSE 0.000000000 8.47135e-05 6578 165263
3  0.532544 0.700533 0.700533 FALSE 0.000000000 2.42038e-05 6578 165263
4  0.290456 0.758750 0.758750 FALSE 0.000000000 2.11784e-05 6578 165263
5  0.640374 0.667752 0.667752 FALSE 0.000000000 1.81529e-05 6578 165263
6  0.393164 0.742596 0.742596 FALSE 0.000000000 1.81529e-05 6578 165263

In [50]:
head(fread("data/saige/output/binary/step2//ukb_eur_wes_200k_maf0to5e-2_RF_acute_combined_pLoF.txt.gz"
))

  CHR  POS MarkerID        Allele1 Allele2 AC_Allele2 AF_Allele2  MissingRate
1 chr1 1   ENSG00000014914 0       1        14        4.07353e-05 0
2 chr1 1   ENSG00000042781 0       1         6        1.74580e-05 0
3 chr1 1   ENSG00000065600 0       1         9        2.61870e-05 0
4 chr1 1   ENSG00000067533 0       1         6        1.74580e-05 0
5 chr1 1   ENSG00000094963 0       1       725        2.10951e-03 0
6 chr1 1   ENSG00000116731 0       1         6        1.74580e-05 0
  BETA        SE       Tstat     var       p.value  p.value.NA Is.SPA
1 -0.53519600 0.998286 -0.537035  1.003440 0.591879 0.591879   FALSE
2 -0.52078200 1.716720 -0.176709  0.339315 0.761616 0.761616   FALSE
3 -0.53839600 1.473910 -0.247834  0.460319 0.714899 0.714899   FALSE
4 -0.52565600 1.510790 -0.230300  0.438118 0.727889 0.727889   FALSE
5  0.00203199 0.138337  0.106180 52.254300 0.988281 0.988281   FALSE
6 -0.55184500 1.414440 -0.275833  0.499837 0.696426 0.696426   FALSE
  AF_case    AF_ctrl     N_case N_ctrl
1 0.00000000 4.23567e-05 6578   165263
2 0.00000000 1.81529e-05 6578   165263
3 0.00000000 2.72293e-05 6578   165263
4 0.00000000 1.81529e-05 6578   165263
5 0.00212831 2.10876e-03 6578   165263
6 0.00000000 1.81529e-05 6578   165263

In [2]:
d <- fread('data/permute/genes/chr21/ukb_eur_wes_200k_pLoF_damaging_missense_chr21_ENSG00000141956.tsv.gz')

In [3]:
# simple method but still a bit slow
shuffle_knockouts <- function(d){
    d$KO <- rbinom(n=nrow(d), size=1, prob = d$pTKO)
    d$pKO <- ifelse((d$KO == 1), 1,
             ifelse((d$phased_het == 1 & d$unphased_het > 0), 1 - 1*(1/2)^d$unphased_het,
             ifelse((d$phased_het == 0 & d$unphased_het > 1), 1 - 2*(1/2)^d$unphased_het, 0)))
    return(d$pKO)
}

In [7]:

detectCores()
cl <- makeCluster(detectCores()-1)  
clusterEvalQ(cl,library(data.table))
clusterExport(cl,c("d"))
clusterExport(cl,c("shuffle_knockouts"))

[1] 48

[[1]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[2]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[3]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[4]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[5]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[6]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[7]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[8]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[9]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[10]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[11]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[12]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[13]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[14]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[15]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[16]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[17]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[18]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[19]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[20]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[21]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[22]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[23]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[24]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[25]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[26]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[27]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[28]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[29]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[30]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[31]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[32]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[33]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[34]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[35]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[36]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[37]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[38]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[39]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[40]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[41]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[42]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[43]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[44]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[45]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[46]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[47]]
[1] "data.table" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

In [8]:
system.time(parLapply(cl, 1:48, function(i) { 
    set.seed(i)
    samp <- replicate(10, shuffle_knockouts(d))
    rownames(samp) <- d$s
    samp <- data.table(t(samp))
    return(samp)
} ))

ERROR: Error in unserialize(node$con): error reading from connection

Timing stopped at: 1.639 0.202 8.534

In [ ]:
system.time(replicate(48*10, shuffle_knockouts(d)))

In [ ]:
stopCluster(cl)