In [1]:
library(data.table)

In [2]:
setwd('/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb')

In [23]:
files <- list.files('data/permute/permutations/', pattern = "*empirical_p.txt$", recursive = TRUE, full.names = TRUE)

In [41]:
files[grepl("ENSG00000109016", files)]

[1] "data/permute/permutations//chr17/ENSG00000109016/ukb_eur_wes_200k_pLoF_damaging_missense_permuted_chr17_ENSG00000109016_empirical_p.txt"

In [27]:
d <- do.call(rbind, lapply(files, fread, header = FALSE))

In [31]:
table(d$V7)

          OK    OK (gene) OK (min_mac)
          34         1224          504

In [38]:
d <- d[d$V6 %in% c(NA) & ( ! d$V7 %in% c("OK (gene)", "OK (min_mac)")) | d$V7 %in% "OK" ]

In [39]:
d

       V1              V2                                V3       V4
1      ENSG00000092621 Alanine_aminotransferase_residual    10000 0.0242823
2      ENSG00000142609 Alanine_aminotransferase_residual    10000 0.9282300
3      ENSG00000169962 Alanine_aminotransferase_residual    10000 0.3263560
4      ENSG00000148606 Alanine_aminotransferase_residual    10000 0.9334390
5      ENSG00000110031 Alanine_aminotransferase_residual    10000 0.0409139
6      ENSG00000111266 Alanine_aminotransferase_residual    10000 0.6299350
7      ENSG00000134531 Alanine_aminotransferase_residual    10000 0.1139820
8      ENSG00000134531 Alanine_aminotransferase_residual   100000 0.1139820
9      ENSG00000134531 Alanine_aminotransferase_residual  1000000 0.1139820
10     ENSG00000134531 Alanine_aminotransferase_residual    10000 0.1139820
11     ENSG00000134531 Alanine_aminotransferase_residual   100000 0.1139820
12     ENSG00000134531 Alanine_aminotransferase_residual  1000000 0.1139820
13     ENSG00000134531 Alanine_aminotransferase_residual 10000000 0.1139820
14     ENSG00000136153 Alanine_aminotransferase_residual    10000 0.6786890
15     ENSG00000140465 Alanine_aminotransferase_residual    10000 0.8318810
16     ENSG00000140545 Alanine_aminotransferase_residual    10000 0.4327270
17     ENSG00000103037 Alanine_aminotransferase_residual    10000 0.4186980
18     ENSG00000092929 Alanine_aminotransferase_residual    10000 0.3566080
19     ENSG00000109016 Alanine_aminotransferase_residual    10000 0.3133310
20     ENSG00000109016 Alanine_aminotransferase_residual   100000 0.3133310
21     ENSG00000109016 Alanine_aminotransferase_residual  1000000 0.3133310
22     ENSG00000109016 Alanine_aminotransferase_residual    10000 0.3133310
23     ENSG00000109016 Alanine_aminotransferase_residual   100000 0.3133310
24     ENSG00000109016 Alanine_aminotransferase_residual  1000000 0.3133310
25     ENSG00000109016 Alanine_aminotransferase_residual 10000000 0.3133310
26     ENSG00000129204 Alanine_aminotransferase_residual    10000 0.3078640
27     ENSG00000196689 Alanine_aminotransferase_residual    10000 0.4091810
28     ENSG00000150656 Alanine_aminotransferase_residual    10000 0.4531830
29     ENSG00000160111 Alanine_aminotransferase_residual    10000 0.4141820
30     ENSG00000115221 Alanine_aminotransferase_residual    10000 0.5026080
<U+22EE> <U+22EE>        <U+22EE>                          <U+22EE> <U+22EE>
47     ENSG00000164175 Alanine_aminotransferase_residual    10000 0.0992442
48     ENSG00000204963 Alanine_aminotransferase_residual    10000 0.9029230
49     ENSG00000253305 Alanine_aminotransferase_residual    10000 0.5750590
50     ENSG00000112782 Alanine_aminotransferase_residual    10000 0.1600650
51     ENSG00000184465 Alanine_aminotransferase_residual    10000 0.8027590
52     ENSG00000198670 Alanine_aminotransferase_residual    10000 0.0855513
53     ENSG00000164692 Alanine_aminotransferase_residual    10000 0.4049910
54     ENSG00000164692 Alanine_aminotransferase_residual   100000 0.4049910
55     ENSG00000164692 Alanine_aminotransferase_residual  1000000 0.4049910
56     ENSG00000164692 Alanine_aminotransferase_residual    10000 0.4049910
57     ENSG00000164692 Alanine_aminotransferase_residual   100000 0.4049910
58     ENSG00000164692 Alanine_aminotransferase_residual  1000000 0.4049910
59     ENSG00000164692 Alanine_aminotransferase_residual 10000000 0.4049910
60     ENSG00000174469 Alanine_aminotransferase_residual    10000 0.6183010
61     ENSG00000156687 Alanine_aminotransferase_residual    10000 0.1121300
62     ENSG00000156687 Alanine_aminotransferase_residual   100000 0.1121300
63     ENSG00000156687 Alanine_aminotransferase_residual  1000000 0.1121300
64     ENSG00000156687 Alanine_aminotransferase_residual    10000 0.1121300
65     ENSG00000156687 Alanine_aminotransferase_residual   100000 0.1121300
66     ENSG00000156687 Alanine_aminotransferase_residual  1000000 0.1121300
67     ENSG00000156687 Alanine_aminotransferase_residual 10000000 0.1121300
68     ENSG00000175806 Alanine_aminotransferase_residual    10000 0.6273000
69     ENSG00000184156 Alanine_aminotransferase_residual    10000 0.3417090
70     ENSG00000096968 Alanine_aminotransferase_residual    10000 0.2147540
71     ENSG00000096968 Alanine_aminotransferase_residual   100000 0.2147540
72     ENSG00000096968 Alanine_aminotransferase_residual  1000000 0.2147540
73     ENSG00000096968 Alanine_aminotransferase_residual    10000 0.2147540
74     ENSG00000096968 Alanine_aminotransferase_residual   100000 0.2147540
75     ENSG00000096968 Alanine_aminotransferase_residual  1000000 0.2147540
76     ENSG00000096968 Alanine_aminotransferase_residual 10000000 0.2147540
       V5         V6        V7
1      0.01405120 0.2453472 OK
2      0.07661430 0.8869084 OK
3      0.02470840 0.6883034 OK
4      0.93343900 1.0000000 OK
5      0.00130709 0.2582085 OK
6      0.01422080 0.5235000 OK
7      0.76521600        NA NA
8      0.76521600        NA NA
9      0.76521600        NA NA
10     0.76521600        NA NA
11     0.76521600        NA NA
12     0.76521600        NA NA
13     0.76521600        NA NA
14     0.00479926 1.0000000 OK
15     0.03506740 0.7485000 OK
16     0.01492390 0.4965769 OK
17     0.10197200 0.8290023 OK
18     0.04499910 0.1316000 OK
19     0.41892000        NA NA
20     0.41892000        NA NA
21     0.41892000        NA NA
22     0.41892000        NA NA
23     0.41892000        NA NA
24     0.41892000        NA NA
25     0.41892000        NA NA
26     0.02417980 0.2009411 OK
27     0.28534200 0.3507058 OK
28     0.05267440 0.2217832 OK
29     0.04192530 0.2138428 OK
30     0.15237000 1.0000000 OK
<U+22EE> <U+22EE>   <U+22EE>  <U+22EE>
47     0.0804868  0.1541275 OK
48     0.1142820  0.7983274 OK
49     0.0533924  0.6115869 OK
50     0.1177460  1.0000000 OK
51     0.1165600  0.7032912 OK
52     0.0374186  0.0276000 OK
53     0.6531540         NA NA
54     0.6531540         NA NA
55     0.6531540         NA NA
56     0.6531540         NA NA
57     0.6531540         NA NA
58     0.6531540         NA NA
59     0.6531540         NA NA
60     0.0480550  0.6347078 OK
61     0.2575900         NA NA
62     0.2575900         NA NA
63     0.2575900         NA NA
64     0.2575900         NA NA
65     0.2575900         NA NA
66     0.2575900         NA NA
67     0.2575900         NA NA
68     0.4006880  1.0000000 OK
69     0.3417090  1.0000000 OK
70     0.2223570         NA NA
71     0.2223570         NA NA
72     0.2223570         NA NA
73     0.2223570         NA NA
74     0.2223570         NA NA
75     0.2223570         NA NA
76     0.2223570         NA NA

In [74]:
path <- "data/permute/permutations/chr7/ENSG00000164692/ukb_eur_wes_200k_pLoF_damaging_missense_permuted_chr7_ENSG00000164692_Alanine_aminotransferase_residual_merged.txt.gz"

In [75]:
x <- fread(path, tmpdir = "data/tmp/rtmp/")

In [82]:
x[x$AC_Allele2 == 4]

        CHR    POS    MarkerID        Allele1 Allele2 AC_Allele2 AF_Allele2
1       chr7    1     ENSG00000164692 X       Y       4          1.20247e-05
2       chr7    2     ENSG00000164692 X       Y       4          1.20247e-05
3       chr7    4     ENSG00000164692 X       Y       4          1.20247e-05
4       chr7    8     ENSG00000164692 X       Y       4          1.20247e-05
5       chr7    9     ENSG00000164692 X       Y       4          1.20247e-05
6       chr7   13     ENSG00000164692 X       Y       4          1.20247e-05
7       chr7   14     ENSG00000164692 X       Y       4          1.20247e-05
8       chr7   16     ENSG00000164692 X       Y       4          1.20247e-05
9       chr7   17     ENSG00000164692 X       Y       4          1.20247e-05
10      chr7   18     ENSG00000164692 X       Y       4          1.20247e-05
11      chr7   19     ENSG00000164692 X       Y       4          1.20247e-05
12      chr7   24     ENSG00000164692 X       Y       4          1.20247e-05
13      chr7   26     ENSG00000164692 X       Y       4          1.20247e-05
14      chr7   28     ENSG00000164692 X       Y       4          1.20247e-05
15      chr7   31     ENSG00000164692 X       Y       4          1.20247e-05
16      chr7   35     ENSG00000164692 X       Y       4          1.20247e-05
17      chr7   40     ENSG00000164692 X       Y       4          1.20247e-05
18      chr7   41     ENSG00000164692 X       Y       4          1.20247e-05
19      chr7   44     ENSG00000164692 X       Y       4          1.20247e-05
20      chr7   45     ENSG00000164692 X       Y       4          1.20247e-05
21      chr7   48     ENSG00000164692 X       Y       4          1.20247e-05
22      chr7   51     ENSG00000164692 X       Y       4          1.20247e-05
23      chr7   52     ENSG00000164692 X       Y       4          1.20247e-05
24      chr7   59     ENSG00000164692 X       Y       4          1.20247e-05
25      chr7   63     ENSG00000164692 X       Y       4          1.20247e-05
26      chr7   65     ENSG00000164692 X       Y       4          1.20247e-05
27      chr7   67     ENSG00000164692 X       Y       4          1.20247e-05
28      chr7   68     ENSG00000164692 X       Y       4          1.20247e-05
29      chr7   71     ENSG00000164692 X       Y       4          1.20247e-05
30      chr7   72     ENSG00000164692 X       Y       4          1.20247e-05
<U+22EE>  <U+22EE> <U+22EE> <U+22EE>        <U+22EE> <U+22EE> <U+22EE>   <U+22EE>
3747967 chr7   9941   ENSG00000164692 X       Y       4          1.20247e-05
3747968 chr7   9943   ENSG00000164692 X       Y       4          1.20247e-05
3747969 chr7   9944   ENSG00000164692 X       Y       4          1.20247e-05
3747970 chr7   9945   ENSG00000164692 X       Y       4          1.20247e-05
3747971 chr7   9946   ENSG00000164692 X       Y       4          1.20247e-05
3747972 chr7   9947   ENSG00000164692 X       Y       4          1.20247e-05
3747973 chr7   9948   ENSG00000164692 X       Y       4          1.20247e-05
3747974 chr7   9952   ENSG00000164692 X       Y       4          1.20247e-05
3747975 chr7   9954   ENSG00000164692 X       Y       4          1.20247e-05
3747976 chr7   9959   ENSG00000164692 X       Y       4          1.20247e-05
3747977 chr7   9960   ENSG00000164692 X       Y       4          1.20247e-05
3747978 chr7   9961   ENSG00000164692 X       Y       4          1.20247e-05
3747979 chr7   9962   ENSG00000164692 X       Y       4          1.20247e-05
3747980 chr7   9963   ENSG00000164692 X       Y       4          1.20247e-05
3747981 chr7   9967   ENSG00000164692 X       Y       4          1.20247e-05
3747982 chr7   9968   ENSG00000164692 X       Y       4          1.20247e-05
3747983 chr7   9970   ENSG00000164692 X       Y       4          1.20247e-05
3747984 chr7   9974   ENSG00000164692 X       Y       4          1.20247e-05
3747985 chr7   9975   ENSG00000164692 X       Y       4          1.20247e-05
3747986 chr7   9977   ENSG00000164692 X       Y       4          1.20247e-05
3747987 chr7   9979   ENSG00000164692 X       Y       4          1.20247e-05
3747988 chr7   9981   ENSG00000164692 X       Y       4          1.20247e-05
3747989 chr7   9982   ENSG00000164692 X       Y       4          1.20247e-05
3747990 chr7   9983   ENSG00000164692 X       Y       4          1.20247e-05
3747991 chr7   9986   ENSG00000164692 X       Y       4          1.20247e-05
3747992 chr7   9990   ENSG00000164692 X       Y       4          1.20247e-05
3747993 chr7   9992   ENSG00000164692 X       Y       4          1.20247e-05
3747994 chr7   9994   ENSG00000164692 X       Y       4          1.20247e-05
3747995 chr7   9997   ENSG00000164692 X       Y       4          1.20247e-05
3747996 chr7   9999   ENSG00000164692 X       Y       4          1.20247e-05
        MissingRate BETA       SE       Tstat     var     p.value  N
1       0           -0.2028980 0.577203 -0.609003 3.00153 0.725199 166324
2       0           -0.0624300 0.577205 -0.187384 3.00151 0.913869 166324
3       0            0.2167620 0.577207  0.650609 3.00149 0.707262 166324
4       0           -0.0561891 0.577208 -0.168651 3.00148 0.922451 166324
5       0           -0.0561891 0.577208 -0.168651 3.00148 0.922451 166324
6       0            0.0700517 0.577210  0.210257 3.00145 0.903404 166324
7       0            0.0762939 0.577213  0.228991 3.00143 0.894845 166324
8       0           -0.0624300 0.577205 -0.187384 3.00151 0.913869 166324
9       0           -0.2028980 0.577203 -0.609003 3.00153 0.725199 166324
10      0           -0.0624300 0.577205 -0.187384 3.00151 0.913869 166324
11      0           -0.0624300 0.577205 -0.187384 3.00151 0.913869 166324
12      0            0.0762939 0.577213  0.228991 3.00143 0.894845 166324
13      0           -0.0561891 0.577208 -0.168651 3.00148 0.922451 166324
14      0           -0.0624300 0.577205 -0.187384 3.00151 0.913869 166324
15      0            0.0700517 0.577210  0.210257 3.00145 0.903404 166324
16      0            0.2167620 0.577207  0.650609 3.00149 0.707262 166324
17      0            0.0762939 0.577213  0.228991 3.00143 0.894845 166324
18      0           -0.2028980 0.577203 -0.609003 3.00153 0.725199 166324
19      0           -0.0624300 0.577205 -0.187384 3.00151 0.913869 166324
20      0           -0.0561891 0.577208 -0.168651 3.00148 0.922451 166324
21      0           -0.2028980 0.577203 -0.609003 3.00153 0.725199 166324
22      0            0.2167620 0.577207  0.650609 3.00149 0.707262 166324
23      0           -0.0624300 0.577205 -0.187384 3.00151 0.913869 166324
24      0           -0.0561891 0.577208 -0.168651 3.00148 0.922451 166324
25      0            0.2167620 0.577207  0.650609 3.00149 0.707262 166324
26      0            0.0700517 0.577210  0.210257 3.00145 0.903404 166324
27      0            0.0762939 0.577213  0.228991 3.00143 0.894845 166324
28      0           -0.0561891 0.577208 -0.168651 3.00148 0.922451 166324
29      0            0.2167620 0.577207  0.650609 3.00149 0.707262 166324
30      0            0.0700517 0.577210  0.210257 3.00145 0.903404 166324
<U+22EE>  <U+22EE>    <U+22EE>   <U+22EE> <U+22EE>  <U+22EE> <U+22EE> <U+22EE>
3747967 0            0.2167620 0.577207  0.650609 3.00149 0.707262 166324
3747968 0            0.0700517 0.577210  0.210257 3.00145 0.903404 166324
3747969 0           -0.2028980 0.577203 -0.609003 3.00153 0.725199 166324
3747970 0            0.0762939 0.577213  0.228991 3.00143 0.894845 166324
3747971 0           -0.0561891 0.577208 -0.168651 3.00148 0.922451 166324
3747972 0           -0.2028980 0.577203 -0.609003 3.00153 0.725199 166324
3747973 0            0.2167620 0.577207  0.650609 3.00149 0.707262 166324
3747974 0           -0.0561891 0.577208 -0.168651 3.00148 0.922451 166324
3747975 0           -0.2028980 0.577203 -0.609003 3.00153 0.725199 166324
3747976 0            0.0700517 0.577210  0.210257 3.00145 0.903404 166324
3747977 0           -0.0561891 0.577208 -0.168651 3.00148 0.922451 166324
3747978 0           -0.0561891 0.577208 -0.168651 3.00148 0.922451 166324
3747979 0            0.0762939 0.577213  0.228991 3.00143 0.894845 166324
3747980 0            0.0762939 0.577213  0.228991 3.00143 0.894845 166324
3747981 0            0.2167620 0.577207  0.650609 3.00149 0.707262 166324
3747982 0           -0.2028980 0.577203 -0.609003 3.00153 0.725199 166324
3747983 0           -0.0561891 0.577208 -0.168651 3.00148 0.922451 166324
3747984 0           -0.0624300 0.577205 -0.187384 3.00151 0.913869 166324
3747985 0           -0.0561891 0.577208 -0.168651 3.00148 0.922451 166324
3747986 0            0.2167620 0.577207  0.650609 3.00149 0.707262 166324
3747987 0           -0.0624300 0.577205 -0.187384 3.00151 0.913869 166324
3747988 0            0.0700517 0.577210  0.210257 3.00145 0.903404 166324
3747989 0           -0.2028980 0.577203 -0.609003 3.00153 0.725199 166324
3747990 0           -0.2028980 0.577203 -0.609003 3.00153 0.725199 166324
3747991 0            0.0700517 0.577210  0.210257 3.00145 0.903404 166324
3747992 0            0.2167620 0.577207  0.650609 3.00149 0.707262 166324
3747993 0            0.0762939 0.577213  0.228991 3.00143 0.894845 166324
3747994 0            0.0700517 0.577210  0.210257 3.00145 0.903404 166324
3747995 0            0.0762939 0.577213  0.228991 3.00143 0.894845 166324
3747996 0           -0.2028980 0.577203 -0.609003 3.00153 0.725199 166324

In [81]:
table(x$MissingRate)

      0
6874256

In [ ]:
0.0000001

In [77]:
0.0000001

[1] 1e-07

In [72]:
?fread

Warning message in seq_len(head.end.idx):
"first element used of 'length.out' argument"
ERROR while rich displaying an object: Error in seq_len(head.end.idx): argument must be coercible to non-negative integer

Traceback:
1. FUN(X[[i]], ...)
2. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
3. tryCatchList(expr, classes, parentenv, handlers)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
5. doTryCatch(return(expr), name, parentenv, handler)
6. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler)
7. repr::mime2repr[[mime]](obj)
8. repr_html.help_files_with_topic(obj)
9. repr_help_files_with_topic_generic(obj, Rd2HTML)

In [85]:
d <- fread('data/knockouts/alt/ukb_eur_wes_200k_chr7_maf0to5e-2_damaging_missense.tsv.gz', tmpdir = "data/tmp/rtmp/")

In [89]:
d <- d[d$gene_id %in% "ENSG00000164692",]
d

  gene_id         s       gts
1 ENSG00000164692 1326715 ["0|1","1|0"]
2 ENSG00000164692 1365568 ["0|1","0/1"]
3 ENSG00000164692 1466583 ["0/1","0/1"]
4 ENSG00000164692 1702288 ["0/1","0|1"]
5 ENSG00000164692 3717495 ["0|1","0/1"]
  varid                                     hom_alt_n phased.a1 phased.a2
1 ["chr7:94427672:G:A","chr7:94430340:G:A"] 0         1         1
2 ["chr7:94399073:C:T","chr7:94429245:A:G"] 0         0         1
3 ["chr7:94427794:G:T","chr7:94427795:A:G"] 0         0         0
4 ["chr7:94401610:C:T","chr7:94427672:G:A"] 0         0         1
5 ["chr7:94425757:G:A","chr7:94429429:C:T"] 0         0         1
  unphased.n pKO knockout
1 0          1.0 Compound heterozygote
2 1          0.5 Possible Compound heterozygote
3 2          0.5 Possible Compound heterozygote
4 1          0.5 Possible Compound heterozygote
5 1          0.5 Possible Compound heterozygote

In [90]:
d$DS <- d$pKO * 2

In [94]:
sum(d$pKO)

[1] 3