In [2]:
setwd("/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb")
library(data.table)

In [4]:
d <- fread("data/conditional/combined/test.txt")

In [10]:
all(d$POS == d$POS[rank(d$POS)])

[1] TRUE

In [11]:
all(d$POS == sort(d$POS))

[1] TRUE

In [14]:
sum(duplicated(d$ID))

[1] 0

In [19]:
lapply(d, function(x) sum(duplicated(x)))

$`#CHROM`
[1] 35978

$POS
[1] 1195

$ID
[1] 0

$REF
[1] 34985

$ALT
[1] 35302

In [22]:
sum(duplicated(d$POS))

[1] 1195

In [24]:
d[d$POS %in% c(394867),]

  #CHROM POS    ID              REF ALT
1 chr6   394867 chr6:394867:C:A C   A
2 chr6   394867 chr6:394867:C:T C   T

In [23]:
d[duplicated(d$POS),]

       #CHROM POS       ID                      REF    ALT
1      chr6    394867   chr6:394867:C:T         C      T
2      chr6    637793   chr6:637793:AG:A        AG     A
3      chr6   1313092   chr6:1313092:A:T        A      T
4      chr6   1610866   chr6:1610866:C:T        C      T
5      chr6   1611648   chr6:1611648:C:G        C      G
6      chr6   1611807   chr6:1611807:G:GGC      G      GGC
7      chr6   1726430   chr6:1726430:G:C        G      C
8      chr6   1742544   chr6:1742544:C:G        C      G
9      chr6   1742555   chr6:1742555:G:T        G      T
10     chr6   1960938   chr6:1960938:G:T        G      T
11     chr6   2679350   chr6:2679350:CA:C       CA     C
12     chr6   2683034   chr6:2683034:T:G        T      G
13     chr6   2783468   chr6:2783468:G:T        G      T
14     chr6   2895459   chr6:2895459:A:G        A      G
15     chr6   3015573   chr6:3015573:G:GGATGGAT G      GGATGGAT
16     chr6   3076908   chr6:3076908:G:C        G      C
17     chr6   3083211   chr6:3083211:G:C        G      C
18     chr6   3127319   chr6:3127319:C:T        C      T
19     chr6   3127323   chr6:3127323:G:T        G      T
20     chr6   3140452   chr6:3140452:A:T        A      T
21     chr6   3263723   chr6:3263723:TC:T       TC     T
22     chr6   3323985   chr6:3323985:G:C        G      C
23     chr6   3737186   chr6:3737186:G:T        G      T
24     chr6   3751477   chr6:3751477:AG:A       AG     A
25     chr6   3850526   chr6:3850526:A:T        A      T
26     chr6   4087727   chr6:4087727:G:GT       G      GT
27     chr6   5545263   chr6:5545263:C:T        C      T
28     chr6   5545264   chr6:5545264:G:C        G      C
29     chr6   5999201   chr6:5999201:G:T        G      T
30     chr6   6182065   chr6:6182065:A:T        A      T
<U+22EE> <U+22EE> <U+22EE>  <U+22EE>                <U+22EE> <U+22EE>
1166   chr6   166938988 chr6:166938988:T:G      T      G
1167   chr6   166948585 chr6:166948585:G:C      G      C
1168   chr6   167294632 chr6:167294632:A:T      A      T
1169   chr6   167296063 chr6:167296063:G:T      G      T
1170   chr6   167296104 chr6:167296104:C:G      C      G
1171   chr6   167298070 chr6:167298070:G:T      G      T
1172   chr6   167325221 chr6:167325221:G:T      G      T
1173   chr6   167898215 chr6:167898215:C:T      C      T
1174   chr6   168040064 chr6:168040064:G:C      G      C
1175   chr6   168061806 chr6:168061806:C:T      C      T
1176   chr6   168062910 chr6:168062910:C:T      C      T
1177   chr6   168064984 chr6:168064984:C:T      C      T
1178   chr6   168598991 chr6:168598991:G:C      G      C
1179   chr6   169220335 chr6:169220335:ACT:A    ACT    A
1180   chr6   169222207 chr6:169222207:G:C      G      C
1181   chr6   169223305 chr6:169223305:G:C      G      C
1182   chr6   169223401 chr6:169223401:C:T      C      T
1183   chr6   169225202 chr6:169225202:G:C      G      C
1184   chr6   169226199 chr6:169226199:AG:A     AG     A
1185   chr6   169232072 chr6:169232072:C:G      C      G
1186   chr6   169702659 chr6:169702659:T:G      T      G
1187   chr6   169702689 chr6:169702689:A:G      A      G
1188   chr6   169702690 chr6:169702690:T:G      T      G
1189   chr6   169704051 chr6:169704051:TG:T     TG     T
1190   chr6   169705174 chr6:169705174:C:T      C      T
1191   chr6   169712387 chr6:169712387:G:C      G      C
1192   chr6   169759017 chr6:169759017:G:C      G      C
1193   chr6   169759017 chr6:169759017:G:T      G      T
1194   chr6   170285032 chr6:170285032:C:T      C      T
1195   chr6   170388408 chr6:170388408:GGA:G    GGA    G