In [24]:
library(data.table)
library(stringr)
setwd("/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb")

In [49]:
args <- list(
    input_path = "data/simulation/phenotypes_new/ukb_eur_h2_1e-1_1e-1_pi_NA_NA_K_1e-1_chr21",
    covars_keep = "PC1,PC2",
    real_phenotype_path = "data/phenotypes/filtered_covar_phenotypes_cts.tsv.gz"
)

In [50]:
covars <- unlist(strsplit(args$covars_keep, split = ","))
d <- fread(args$real_phenotype_path)
d <- d[,colnames(d) %in% c("eid", covars), with = FALSE]

In [51]:
files <- list.files(dirname(args$input_path), pattern = basename(args$input_path), full.names = TRUE)
files <- files[!grepl('_genes',files)]

In [52]:
lst <- lapply(files, function(f){
   id <- str_extract(basename(f),"[0-9]+.tsv.gz")
   id <- gsub('\\.tsv\\.gz','', id)
   d <- fread(f)
   colnames(d)[2:ncol(d)] <- paste0(colnames(d)[2:ncol(d)],'_', id)
   return(d)
})

reduced <- Reduce(merge, lst)

In [53]:
head(d)

  eid     PC1       PC2
1 1000028 -11.34000 3.304250
2 1000034  -7.59207 0.766548
3 1000087 -11.36170 3.991620
4 1000118 -12.72040 5.578300
5 1000120 -11.03550 0.427943
6 1000162 -11.43270 2.185500

In [55]:
final <- merge(reduced, d, by.x = 's', by.y = 'eid', all.x = TRUE)

In [56]:
final

       s       y_no_noise_snp_5 y_no_noise_ko_5 y_cts_5   y_bin_5
1      1000028  0.00439460       0.010616        1.637300  TRUE
2      1000034  0.00029015      -0.151660       -0.699090 FALSE
3      1000087  0.00039548       0.010616       -0.445040 FALSE
4      1000118  0.08437000       0.010616        0.258600 FALSE
5      1000120  0.00044642       0.010616       -1.245000 FALSE
6      1000162  0.00039679       0.010616        0.344110 FALSE
7      1000171  0.08957300       0.010616        0.343960 FALSE
8      1000196  0.00028668       0.010616        0.509030 FALSE
9      1000254  0.00034108       0.010616        1.226600 FALSE
10     1000278  0.00027099       0.010616        0.500210 FALSE
11     1000297 -0.00089571       0.010616       -0.908410 FALSE
12     1000302  0.00028298       0.010616       -0.759880 FALSE
13     1000329  0.02559000       0.010616       -1.181800 FALSE
14     1000337 -0.04189900       0.010616        0.088171 FALSE
15     1000341  0.00034448       0.010616       -0.255620 FALSE
16     1000353  0.00450990       0.010616       -0.749810 FALSE
17     1000370  0.00577770       0.010616       -0.636140 FALSE
18     1000406  2.73980000       0.010616        2.558400  TRUE
19     1000427 -0.23635000       0.010616        1.310100  TRUE
20     1000465  0.00038903       0.010616       -0.221400 FALSE
21     1000473 -0.00092527       0.010616       -0.627660 FALSE
22     1000488 -0.00100760       0.010616       -1.611500 FALSE
23     1000508  0.01572500       0.010616       -0.457460 FALSE
24     1000566  0.23796000       0.010616       -0.028599 FALSE
25     1000579  0.00034182       0.010616       -0.768280 FALSE
26     1000582  0.00034108       0.010616        0.015912 FALSE
27     1000600  0.12594000      -0.151660        0.743040 FALSE
28     1000617  0.00029738       0.010616       -0.223740 FALSE
29     1000624  0.00028668       0.010616        0.042686 FALSE
30     1000636 -0.00030138       0.010616       -0.785340 FALSE
<U+22EE> <U+22EE> <U+22EE>         <U+22EE>        <U+22EE>  <U+22EE>
176886 6025692 -0.00100760       0.010616        0.53486  FALSE
176887 6025720  0.01000700       0.010616        0.14389  FALSE
176888 6025812  0.00037367       0.010616       -2.14310  FALSE
176889 6025864 -0.00100700       0.010616        1.15600  FALSE
176890 6025898 -0.00101790       0.010616        0.37211  FALSE
176891 6025901 -1.37740000       0.010616       -2.40900  FALSE
176892 6025913 -0.00101020      -0.226500       -0.47035  FALSE
176893 6025938  0.00036078       0.010616        1.35860   TRUE
176894 6025942 -0.10403000       0.010616        1.05260  FALSE
176895 6025967 -0.00095571       0.010616        0.96434  FALSE
176896 6025980 -1.50800000       0.010616       -2.96060  FALSE
176897 6025999 -0.00093544       0.010616        0.24111  FALSE
176898 6026004  0.56248000      -0.226500        1.83120   TRUE
176899 6026018  2.35590000       0.010616        2.47050   TRUE
176900 6026020 -0.00225430      -0.151660       -1.76660  FALSE
176901 6026128 -0.00089879       0.010616        0.79959  FALSE
176902 6026152  0.00039548       0.010616        0.24125  FALSE
176903 6026187  0.00032105       0.010616        1.38380   TRUE
176904 6026202 -0.00094107       0.010616       -1.50300  FALSE
176905 6026229 -0.18745000       0.010616        1.12340  FALSE
176906 6026237  0.01661900      -0.221660       -1.14930  FALSE
176907 6026268 -0.00089879       0.010616        1.18530  FALSE
176908 6026270 -0.00101010       0.010616       -0.70928  FALSE
176909 6026295  0.34104000       0.010616       -1.18780  FALSE
176910 6026311 -0.00102780       0.010616        1.04340  FALSE
176911 6026322 -0.10518000       0.010616       -0.32032  FALSE
176912 6026335  0.15706000       0.010616       -0.83270  FALSE
176913 6026383 -0.00095319       0.010616        1.54250   TRUE
176914 6026397  0.20488000       0.010616        0.66965  FALSE
176915 6026401  0.09360400       0.010616       -1.19920  FALSE
       y_no_noise_snp_6 y_no_noise_ko_6 y_cts_6    y_bin_6 y_no_noise_snp_7
1       7.5741e-03       0.535520       -0.9313600 FALSE    0.01371000
2       8.8764e-03      -0.010554       -1.2084000 FALSE    0.01069100
3       1.2118e-02      -0.010554       -0.1748100 FALSE   -0.00535460
4      -8.0357e-02      -0.010554        1.0180000 FALSE    0.50479000
5       1.2126e-02      -0.010554        0.5094000 FALSE   -0.00540760
6       1.2108e-02      -0.010554        0.7515500 FALSE   -0.00535380
7       2.1188e-01      -0.010554       -0.9750500 FALSE   -0.23091000
8       8.8746e-03      -0.010554       -0.3673800 FALSE    0.01068400
9       1.0496e-02      -0.010554        0.9152700 FALSE    0.00266480
10      8.8819e-03       0.535520        1.1886000 FALSE    0.01068500
11      3.1913e-03      -0.010554        0.0729130 FALSE   -0.00890480
12      8.8496e-03      -0.010554        0.5950300 FALSE    0.01066900
13      5.4483e-02      -0.010554        0.4949100 FALSE   -0.03748700
14     -2.2893e-01      -0.010554       -1.1293000 FALSE   -0.11125000
15      1.0485e-02      -0.010554        0.7896400 FALSE    0.00266900
16      9.2456e-03      -0.010554       -0.9978700 FALSE    0.00573820
17      1.8169e-02      -0.010554       -0.5760200 FALSE    0.00929490
18      9.1012e-01      -0.010554        1.9752000  TRUE   -0.22798000
19     -9.8048e-01      -0.010554        0.7680600 FALSE   -1.46900000
20      1.2122e-02      -0.010554        0.1549300 FALSE   -0.00534320
21      1.5709e-03      -0.010554        0.9616700 FALSE   -0.00089279
22     -6.5589e-05      -0.010554        0.6152500 FALSE    0.00713250
23     -5.7781e-02      -0.010554        0.9442300 FALSE   -0.00018292
24      7.4042e-02      -0.010554        0.3749200 FALSE   -0.00363960
25      1.0491e-02      -0.010554       -1.1259000 FALSE    0.00266520
26      1.0496e-02      -0.010554        0.8357700 FALSE    0.00266480
27      2.9182e-01      -0.010554        0.5639100 FALSE   -0.07225700
28      8.8928e-03      -0.010554       -0.8565000 FALSE    0.01068400
29      8.8746e-03      -0.010554       -0.8010500 FALSE    0.01068400
30      7.0619e-02      -0.010554       -0.0012798 FALSE   -0.10309000
<U+22EE> <U+22EE>         <U+22EE>        <U+22EE>   <U+22EE> <U+22EE>
176886 -6.5589e-05      -0.010554       -1.3027000 FALSE    0.00713250
176887  1.8563e-02      -0.010554        1.5066000  TRUE    0.00431130
176888  1.2070e-02      -0.010554        0.2458700 FALSE   -0.00532910
176889 -6.0574e-05      -0.010554        1.3073000  TRUE    0.00713560
176890 -6.3976e-05      -0.010554        0.7899900 FALSE    0.00713260
176891  8.5578e-01      -0.010554       -0.0083029 FALSE   -0.11186000
176892 -6.2347e-05      -0.010554        0.0815320 FALSE    0.00712670
176893  1.2132e-02      -0.010554        0.8152200 FALSE   -0.00536160
176894  2.0068e-01      -0.010554        0.6252700 FALSE    0.41212000
176895  1.5503e-03      -0.010554        1.0110000 FALSE   -0.00089399
176896  2.2470e-01      -0.010554       -0.2685400 FALSE   -0.94800000
176897  1.5678e-03      -0.010554        0.5196100 FALSE   -0.00088924
176898 -7.0105e-01      -0.010554       -1.7726000 FALSE   -0.14511000
176899  1.3578e+00      -0.010554        1.3212000  TRUE   -1.06930000
176900 -7.3840e-03      -0.010554       -0.9802900 FALSE   -0.00444070
176901  3.1781e-03      -0.010554       -0.2554800 FALSE   -0.00890620
176902  1.2118e-02      -0.010554       -0.5336400 FALSE   -0.00535460
176903  1.0483e-02      -0.010554        0.9087200 FALSE    0.00265660
176904  1.5515e-03       0.077458        1.9892000  TRUE   -0.00089552
176905 -3.6773e-01      -0.010554        0.4904700 FALSE    0.06948300
176906  7.3356e-04      -0.010554       -1.7723000 FALSE    0.07464500
176907  3.1781e-03      -0.010554        0.6168500 FALSE   -0.00890620
176908 -6.2494e-05      -0.010554        0.7863900 FALSE    0.00712440
176909  2.3341e-01      -0.010554        0.1996800 FALSE   -1.10220000
176910 -6.1179e-05      -0.010554       -0.3868000 FALSE    0.00711720
176911  7.8814e-02      -0.010554       -0.6794000 FALSE    0.09201000
176912  3.0017e-01      -0.010554       -0.3026600 FALSE    0.03877900
176913  1.5563e-03      -0.010554        0.1917000 FALSE   -0.00088685
176914  7.5136e-02      -0.010554        1.3307000  TRUE    0.06980000
176915  1.5274e-01      -0.010554        1.0042000 FALSE    0.08636500
       y_no_noise_ko_7 y_cts_7   y_bin_7 PC1       PC2
1      -0.02340         0.704610 FALSE   -11.34000 3.304250
2      -0.02340         0.578800 FALSE    -7.59207 0.766548
3      -0.02340        -0.045534 FALSE   -11.36170 3.991620
4      -0.02340        -1.596400 FALSE   -12.72040 5.578300
5      -0.02340        -1.671500 FALSE   -11.03550 0.427943
6      -0.02340        -1.284500 FALSE   -11.43270 2.185500
7      -0.02340        -0.411880 FALSE   -12.83620 3.911810
8      -0.02340        -1.251700 FALSE   -12.79490 1.853010
9      -0.02340        -0.999700 FALSE   -13.34800 3.208940
10     -0.02340        -0.233810 FALSE   -14.91800 3.083510
11     -0.02340         1.184800 FALSE   -15.34770 5.811400
12     -0.02340         0.248180 FALSE   -13.21500 4.684240
13     -0.02340        -0.587580 FALSE   -12.69900 3.985820
14     -0.02340        -0.639010 FALSE   -12.32170 3.084630
15     -0.02340         0.564840 FALSE   -10.33030 5.230870
16      0.49009         0.302070 FALSE   -12.21470 3.429380
17     -0.02340         0.197850 FALSE   -10.54770 2.954620
18     -0.02340        -1.078200 FALSE   -11.86460 2.090340
19     -0.02340        -1.895400 FALSE   -13.53390 3.289560
20     -0.02340         0.245200 FALSE    -9.59952 5.971710
21     -0.02340        -0.970080 FALSE   -13.80030 2.229400
22     -0.02340        -1.448600 FALSE   -12.78700 2.590580
23     -0.02340        -0.474110 FALSE   -13.50960 6.071120
24     -0.02340        -0.945710 FALSE   -13.24180 4.692420
25     -0.02340         0.785550 FALSE   -12.07340 3.212760
26     -0.02340        -0.520540 FALSE   -14.71800 5.071200
27     -0.02340        -0.934950 FALSE   -12.91420 5.510500
28     -0.02340        -0.595810 FALSE   -12.55910 0.658646
29     -0.02340        -0.013281 FALSE   -12.19320 3.594020
30     -0.02340        -0.601220 FALSE   -11.99570 6.504420
<U+22EE> <U+22EE>        <U+22EE>  <U+22EE> <U+22EE>  <U+22EE>
176886 -0.02340         0.679190 FALSE    -8.99563 3.0690200
176887 -0.02340        -0.352560 FALSE   -11.46410 4.3971000
176888 -0.02340        -0.144380 FALSE   -12.72840 4.1646800
176889 -0.02340         0.784830 FALSE   -13.65620 0.8464590
176890 -0.02340        -0.019784 FALSE   -12.43880 2.7363700
176891 -0.02340         0.555320 FALSE   -13.04550 3.7551300
176892 -0.02340        -0.849050 FALSE   -12.87260 4.1205300
176893 -0.02340         0.657730 FALSE   -12.85850 2.0472800
176894 -0.02340         0.749150 FALSE   -11.49590 0.0337021
176895 -0.02340        -0.442620 FALSE   -12.72960 6.5738500
176896 -0.02340        -0.456340 FALSE   -14.01190 2.7368000
176897 -0.02340        -0.504180 FALSE   -14.44010 3.6172400
176898 -0.02340         1.481200  TRUE   -11.64450 5.5047700
176899 -0.02340        -0.660430 FALSE   -10.14150 2.3404500
176900  1.23120         0.166650 FALSE   -12.66150 5.2299800
176901 -0.02340        -1.498100 FALSE   -12.16780 3.0118500
176902 -0.02340        -0.899170 FALSE   -11.90730 4.9731600
176903 -0.02340        -0.044592 FALSE   -14.50880 5.5131200
176904 -0.02340        -1.077000 FALSE   -11.51330 2.7156400
176905 -0.02340        -0.689840 FALSE   -11.27800 3.8466500
176906 -0.02340         0.104230 FALSE   -14.34190 2.9307000
176907 -0.02340         1.462300  TRUE   -14.60670 2.4666600
176908 -0.02340         0.520370 FALSE   -15.02700 3.1053100
176909  0.49009        -2.048900 FALSE    -6.93813 3.4333400
176910 -0.02340         0.970040 FALSE   -12.54590 4.6490100
176911 -0.02340         0.985470 FALSE   -10.01070 1.4682000
176912 -0.02340         1.004600 FALSE   -11.44730 2.2699000
176913  0.49009         2.814600  TRUE   -11.40030 1.6899200
176914 -0.02340        -0.548450 FALSE   -11.94400 3.2148100
176915 -0.02340         0.439140 FALSE   -14.81630 2.4880300