In [2]:
setwd("/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb")
library(data.table)
library(digest)
devtools::load_all("/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb/utils/modules/R/gwastools")

i Loading gwastools

In [20]:
args <- list(
    dir = "data/saige/output/binary/step2_common_cond/min_mac4/",
    regex = "ukb_eur_wes_200k_chr[0-9]+_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense$"
)

In [38]:
dir <- dirname(args$path)
regex <- basename(args$path)
files <- list.files(args$dir, pattern = args$regex, full.names = TRUE)
files_index <- paste0(files, ".index")
n <- length(files)
stopifnot(n >= 22)
# read files
lst <- lapply(files, fread)
lst <- lapply(files, unlink)
lst <- lapply(files_index, unlink)
d <- rbindlist(lst, fill = TRUE)
# order by chr and position
d$chr_int <- as.numeric(gsub("chr","",d$CHR))
d <- d[order(d$chr_int, d$POS),]
d$chr_int <- NULL

ERROR: Error in dirname(args$path): a character vector argument expected

 [1] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr10_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"
 [2] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr11_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"
 [3] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr12_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"
 [4] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr13_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"
 [5] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr14_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"
 [6] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr15_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"
 [7] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr16_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"
 [8] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr17_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"
 [9] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr18_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"
[10] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr19_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"
[11] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr1_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"
[12] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr20_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"
[13] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr21_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"
[14] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr22_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"
[15] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr2_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"
[16] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr3_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"
[17] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr4_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"
[18] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr5_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"
[19] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr6_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"
[20] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr7_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"
[21] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr8_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"
[22] "data/saige/output/binary/step2_common_cond/min_mac4//ukb_eur_wes_200k_chr9_maf0to5e-2_PSOR_combined_primary_care_pLoF_damaging_missense.index"

In [37]:
colnames(d)

 [1] "CHR"          "POS"          "MarkerID"     "Allele1"      "Allele2"
 [6] "AC_Allele2"   "AF_Allele2"   "MissingRate"  "BETA"         "SE"
[11] "Tstat"        "var"          "p.value"      "p.value.NA"   "Is.SPA"
[16] "AF_case"      "AF_ctrl"      "N_case"       "N_ctrl"       "BETA_c"
[21] "SE_c"         "Tstat_c"      "var_c"        "p.value_c"    "p.value.NA_c"

In [68]:
x <- lst[[6]]

In [69]:
head(x)

  CHR   POS MarkerID        Allele1 Allele2 AC_Allele2 AF_Allele2  MissingRate
1 chr15 10  ENSG00000062524 TfKm    CxwZ    10         2.83135e-05 0
2 chr15 12  ENSG00000066933 tNrT    BRSH     5         1.41568e-05 0
3 chr15 27  ENSG00000074621 KLhe    GWZJ    15         4.24703e-05 0
4 chr15 29  ENSG00000074803 LPKs    HHzP    54         1.52893e-04 0
5 chr15 36  ENSG00000092439 uilb    Drpz     6         1.69881e-05 0
6 chr15 39  ENSG00000092529 xkwk    kvwC    12         3.39762e-05 0
  BETA      SE       Tstat     var          p.value  p.value.NA Is.SPA AF_case
1      -Inf      Inf -0.490467 3.63394e-310 1.000000 1.000000    TRUE  0
2 -0.610266 1.810590 -0.186157  3.05042e-01 0.736077 0.736077   FALSE  0
3 -0.539142 0.911159 -0.649404  1.20451e+00 0.554045 0.554045   FALSE  0
4 -0.547418 0.506625 -2.132780  3.89606e+00 0.279911 0.279911   FALSE  0
5 -0.522366 1.459090 -0.245363  4.69715e-01 0.720338 0.720338   FALSE  0
6 -0.522960 1.103900 -0.429151  8.20618e-01 0.635686 0.635686   FALSE  0
  AF_ctrl     N_case N_ctrl
1 2.93991e-05 6521   170073
2 1.46996e-05 6521   170073
3 4.40987e-05 6521   170073
4 1.58755e-04 6521   170073
5 1.76395e-05 6521   170073
6 3.52790e-05 6521   170073

In [76]:
z <- x$BETA / x$SE

In [77]:
abs((pnorm(-abs(z),log.p=TRUE)+log(2))/log(10))

  [1]     0.000000     6.355913    23.262203    51.130535    90.026996
  [6]   139.973674   200.980606   273.053196   356.194686   450.407171
 [11]   555.692089   672.050462   799.483048   937.990424  1087.573036
 [16]  1248.231240  1419.965322  1602.775516  1796.662017  2001.624986
 [21]  2217.664563  2444.780863  2682.973988  2932.244026  3192.591053
 [26]  3464.015136  3746.516334  4040.094700  4344.750281  4660.483118
 [31]  4987.293249  5325.180708  5674.145525  6034.187729  6405.307344
 [36]  6787.504393  7180.778899  7585.130880  8000.560354  8427.067338
 [41]  8864.651846  9313.313894  9773.053494 10243.870658 10725.765397
 [46] 11218.737723 11722.787644 12237.915171 12764.120312 13301.403074
 [51] 13849.763467 14409.201496 14979.717168 15561.310490 16153.981468
 [56] 16757.730108 17372.556415 17998.460393 18635.442049 19283.501385
 [61] 19942.638408 20612.853120 21294.145526 21986.515629 22689.963434
 [66] 23404.488943 24130.092159 24866.773087 25614.531728 26373.368086
 [71] 27143.282163 27924.273961 28716.343484 29519.490734 30333.715713
 [76] 31159.018423 31995.398866 32842.857045 33701.392960 34571.006615
 [81] 35451.698011 36343.467149 37246.314032 38160.238660 39085.241036
 [86] 40021.321161 40968.479036 41926.714663 42896.028043 43876.419177
 [91] 44867.888067 45870.434714 46884.059119 47908.761283 48944.541208
 [96] 49991.398893 51049.334341 52118.347553 53198.438529 54289.607270

In [65]:
2 * pt(abs(z), df = nrow(x)-1, lower.tail = FALSE)

 [1] 0.04815333 0.98169366 0.60898087 0.72603754 0.14166581 0.45844684
 [7] 0.71550160 0.68566387 0.04807343 0.36841074 0.69546355 0.18438582
[13] 0.66273683 0.41398400 0.80205058 0.67567753 0.62957467 0.54113951
[19] 0.63576989 0.68877786 0.74251613 0.74178459 0.79850819 0.88162220
[25] 0.46221446 0.33353631 0.83384099 0.66632598 0.34669432 0.63147822
[31] 0.72652720 0.57505007 0.71571395 0.61430149 0.79057296 0.70398229
[37] 0.74660180 0.72855957 0.73888972 0.72302545 0.73277537 0.86406854
[43] 0.70243846 0.64221001 0.70902113 0.06144263 0.08325033 0.37239171
[49] 0.75664375 0.56678287 0.73076950 0.75074952 0.40584979 0.60369554
[55] 0.29250644 0.68732504 0.61599652 0.12226896 0.30485471

In [67]:
x$p.value

 [1] 0.0435213 0.9816140 0.6070280 0.7247620 0.1362480 0.4554320 0.7141700
 [8] 0.6841660 0.0434446 0.3646600 0.6940220 0.1791520 0.6611080 0.4106140
[15] 0.8011600 0.6741230 0.6277480 0.5387350 0.6339810 0.6872970 0.7413260
[22] 0.7405910 0.7976000 0.8811030 0.4592280 0.3294870 0.8331020 0.6647180
[29] 0.3427580 0.6296640 0.7252530 0.5728760 0.7143820 0.6123800 0.7896260
[36] 0.7025870 0.7454330 0.7272970 0.7376820 0.7217330 0.7315350 0.8634700
[43] 0.7010340 0.6404600 0.7076530 0.0564867 0.0779814 0.3686750 0.7555270
[50] 0.5645540 0.7295180 0.7496030 0.4024130 0.6017070 0.2881030 0.6858370
[57] 0.6140860 0.1168280 0.3005580

In [4]:
order_markers(c("chr4:144:A:G","chr4:133:T:G","chr4:133:T:G"))

Warning message in order_markers(c("chr4:144:A:G", "chr4:133:T:G", "chr4:133:T:G")):
"Some markers are duplicated. These have been discarded."

[1] "chr4:133:T:G" "chr4:144:A:G"

In [59]:
args <- list(
    infile = "data//conditional//common//combined//ukb_eur_wes_200k_chr6_maf0to5e-2_pLoF_damaging_missense_w_common_markers.txt",
    annotation = NULL,
    phenotype = "PSOR_combined",
    marker_col = 2,
    pheno_col = 5,
    annotation_col = 6,
    outfile = NULL
    
)

In [60]:
is.numeric(args$marker_col)

[1] TRUE

In [61]:
d <- fread(args$infile, header = FALSE)
n <- nrow(d)
if (n > 0){
    
    # check that input are indexes 
    stopifnot(is.numeric(args$marker_col))
    if (!is.null(args$pheno_col)) stopifnot(is.numeric(args$pheno_col))
    if (!is.null(args$annotation_col)) stopifnot(is.numeric(args$marker_col))
    
    # subset by phenptype column
    if (!is.null(args$phenotype)){
        phenotypes <- d[[args$pheno_col]]
        stopifnot(is.character(phenotypes))
        stopifnot(grepl('_',phenotypes))
        bool_pheno <- phenotypes == args$phenotype
        d <- d[bool_pheno, ]
    }
    
    # subset by annotation column
    if (!is.null(args$annotation)){
        annotations <- d[[args$annotation_col]]
        bool_annotations <- annotations == args$phenotype
        stopifnot(is.character(annotations))
        stopifnot(grepl('_', annotations))
        d <- d[bool_annotations, ]
    }
    
    # check markers format
    markers <- d[[args$marker_col]]
    regex <- "chr[0-9]+\\:[0-9]+\\:[a-zA-Z]+\\:[a-zA-Z]"
    if (any(!grepl(regex, markers))) stop("Markers are not formatted correctly!")
    markers <- gwastools::order_markers(markers)
    
    # write to stdout or a file
    if (!is.null(args$outfile)){
        cat(markers,file=args$outfile,sep="\n")
    } else {
        out <- paste(markers, collapse = ',')
        write(out, stdout())
    }
    
}

chr6:30991224:G:A,chr6:31284147:C:T,chr6:31354142:G:T

In [ ]:
]

In [20]:
head(d)

  V1 V2                V3           V4    V5
1 1  chr6:31284147:C:T 1.73995e-234 5e-06 PSOR_combined
2 2  chr6:31354142:G:T  1.38131e-20 5e-06 PSOR_combined
3 3  chr6:30991224:G:A  6.81467e-10 5e-06 PSOR_combined
  V6
1 chr6:31284147:C:T
2 chr6:31284147:C:T,chr6:31354142:G:T
3 chr6:31284147:C:T,chr6:31354142:G:T,chr6:30991224:G:A

In [12]:
head(d)

  V1 V2                V3           V4    V5
1 1  chr6:31284147:C:T 1.73995e-234 5e-06 PSOR_combined
2 2  chr6:31354142:G:T  1.38131e-20 5e-06 PSOR_combined
3 3  chr6:30991224:G:A  6.81467e-10 5e-06 PSOR_combined
4 1  chr6:31284147:C:T 4.80146e-262 5e-06 PSOR_combined_primary_care
5 2  chr6:31395920:C:T  1.21611e-18 5e-06 PSOR_combined_primary_care
6 3  chr6:32262943:G:C  6.75395e-11 5e-06 PSOR_combined_primary_care
  V6
1 chr6:31284147:C:T
2 chr6:31284147:C:T,chr6:31354142:G:T
3 chr6:31284147:C:T,chr6:31354142:G:T,chr6:30991224:G:A
4 chr6:31284147:C:T
5 chr6:31284147:C:T,chr6:31395920:C:T
6 chr6:31284147:C:T,chr6:31395920:C:T,chr6:32262943:G:C

In [ ]:
devtools::load_all("/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb/utils/modules/R/gwastools")
library(argparse)

main <- function(args){

    x <- args$markers
    stopifnot(x != "")
    markers <- unlist(strsplit(x, split = ','))
    ordered_markers <- order_markers(markers)
    out <- paste0(ordered_markers, collapse = ',')
    write(out, stdout())

}

In [119]:
gt_to_hash <- function(gt){
    gt <- gsub("\\|", "\\\\", gt)
    gt <- gsub("0/1", "1", gt)
    gt <- gsub("1/0", "1", gt)
    gt <- gsub("0/0", "0", gt)
    gt <- gsub("1/1", "2", gt)
    return(gt)
}

In [120]:
args <- list(
    in_vcf = "data/conditional/common/intervals/min_mac4/ukb_eur_wes_200k_maf0to5e-2_PSOR_combined_pLoF_damaging_missense.vcf.bgz"
)


 #chr6:31284147:C:T,chr6:31395920:C:T,chr6:32262943:G:C,chr6:29834773:C:T # grep -E (31284147)|(31395920)|(32262943)|(29834773)

In [145]:
# read in VCF
cmd <- paste0("zcat ", args$in_vcf, " | grep -v '#' | grep chr6 | grep -E '((31284147)|(31395920)|(32262943)|(29834773))'")
cmd
d <- fread(cmd = cmd)

[1] "zcat data/conditional/common/intervals/min_mac4/ukb_eur_wes_200k_maf0to5e-2_PSOR_combined_pLoF_damaging_missense.vcf.bgz | grep -v '#' | grep chr6 | grep -E '((31284147)|(31395920)|(32262943)|(29834773))'"

In [153]:
head(d, n = 1)

  V1   V2       V3        V4 V5 V6 V7 V8 V9 V10 <U+22EF>   V176594 V176595
1 chr6 29834773 rs2523793 C  T  .  .  .  GT 0/0 <U+22EF> 0/1     0/1
  V176596 V176597 V176598 V176599 V176600 V176601 V176602 V176603
1 0/0     0/0     0/0     0/0     0/1     0/0     0/0     0/0

In [182]:
# setup columns that contains genotypes or id variables
genotype_cols <- suppressWarnings(!is.na(as.numeric(colnames(d))))
id_cols <- suppressWarnings(is.na(as.numeric(colnames(d))))

In [184]:
# 
total_cols <- 1:ncol(d)
id_cols <- 1:which(as.logical(head(d, 1) %in% "GT"))
id_cols <- total_cols %in% id_cols
genotype_cols <-  (!id_cols)

In [176]:
any(genotype_cols)

[1] TRUE

In [188]:
stopifnot(any(genotype_cols))
stopifnot(any(id_cols))

In [189]:
# genotype matrix
G <- d[,genotype_cols, with = FALSE]

In [190]:
# setup data.table
id <- d[,id_cols, with = FALSE]
if (any("DS" %in% id$FORMAT)) stop("This script only accepts genotypes!")
dt <- data.table(chr = id$`#CHROM`, pos = id$POS, id = id$ID, ref = id$REF, alt = id$ALT)

In [191]:
# combine all gentotypes into a single string per variant
dt$gt_string <- unlist(apply(G, 1, function(x) as.character(paste(x, collapse = '-'))))
# convert genotype to dosage
dt$dosage_string <- gsub_to_dosage(dt$gt_string)
# create hash of the string
dt$dosage_hash <- unlist(lapply(dt$dosage_string, function(x) digest(x, algo="md5")))
# clean up
dt$gt_string <- NULL
dt$dosage_string <- NULL
dt$dosage_hash_dup <- as.numeric(duplicated(dt))

In [192]:
dt

  dosage_hash                      dosage_hash_dup
1 8fc9563ac3fb34d9a8060eca36947405 0
2 a838bef313c9239688afa3dd9302064f 0
3 309bea789024a8400d95619edc4ebcad 0
4 44ba86581d88f57bcc1fabe2f6b3b425 0

In [62]:
main <- function(args){

    stopifnot(file.exists(args$infile))
    d <- fread(args$infile, header = FALSE)
    n <- nrow(d)
    if (n > 0){

        # check that input are indexes
        stopifnot(is.numeric(args$marker_col))
        if (!is.null(args$pheno_col)) stopifnot(is.numeric(args$pheno_col))
        if (!is.null(args$annotation_col)) stopifnot(is.numeric(args$marker_col))

        # subset by phenptype column
        if (!is.null(args$phenotype)){
            phenotypes <- d[[args$pheno_col]]
            stopifnot(is.character(phenotypes))
            stopifnot(grepl('_',phenotypes))
            bool_pheno <- phenotypes == args$phenotype
            d <- d[bool_pheno, ]
        }

        # subset by annotation column
        if (!is.null(args$annotation)){
            annotations <- d[[args$annotation_col]]
            bool_annotations <- annotations == args$phenotype
            stopifnot(is.character(annotations))
            stopifnot(grepl('_', annotations))
            d <- d[bool_annotations, ]
        }

        # check markers format
        markers <- d[[args$marker_col]]
        regex <- "chr[0-9]+\\:[0-9]+\\:[a-zA-Z]+\\:[a-zA-Z]"
        if (any(!grepl(regex, markers))) stop("Markers are not formatted correctly!")
        markers <- gwastools::order_markers(markers)

    } else {
        markers <- ""
    }

    # write to stdout or a file
    if (!is.null(args$outfile)){
        cat(markers,file=args$outfile,sep="\n")
    } else {
        out <- paste(markers, collapse = ',')
        write(out, stdout())
    }


}

In [1]:
?digest

Warning message in seq_len(head.end.idx):
"first element used of 'length.out' argument"
ERROR while rich displaying an object: Error in seq_len(head.end.idx): argument must be coercible to non-negative integer

Traceback:
1. FUN(X[[i]], ...)
2. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
3. tryCatchList(expr, classes, parentenv, handlers)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
5. doTryCatch(return(expr), name, parentenv, handler)
6. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler)
7. repr::mime2repr[[mime]](obj)
8. repr_html.help_files_with_topic(obj)
9. repr_help_files_with_topic_generic(obj, Rd2HTML)